### ISSUE TITLE
Angular cli not working

### ISSUE THREAD

**Issue by Jodathan** [maximegris/angular-electron#1]
This is a nice repository. Exactly the thing i searched for so long. But is there a way to use the angular cli?

When i try to create a new component i get this error message;

`You have to be inside an angular-cli project in order to use the generate command.`

**Comment by maximegris** [comment]
Hi,

Thanks for your feedback !

If you run `ng -v`, what is the version of your angular-cli? If it's not 1.0.0, you may need to upgrade it.
You can try `npm install -g @angular/cli@latest` since the angular-cli has been renamed

**Comment by Jodathan** [comment]
Thank you very much. I uninstalled the beta release and installed the stable version 1.0.0. It works :)
