### ISSUE TITLE
production mode

### ISSUE THREAD

**Issue by ajagnanan** [maximegris/angular-electron#10]
Is it possible to build for production mode with npm run electron:dist? This way the environment vars are loaded from environment.prod.ts

**Comment by maximegris** [comment]
Hey,

There is an opened issue on AotPlugin (angular-cli/issues/5433) when webpack config is overridden.
I updated this project with the workaround mentionned in the issue. 
Now you can build for dev or prod mode. See 8549da1a17d946b4cc272d8baf9d4ad64fe4e458

`npm run electron:dist` is now replaced by two new commands:

* Using development variables (environments/index.ts) :  `npm run electron:dev`
* Using production variables (environments/index.prod.ts) :  `npm run electron:prod`

Regards

**Comment by abruneau** [comment]
I'm having an issue with production mode
`environment.production` keeps returning false even when running `npm run electron:prod`

Anyone with the same issue ?
