### ISSUE TITLE
Source ts files are missing in dev tools

### ISSUE THREAD

**Issue by moshefi** [maximegris/angular-electron#101]
Usually, a webpack folder appears in devtools in the source tab

**Comment by maximegris** [comment]
Usually we find more information in an issue than a single sentence without explanation. :)

**Comment by 5minutes2start** [comment]
@maximegris Same for me. When I start your demo project, open dev tools and try to look for any .ts file (e.g. "home.component.ts") - there is no any. There is only information that source map exist and "assosiated files should be addes to source tree"
