### ISSUE TITLE
Serialport Issues

### ISSUE THREAD

**Issue by jpiwek** [maximegris/angular-electron#103]
Hi,

in the past I wrote some applications in Nodejs+Typescript with SerialPort native module to communicate over RS232 with diffenrent hardware systems.

Now I would like to add serialport to my Angular-Electron app.
So I installed
npm install serialport --save
npm install @types/serialport --save

I placed "import * as SerialPort from 'serialport'" in "home.components.ts"
After invoking the code below nothing but errors:

`//List serial ports
SerialPort.list( (err:Error, ports:any[]) => {
      ports.forEach((port:any) => {
          console.log('Com Name ' +port.comName + 
                          ' | Manufac ' +port.manufacturer +
                          ' | Vendor ID '+ port.vendorId );
      });
  });

//open com port 4 
this.com = new SerialPort('COM4', {baudRate : 19200}, (err: Error) => {
      if (err) {
          console.log('Open Error: ', err.message);
      }
    });`

**Browser DevTool Log:**

  | getRoot | @ | vendor.bundle.js:87243
-- | -- | -- | --
  | bindings | @ | vendor.bundle.js:87139
  | ./node_modules/serialport/lib/bindings/linux.js | @ | vendor.bundle.js:109113
  | __webpack_require__ | @ | inline.bundle.js:55
  | (anonymous) | @ | vendor.bundle.js:108666
  | ./node_modules/serialport/lib/bindings/auto-detect.js | @ | vendor.bundle.js:108669
  | __webpack_require__ | @ | inline.bundle.js:55
  | ./node_modules/serialport/lib/index.js | @ | vendor.bundle.js:109589
  | __webpack_require__ | @ | inline.bundle.js:55
  | (anonymous) | @ | main.bundle.js:268
  | ./src/app/components/home/home.component.ts | @ | main.bundle.js:348
  | __webpack_require__ | @ | inline.bundle.js:55
  | ./src/app/app-routing.module.ts | @ | main.bundle.js:38
  | __webpack_require__ | @ | inline.bundle.js:55
  | ./src/app/app.module.ts | @ | main.bundle.js:164
  | __webpack_require__ | @ | inline.bundle.js:55
  | ./src/main.ts | @ | main.bundle.js:418
  | __webpack_require__ | @ | inline.bundle.js:55
  | 0 | @ | main.bundle.js:507
  | __webpack_require__ | @ | inline.bundle.js:55
  | webpackJsonpCallback | @ | inline.bundle.js:26
  | (anonymous) | @ | main.bundle.js:1

Any hint how to get it running? I need SerialPort support in my Angluar-Electron application.
In Python or C that's no problem.

Any help is appreciated
JP

**Comment by nutspanther** [comment]
Came here for this...

**Comment by jpiwek** [comment]
???

**Comment by jpiwek** [comment]
What do it mean?

**Comment by az114q** [comment]
`"scripts": [
      "../node_modules/qrcode/build/qrcode.min.js",
      "../node_modules/echarts/dist/echarts.min.js",
      "../node_modules/better-picker/dist/picker.min.js"
    ],`
you can find .angular-cli.json  file, add like this example,add your SerialPort  here ,try again.

**Comment by jf0** [comment]
Also trying to get this working, @az114q 's solution doesn't work for me. Did you find an answer @jpiwek ?

**Comment by nthjelme** [comment]
I had the same issue, solved it by running electron-rebuild on the serialport module in the dist/node_modules folder.

**Comment by jf0** [comment]
Sounds promising, how do you do this? I've tried adding:

```
"scripts": {
  "rebuild": "electron-rebuild -f -w serialport"
}
```

But no luck

**Comment by jf0** [comment]
Ok, got it. For anyone else who is encountering this issue, you need to add serialport as an external in webpack.config.js

```
module.exports = {
  "externals": {
    "serialport": "require('serialport')"
  }
}
```

I also added the following script to package.json

```
"scripts": {
    "postinstall": "electron-builder install-app-deps && electron-rebuild -f -w serialport"
}
```

Then it works

**Comment by jpiwek** [comment]
It works!!! Perfect! Serial interface runs!
![grafik](https://user-images.githubusercontent.com/32235471/36021791-3076dece-0d87-11e8-9c44-0925d41d0b51.png)

But when I start my application in browser mode (npm run start:web) it crashes!
![grafik](https://user-images.githubusercontent.com/32235471/36021859-66a08572-0d87-11e8-81e1-319a2a74233f.png)

**Comment by jf0** [comment]
start:web bypasses electron and just runs the webpack development server:

`"start:web": "webpack-dev-server --content-base . --port 4200 --inline"`

Adding a dependency as an external means that webpack does not bundle it, and instead expects it as an external dependency, see https://webpack.js.org/configuration/externals/. The external dependencies can be provided via CDN or by node.js (or electron's version in this case) if its a server side application. As this is now being run in the browser rather than server side, there is no external dependency that it can access.

There is likely some solution to be found by digging around in the webpack documentation, I just need it to run in electron though so I'm satisfied with the current solution.

**Comment by jpiwek** [comment]
At least the desktop app on Windows with serialport lib works!
See serial data on the right hand side in console log:
![grafik](https://user-images.githubusercontent.com/32235471/36071436-9f9f7422-0f0e-11e8-956b-14a53d9eccd0.png)
