### ISSUE TITLE
Visual Studio Code Debugging

### ISSUE THREAD

**Issue by thomashoegg** [maximegris/angular-electron#104]
Hi,

first,  I have to thank you for providing this boilerplate. I really like it. Do you have any idea how to enable visual studio code debugging with full source map support. I cannot make it run.

Thank you.
Best regards,
Thomas

**Comment by nccnm** [comment]
Can you check it: https://github.com/maximegris/angular-electron/issues/84#issuecomment-357424682

**Comment by maximegris** [comment]
Duplicate #84
