### ISSUE TITLE
Alternative and Inspiration

### ISSUE THREAD

**Issue by Kaffiend** [maximegris/angular-electron#106]
@maximegris I found an alternative means of doing live reload and HMR. Proxy the electron window with browser-sync or something of the sort. So far I've just had to wrap the CLI and proxy its development services. No ejection of the underlying webpack.
The seeds progress can be tracked here.
https://github.com/Kaffiend/electron-angular-ngrx

I also wanted to thank you for the inspiration this seed provided to build this one.

**Comment by maximegris** [comment]
Hi

Thank you for this idea & nice repo!
I had the time to do some refactoring on the project. 
In the current version (3.x.x), webpack is not ejected anymore. NPM scripts now use ng commands.
