### ISSUE TITLE
Reload not working after adding ngx charts 

### ISSUE THREAD

**Issue by ranakrunal9** [maximegris/angular-electron#107]
After adding [ngx-charts](https://github.com/swimlane/ngx-charts) and running it with `npm start` when we do Reload page from View menu its not working. Repository for reproduction is at [https://github.com/ranakrunal9/angular-electron/tree/charts](https://github.com/ranakrunal9/angular-electron/tree/charts)

![image](https://user-images.githubusercontent.com/12890329/34840700-ce7a6446-f72b-11e7-9519-d1e7f9acde48.png)

**Comment by maximegris** [comment]
Sorry, I have no time to investigate issues due to external librairies.

**Comment by ranakrunal9** [comment]
@maximegris I think its the similar issue #96 as i am getting `index.html` not found when i do reload or force reload.

**Comment by shaniqwa** [comment]
@ranakrunal9 theres an open issue in ngx-charts, i'm having similar issues. follow https://github.com/swimlane/ngx-charts/issues/703
