### ISSUE TITLE
<webview>Tag

### ISSUE THREAD

**Issue by az114q** [maximegris/angular-electron#109]
how can I use this tag in ng5+electron project

**Comment by LeoMartinDev** [comment]
My solution (read hot fix) right now is to create a Webview directive :

`import { Directive } from '@angular/core';

@Directive({
  selector: 'webview'
})
export class WebviewDirective {

  constructor() { }

}
`

**Comment by az114q** [comment]
ok,get ! thank you

**Comment by Y2zz** [comment]
It doesn't seem to work?

**Comment by goutamdh** [comment]
It does not work in that please help.
