### ISSUE TITLE
Not allowed to load local resource

### ISSUE THREAD

**Issue by mmick66** [maximegris/angular-electron#111]
I follow the instructions and I `run npm` start after installing. I get an error on the JS console:

```
Not allowed to load local resource: file:///Users/[path]/angular-electron/dist/index.html
```

**Comment by spetz83** [comment]
Yea, I get the same thing. builds fail. Sometimes the electron app will start with that error in the console window. It looks like the index.html file isn't being generated and put in the dist folder?

**Comment by AnouarGit** [comment]
running `tsc` before running `npm start` resolved the problem

**Comment by mmick66** [comment]
This gives me

```
node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts(34,40): error TS1005: ',' expected.
node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts(34,42): error TS1139: Type parameter declaration expected.
node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts(34,46): error TS1109: Expression expected.
node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts(34,51): error TS1005: ')' expected.
node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts(34,59): error TS1005: ';' expected.
node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts(34,60): error TS1128: Declaration or statement expected.
node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts(34,73): error TS1005: '(' expected.
```

**Comment by cjackson234** [comment]
What versions of node and typescript are you running? Updating those will likely solve your problem.

**Comment by spetz83** [comment]
So, this is what was causing it for me...

I am using rxjs/Observable in a service. There is a good chance that I am doing this wrong, but here is the offending code snippet:

`public getCoinById(id: String): any {
    return this.http.get(API_URL + id + '/').map(response => {
      return response.map((coin) => new Coin(coin));
    }).catch(this.derp);
  }`

So, the get method returns an instance of Observable<Object>. So, Response should be an Observable, right? Anyways, calling map on response returns the following error in my terminal when running npm start:

ERROR in src/app/services/coin.service.ts(21,23): error TS2339: Property 'map' does not exist on type 'Object'.

However, the electron window still opens and you get the "Not allowed to load local resource"

Fun fact: If I comment that return line out and run npm start I get no errors in the terminal and electron loads. Then, if I uncomment out that line and save, the hot reload kicks off and the uncommented code works just fine.... so this only happens during the initial run of npm start. I don't get why that is the case.

**Comment by ashecret** [comment]
@cousincockle is right. Electron build is showing inconsistent behaviour with **main.ts**. Running `tsc main.ts` before `npm start` solves the problem.

System config -
```
Node - 9.4.0
NPM - 5.6.0
Typescript - 2.6.2
```

**Comment by jakehockey10** [comment]
Running `tsc main.ts` first results in errors for me as well:

``` terminal
$ tsc main.ts
C:\Users\j.smith\source\repos\clarity-app\main.ts(1,1): error TS1008: Unexpected token; 'module, class, interface, enum, import or statement' expected.
C:\Users\j.smith\source\repos\clarity-app\main.ts(1,44): error TS1005: ';' expected.
C:\Users\j.smith\source\repos\clarity-app\main.ts(2,1): error TS1008: Unexpected token; 'module, class, interface, enum, import or statement' expected.
C:\Users\j.smith\source\repos\clarity-app\main.ts(2,8): error TS1008: Unexpected token; 'module, class, interface, enum, import or statement' expected.
C:\Users\j.smith\source\repos\clarity-app\main.ts(2,13): error TS1005: ';' expected.
C:\Users\j.smith\source\repos\clarity-app\main.ts(2,18): error TS1005: ';' expected.
C:\Users\j.smith\source\repos\clarity-app\main.ts(2,23): error TS1005: ';' expected.
C:\Users\j.smith\source\repos\clarity-app\main.ts(3,1): error TS1008: Unexpected token; 'module, class, interface, enum, import or statement' expected.
C:\Users\j.smith\source\repos\clarity-app\main.ts(3,8): error TS1008: Unexpected token; 'module, class, interface, enum, import or statement' expected.
C:\Users\j.smith\source\repos\clarity-app\main.ts(3,13): error TS1005: ';' expected.
C:\Users\j.smith\source\repos\clarity-app\main.ts(3,17): error TS1005: ';' expected.
C:\Users\j.smith\source\repos\clarity-app\main.ts(3,22): error TS1005: ';' expected.
C:\Users\j.smith\source\repos\clarity-app\main.ts(5,5): error TS1005: ';' expected.
C:\Users\j.smith\source\repos\clarity-app\main.ts(6,1): error TS1008: Unexpected token; 'module, class, interface, enum, import or statement' expected.
C:\Users\j.smith\source\repos\clarity-app\main.ts(15,3): error TS1008: Unexpected token; 'statement' expected.
C:\Users\j.smith\source\repos\clarity-app\main.ts(16,3): error TS1008: Unexpected token; 'statement' expected.
C:\Users\j.smith\source\repos\clarity-app\main.ts(18,3): error TS1008: Unexpected token; 'statement' expected.
C:\Users\j.smith\source\repos\clarity-app\main.ts(19,3): error TS1008: Unexpected token; 'statement' expected.
```

My TypeScript version is 2.6, but I'm also trying this with TypeScript 2.7.  My `tsc` version is 1.0.3.0.  Node is 9.4.0 and npm is 5.6.0.

**Comment by maximegris** [comment]
Typescript & Angular versions must be compatible 
Does the problem persist or can I close the issue ?

**Comment by NathofGod** [comment]
> I follow the instructions and I `run npm` start after installing. I get an error on the JS console:
> 
> ```
> Not allowed to load local resource: file:///Users/[path]/angular-electron/dist/index.html
> ```

I get the same when building for Windows, did you manage to resolve?

**Comment by khiopsrelease** [comment]
Adding this :

```
{
  "from": "../dist",
  "filter": ["**/*"]
}
```
into "files" section of electron-builder.json fixed the issue for me.

**Comment by stephanebouget** [comment]
Adding this :

```
{
  "from": "../dist",
  "filter": ["**/*"]
}
```
into "files" section of electron-builder.json fixed the issue for me.
