### ISSUE TITLE
Cannot generate component (or anything) using Angular-CLI.

### ISSUE THREAD

**Issue by Suroor-Ahmmad** [maximegris/angular-electron#115]
I'm trying to generate components using angular CLI, but it throws some error. 

Angular CLI - 1.6.5

Error:
Error: dryRunSink.commit(...).ignoreElements is not a function
dryRunSink.commit(...).ignoreElements is not a function

**Comment by maximegris** [comment]
you can't use Angular cli on the project (see other issue & readme)
