### ISSUE TITLE
Error: dryRunSink.commit(...).ignoreElements is not a function

### ISSUE THREAD

**Issue by subratawebops** [maximegris/angular-electron#116]
When trying to generate component (e.g. `ng g c hello`) from angular-cli, it throws this error:
```
Error: dryRunSink.commit(...).ignoreElements is not a function
dryRunSink.commit(...).ignoreElements is not a function
```
Stack:
```
@angular/cli: 1.6.4
node: 9.0.4
```

**Comment by AWeeks1** [comment]
Having the same issue with 
cli: 1.6.5 
node: 9.3.0

**Comment by joaomvfsantos** [comment]
At the moment I'm solving this with 

```
npm install @angular-devkit/schematics@0.0.45 @angular/cli --no-save
````

**Comment by DevJoseWeb** [comment]
ng g m agenda
Error: dryRunSink.commit(...).ignoreElements is not a function
dryRunSink.commit(...).ignoreElements is not a function

**Comment by Dinodanio** [comment]
Same here.
Stack:

Angular CLI: 1.6.5
Node: 9.2.1
OS: darwin x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.1.0
@angular/cli: 1.6.5
@angular/material: 5.1.0
@ngtools/json-schema: 1.1.0
typescript: 2.6.2
webpack-dev-server: 2.11.1
webpack: 3.10.0

**Comment by olakara** [comment]
I think this issue is only for CLI version 1.6.5 .. upgrading the CLI version to 1.6.6 solves the issue.

**Comment by haacki47** [comment]
@joaomvfsantos this method works.
I don't know what exactly mean '@angular-devkit/schematics' but i think it realates with my schematics installed on project. Currently i use '@nrwl/schematics'

**Comment by yassinesabri** [comment]
For those who still having this issue, upgrading to @angular-cli 1.6.6 or greater solves the problem
