### ISSUE TITLE
bug: @angular/cli version 1.6.4 causes webpack build to fail

### ISSUE THREAD

**Issue by mo2menelzeiny** [maximegris/angular-electron#118]
@angular/cli 1.6.4 removed the `InsertConcatAssetsWebpackPlugin`, and added `ScriptsWebpackPlugin`
I tried to make it work however I haven't succeeded on re-implementing the external scripts feature.
```
plugins.push(new InsertConcatAssetsWebpackPlugin([
                 ^
TypeError: InsertConcatAssetsWebpackPlugin is not a constructor
```
### UPDATE:
it's becasue the new cli version doesn't having this class, I just resolved this by replacing the `InsertConcatAssetsWebpackPlugin` with the new `ScriptsWebpackPlugin`. 

`const {BaseHrefWebpackPlugin, NamedLazyChunksWebpackPlugin, ScriptsWebpackPlugin} = require('@angular/cli/plugins/webpack');`

now in the implementation replace 
```
plugins.push(new InsertConcatAssetsWebpackPlugin([
      "scripts"
    ]));
```
with the new imported ScriptsWebpackPlugin implementation
```
plugins.push(new ScriptsWebpackPlugin({
      name: "scripts",
      sourceMap: true,
      scripts: scripts
    }));
```

**Comment by firrae** [comment]
I'm running 1.6.4 and had the same issue. After updating to ng-cli 1.6.7 though I'm now getting `Error: Cannot find module '@ngtools/webpack'` when I run `npm start`. Are these potentially connected issues?
