### ISSUE TITLE
[feature request] Separated angular serve

### ISSUE THREAD

**Issue by vorthess** [maximegris/angular-electron#12]
ng cli doenst work after eject. Also npm start runs webpack without server.
Can you and equivalent for `ng serve --open`?

The reason why I ask is very buggy behavior of electron serve and actually every time webpack rebuilds changes, electron crashes... Cant find reason why.

**Comment by maximegris** [comment]
Actually you have to do `npm start` & `npm run electron:serve in another terminal` (README)

If you want to have an equivalent for `ng serve --open`:
* First, install webpack-dev-server : `npm install --save-dev webpack-dev-server`

* You can edit start script or add a new script using webpack-dev-server
`webpack-dev-server --port=4200`

* Then edit main.js in root directory to watch the correct url in serve mode

```javascript
    let url = serve ?
       'http://localhost:4200'`:
      'file://' + __dirname + '/index.html';
```
* Maybe also remove this part in main.js 
```javascript
if (serve) {
  require('electron-reload')(__dirname + '/dist');
}
```

About ng-cli, can you tell me what command does'nt work? 
I tried this one `ng g component test` and it does work.

**Comment by vorthess** [comment]
>Actually you have to do npm start & npm run electron:serve in another terminal (README)

Yes this is fine

Also thanks for info how to add dev server.

About ng cli - it works, but you can't do `ng serve` after eject (it throws info to use webpack, which is fine).

Actually my problem is that after I pulled your repo, I updated it and moved my project there. And now Electron crashes each time webpack rebuilds.

I tried on clean repo and its fine, so the problem is with my repo, so I will revert dependencies and try if it works.

Actually can be closed, Im just facing problems with electron itself
