### ISSUE TITLE
get app

### ISSUE THREAD

**Issue by az114q** [maximegris/angular-electron#120]
```
var app = require('app');
app.on('window-all-closed', function() {
  app.quit();
});
```
I want to get this app.

I see in main.ts file used
`import { app, BrowserWindow, screen } from 'electron';`

but in my component, I used this code,it can't useful.

anyone can help?
 thank you.

**Comment by az114q** [comment]
My real goal is to implement automatic upgrades.

**Comment by ismaail** [comment]
try this:

```js
const { shell, remote } = window.require('electron');
const app = remote.app;

console.log(app.getPath("home"));
```
