### ISSUE TITLE
Question: How to add more i18n localizations?

### ISSUE THREAD

**Issue by joaomvfsantos** [maximegris/angular-electron#122]
I'm struggling to add another localization file. I added a `de.json` in the `assets/i18n` folder, and per angular [documentation](https://angular.io/guide/i18n)  added the necessary provider registration, namely the LOCALE_ID to use `de` instead of `en`. However it always loads the `en` file strings instead. Any lights on this?

Thank you a lot!

**Comment by maximegris** [comment]
Hi

Just replace `translate.setDefaultLang('en');` by `translate.setDefaultLang('de');` in `app.component.ts`

**Comment by andersonmadeira** [comment]
Just to clarify things: translate is a method of TranslateService. So, to use that, you need to inject that service.
