### ISSUE TITLE
UI Components + Theming in Angular-Electron

### ISSUE THREAD

**Issue by jpiwek** [maximegris/angular-electron#126]
Hi,
before I started with Angular-Electron, I have been working with Ionic. Ionic has nice UI components (sliders, tabs, range, lists,....), theming, icon set.... (https://ionicframework.com/docs/components/#overview).
Can those UI components be re-used? What Angular-Electron provides by default?

Best,
Piwi

**Comment by maximegris** [comment]
Hi

Angular Electron doesn't provide a components library like Ionic or Bootstrap by default.
The goal of this project is to stay as simple as possible. So Everyone can choose is own components library.
