### ISSUE TITLE
[feature request] native Typescript support

### ISSUE THREAD

**Issue by vorthess** [maximegris/angular-electron#13]
It would be nice to extend typescript build using same config as for angular, but for main.js (.ts) process, so both view and backend could be set in the same shared enviroment

**Comment by maximegris** [comment]
Hi,

Yes I agree. 

I have just converted electron `main.js` file into `main.ts`. 
I had to adapt `npm scripts` to make it work. Everthing seems ok. (electron dev & package, browser mode & e2e tests)

This feature is include in tag 1.4.0.
