### ISSUE TITLE
Comment porter une application Angular vers angular-electron

### ISSUE THREAD

**Issue by hervehobbes** [maximegris/angular-electron#130]
Bonjour Maxime,

J'ai une application, classique, développée avec Angular 5.2 et dont le squelette a été générée via la ligne de commande par un classique "ng new monprojet", maintenant j'aimerais en faire une version desktop en utilisant Electron et votre projet.

J'ai cru que ça allait être simple mais il y a pas mal de différences entre la structure de votre projet et celle d'Angular. J'ai tenté une fusion avec WinMerge mais rien ne marche...

Auriez-vous des recommandations à me faire pour passer d'Angular à votre projet ?
Ou une méthodologie à suivre ?

merci,
Hervé

**Comment by cjackson234** [comment]
What issues are you running into? Webpack?

The angular code itself shouldn't be hard to port over.

**Comment by hervehobbes** [comment]
Maxime,

Your dependencies are more up to date than mine.
I will first update mine and come back if I still have problems.

**Comment by hervehobbes** [comment]
Maxime,

After updating my dependencies everything went well.
I had problems with @angular/flex-layout

Thank you for your help
