### ISSUE TITLE
Question: How do I run this in 32 bit?

### ISSUE THREAD

**Issue by jakehockey10** [maximegris/angular-electron#131]
Hello,

I have a strong feeling this is a silly question, but I've been searching and searching and I don't understand how to run this in 32 bit mode?  I'm integrating the `electron-edge-js` library into this, and the DLLs I'm calling into are 32 bit mode.  Is this something that I would need to do to `electron-builder`?  Is there something I can add to the package.json scripts?

Any and all help is appreciated, thanks!

**Comment by cjackson234** [comment]
https://github.com/electron-userland/electron-builder/issues/1897
