### ISSUE TITLE
Unneeded hooks/src directory

### ISSUE THREAD

**Issue by superdyzio** [maximegris/angular-electron#139]
During tslint setup I've noticed that `hooks/src` directory is unnecessary, it is not used anywhere and `app.config.ts` file in it raises tslint errors. 

That line: 
`fs.copySync(path.resolve(__dirname, './app.config.ts.tpl'), path.resolve(__dirname, '../src/app/app.config.ts'));`
in `set_profile.js` should go like this:
`fs.copySync(path.resolve(__dirname, './app.config.ts.tpl'), path.resolve('src/app/app.config.ts'));`.

This way `app.config.ts.tpl` template file will go to the `src/app` directory in the repository root and not `hooks/src/app`.

Am I right or am I missing something?

BTW awesome lib, thanks!

**Comment by superdyzio** [comment]
It also looks like this `var profile = process.env.ENV ? process.env.ENV : 'local';` always returns `local` and 'prod' mode is hardcoded in `src/app/app.config.ts`.

**Comment by maximegris** [comment]
You may want to define and use different environment variables with your application. Like if you want to use a test or a production backend API for exemple.

The choice here was to define node ENV in combinaison with npm scripts. 
Depending on the value of ENV, the hook will replace the file `app.config.ts` in `src/app/`. So it match with the correct file in `src/environment`

Please follow README.

## Manage your environment variables

- Using local variables :  `npm start` or `cross-env ENV=local npm start`
- Using development variables :  `cross-env ENV=dev npm start`
- Using production variables  :  `cross-env ENV=rod npm start`
