### ISSUE TITLE
Using fs

### ISSUE THREAD

**Issue by dolanmiu** [maximegris/angular-electron#142]
`angular-electron` does not work with `fs`. Please help.

My Electron app needs to read from file system etc

![image](https://user-images.githubusercontent.com/2917613/37186090-857bb204-233b-11e8-8fdb-8735b72d900a.png)

**Comment by maximegris** [comment]
How do you import fs module ?

**Comment by dolanmiu** [comment]
import * as fs from 'fs'

**Comment by maximegris** [comment]
Please have a look at electron.service.ts .
It will solve your problem :)

**Comment by craigshoemaker** [comment]
@maximegris what about for dependencies that use `fs` internally? For instance, I am trying to use [walk](https://www.npmjs.com/package/walk) and I get the same error thrown in the context `walk`'s attempt to access the file system.

I see that in `electron.service.ts` you make `fs` available as a member of the service, but I can't figure out how to get dependencies to access `fs` out-of-the-box.

**Comment by soupman99** [comment]
yeah @maximegris how would we use a library that has FS etc as a dependency?
