### ISSUE TITLE
in main.ts => platformBrowserDynamic() 

### ISSUE THREAD

**Issue by ChrisZio** [maximegris/angular-electron#143]
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import 'hammerjs';

import { AppModule } from './app/app.module';
import { AppConfig } from './app/app.config';

if (AppConfig.production) {                 __// ( 1 ) Unresolved Variable production__
  enableProdMode();
}

platformBrowserDynamic()
  .bootstrapModule(AppModule, {
   preserveWhitespaces: false
            
__//  ( 2 ) Type mismatch Augmented Type { preserveWhitespaces: 
//  boolean is not assignable to Parameter Type( 
//  ComplierOptions & BootstrapOptions ) | < Array 
//  CompilerOptions & BootstrapOptions >__   

  })
  .catch(err => console.error(err));
////////////////// =============================================================
__Hi,
I am getting these two errors ( 1 and 2 ) straight from git clone boilerplate. 
would be so kind as to let me know why? and if it will have an effect on the production render.__

Thanking you for your time.
Regards 
Chris.

**Comment by maximegris** [comment]
What version of typescript and angular do you use ? They have to be compatible each other.

**Comment by maximegris** [comment]
No answer. I close the issue.
