### ISSUE TITLE
Native dependency in a third part module

### ISSUE THREAD

**Issue by jmpmscorp** [maximegris/angular-electron#147]
Hi and firstly, thank you for your work.

I'm working on a InterProcess Comunication electron app. This app must connect through unix sockets/windows pipes with another nodejs app running on device. For this purpose, I'm using a third part package called "node-ipc" that works fine for my requirements.

I have been cloned your repository and installed every npm dependency. App is working fine. Then I have installed "node-ipc" module and @types. This module uses "net" and "dgram" nodejs native modules. I have coded an angular service using this modules. When I start the app an error message is shown "Can't resolve module dgram at ../node_modules". I understand that net and dgram are not imported by webpack with @angular/cli.

I have been reading related issues and some point to a file "webpack.config.js" but I cannot find it.

Finally, I have found temporal solution modifying library and changing require('net') and require('dgram') by window.require('net') and window.require('dgram'). Now, app works, but my question is, is there any better approach or best way to solve it??

Thanks in advance.
Best regards.

**Comment by maximegris** [comment]
Hi

Have a look at electron.service.ts file. 
I use window.require to Access to bise package.
It works well. If someone knows another implementation, tout can submit a pull request :)

**Comment by jmpmscorp** [comment]
Thank you for your quick reply @maximegris.

As I saw where you point me, electron.service.ts, that's the reason I changed "node-ipc" module and used window.require(...) instead of require and now app is working. I don't find any other way.

You can close issue if you consider. 

Thank you again.
