### ISSUE TITLE
Opening page in new browser window using angular2 with mvc

### ISSUE THREAD

**Issue by neeraaj1502** [maximegris/angular-electron#148]
I am new in angular2 and having a requirement to upgrade the existing asp.net web form application in mvc using angular2.

My existing asp.net application flow is as follows

Login - > Dashboard  

Dashboard  -> it has multiple menus and every menu open a screen in new browser popup window  like menus are 

**Master Data**
  - Product Category
  - Product
  - Product Mapping

when user clicks on any given menus it opens a new browser popup window where user can enter data.
in asp.net web form application we use `window.open` java-script function by providing `.aspx ` page name and its different parameter to open a screen like this 

```
var params = `scrollbars=no,resizable=no,status=no,location=no,toolbar=no,menubar=no,
width=0,height=0,left=-1000,top=-1000`;
var winRef = window.open('ProductCategory.aspx', 'Product Category', params);
winRef.focus();


```
above code opens 'ProductCategory.aspx' page in new browser window same functionality impmented for other menus as well.

My first concern is about SPA application architecture that angular follows, if I am selecting it with my new application! then is it correct(compatible) with my existing application behaviour as my application basic requirement is multi window application where user will land on dashboard screen after login then from dashboard every link/menus will open a page(screen) in new browser window.  Here some of popup (child) screens communicate with parent(dashboard window) buy using `window.opener.[User defined function]`  approach to send data from child to parent.

If there is no compatibility issue with angular2/4 for my existing application flow, can some one post an example how do I implement the new browser popup window functionality in new implementation with angular2/4.

I tried a lot to get the sample code to open multiple browser window in angular2 with mvc application but i did not found complete solution that I can look for implementation. 

Please give me link if anyone know any sample code related with my sechenario.

**Comment by cjackson234** [comment]
So first of all, this isn't an issue related to this repo at all. What you're talking about is the basics of angular and electron.

If you need to open a new window, you can use [window.open](https://github.com/electron/electron/blob/master/docs/api/window-open.md) from the electron documentation. But this only gives you half of what you're looking for. What you need to do is pass params to the page once it opens. This can be done in angular using route parameters as explained [here](https://stackoverflow.com/questions/40275862/how-to-get-parameter-on-angular2-route-in-angular-way/40276279) .

But my question is why do you even want "popups"? I would highly recommend going with either modals or something similar. Adding visible breadcrumbs would probably solve any user navigation issues, and save you some code if you just go with standard pages.

**Comment by maximegris** [comment]
Thanks @cjackson234 for your answer. 
As said, this isn't an issue related to this repo :)
