### ISSUE TITLE
Impossible to use native modules

### ISSUE THREAD

**Issue by qlaffont** [maximegris/angular-electron#149]
Hi,
I am currently use your boilerplate to dev an application with youtube-dl library. But actually, I have an error with 'child_process' import. How i can solve it ?
`Module not found: Error: Can't resolve 'child_process' in 'PATH/angular-electron/node_modules/youtube-dl/lib'`
Regards
Quentin

**Comment by elovin** [comment]
It is possible, previously you had to add it to the webpack.config but the config is no longer exposed.
If you read the README carefully you will find this:

> Please check providers/electron.service.ts to watch how conditional import of electron/Native libraries is done.

Which is [this](https://github.com/maximegris/angular-electron/blob/master/src/app/providers/electron.service.ts) file.

How did you import it ?

**Comment by qlaffont** [comment]
The fact is I use youtube-dl library ([github link](https://github.com/przemyslawpluta/node-youtube-dl)) and when i use it it give me the error. The fact is youtube-dl need an access to native module. 

I have edit electron.service.ts to add this.child_process but not working. I think, I will give up and go back to react x). I love angular 4 but actually the simple thing to use native module is too difficult or impossible in this Framework.

**Comment by maximegris** [comment]
On Windows I add to replace youtube.exe in node_modules directory (see https://stackoverflow.com/questions/49770196/nodejs-youtube-spawn-unknown-error/49771147#49771147)

Then this sample of electron.service.ts works well 

```typescript 
import { Injectable } from '@angular/core';

// If you import a module but never use any of the imported values other than as TypeScript types,
// the resulting javascript file will look as if you never imported the module at all.
import { ipcRenderer, webFrame, remote } from 'electron';
import * as childProcess from 'child_process';
import * as fs from 'fs';
import * as youtubedl from 'youtube-dl';

@Injectable()
export class ElectronService {

  ipcRenderer: typeof ipcRenderer;
  webFrame: typeof webFrame;
  remote: typeof remote;
  childProcess: typeof childProcess;
  fs: typeof fs;
  youtubedl: typeof youtubedl;

  constructor() {
    // Conditional imports
    if (this.isElectron()) {
      this.ipcRenderer = window.require('electron').ipcRenderer;
      this.webFrame = window.require('electron').webFrame;
      this.remote = window.require('electron').remote;

      this.childProcess = window.require('child_process');
      this.fs = window.require('fs');

      this.youtubedl = window.require('youtube-dl');
      const video = this.youtubedl('http://www.youtube.com/watch?v=90AiXO1pAiA',
        // Optional arguments passed to youtube-dl.
        ['--format=18'],
        // Additional options can be given for calling `child_process.execFile()`.
        { cwd: __dirname });

      // Will be called when the download starts.
      video.on('info', function (info) {
        console.log('Download started');
        console.log('filename: ' + info.filename);
        console.log('size: ' + info.size);
      });

      video.pipe(this.fs.createWriteStream('myvideo.mp4'));
    }
  }

  isElectron = () => {
    return window && window.process && window.process.type;
  }

}

```

**Comment by stapleup** [comment]
Hi, I am facing the similar issue and no matter what I do, I can't make npm modules work in services, I am trying to sue the node-imap (https://github.com/mscdex/node-imap) module and when I include it in service like you did, it starts complaining about not being able to import node modules. net and stream modules are required by node-imap.

ERROR in ./node_modules/imap/lib/Connection.js
Module not found: Error: Can't resolve 'net' in '/Users/x/Desktop/GitRepos/x-Desktop/node_modules/imap/lib'
ERROR in ./node_modules/imap/lib/Parser.js
Module not found: Error: Can't resolve 'stream' in '/Users/x/Desktop/GitRepos/x-Desktop/node_modules/imap/lib'

Can you please explain how you got the youtube-dl to work?

Thanks

**Comment by maximegris** [comment]
Please have a look at the last version (4.1.0) [especially commits  165c50a1e964718cbde9881db230a134194438eb 1c403a80fad3be355ed99d924f4d8601a34aa117 50657d01265ec5c9dddc957e3d3e5288b1220753]
It should makes node modules (and other native libs) working and remove require errors.
