### ISSUE TITLE
Issue while building App with small Background Images

### ISSUE THREAD

**Issue by TomTomB** [maximegris/angular-electron#150]
To reproduce this issue simply change the background image inside home.component.scss into an image thats smaller than 256x256px.
Now try to build the project with `npm run electron:windows`.

This will fail with the following Error Message :   
`image C:\Users\username\angular-electron\dist\small-image.0488d9eb003af2735cd0.png must be at least 256x256`

Is there a way to fix this issue? 
It seems like a strange behavior between the Output generated by ng and the electron-builder who´s maybe trying to use those as App Icons.

**Comment by cjackson234** [comment]
https://github.com/electron-userland/electron-builder/issues/2462

**Comment by cjackson234** [comment]
Yeah, it looks like its an issue with electron builder.

**Comment by TomTomB** [comment]
Well, I have found a solution. 

Inside electron-builder.json under `win` and  `mac` and  `linux` change the `icon` to `"icon": "dist/icons",`
Now build the project with `npm run build:prod`.
Inside the `dist ` folder create a new folder called `icons`. 
Now simply cut all the icon files from the `dist` folder and past them into your `dist/icons` folder. 
Now run `npx electron-builder build --windows` ( or `--mac` / `--linux`) and everything works fine.

Hopefully there is a simpler solution to this issue.

**Comment by mo2menelzeiny** [comment]
@TomTomB it's the right way to do it, however you can optimize the manual copy and paste by using `.angular-cli.json` file in your root directory, simply keep your icons in your assets or a new build file you created and specify in the assets where do you want them to go after the Angular build process.

**Comment by TomTomB** [comment]
My Icon files are already inside an assets/img/icons Directory. After Building they are inside the /dist/assets/img/icons Directory and also in the root /dist Directory - But this Time renamed to filename.somerandomhash.png.

**Comment by astroame** [comment]
I have found a simpler solution to this error:

- download the latest version of electron-builder v22.1.0
- now run, ```npm run build:prod```
- once that is completed, inside the ```dist``` folder copy ```favicon.256x256.png``` and paste it in the same folder, repeat this step again to have two copies of the ```favicon.256x256.png``` image, then rename both copies to ```sort_asc.9326ad44ae4bebdedd14.png``` and ```sort_asc_disabled.d7dc10c78f23615d3285.png```  (This name should be same as the two sort_asc_ images in the ```dist``` folder) 

- Now run, ```npx electron-builder build --windows```
- DONE!! it should build successfully without error

**Comment by stephanebouget** [comment]
To prevent this, put your icons into an "**icons**" folder (into src), and update your angular.json into :
architect > build > options :
```
"assets": [
			"src/icons/favicon.ico",
			"src/icons/favicon.png",
			"src/icons/favicon.icns",
			"src/icons/favicon.256x256.png",
			"src/icons/favicon.512x512.png",
]
```
