### ISSUE TITLE
Some Feedback and guide to common issues on Windows Development

### ISSUE THREAD

**Issue by theCrius** [maximegris/angular-electron#172]
Hey, thank you for this repo, I got a couple of suggestion that you could add into your package.json and/or in the readme.md.

I followed the instruction in the readme but I found some issue that are easily to solved and just annoying to face for a first time install if you're forced to work on a **windows** machine. All these needs to be installed at user level instead of project level.

- npm-run-all
- wait-on
- tsc

To get them all in one go: `npm i -g npm-run-all wait-on typescript`.

Some cleanup, not necessary but good to do:

- `/hooks/environments/set_profile.js` have logs in french. Make it english ;)
- `hooks/src/app` have two files: `app.config.ts` and `appconfig.ts`. Something feel fishy there. It's maybe an experiment for the set_profile.js? the script seems to act on `/src/app/` so maybe it could be better to have `/src/app/app.config.ts` in the `.gitignore` and delete entirely the `/hooks/src/app/` folder if that's the case.

Otherwise, everything seems fine as a kickstart repo.

**Comment by maximegris** [comment]
Thanks for PRs! I close the issue :)
