### ISSUE TITLE
Reload - net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by michaelb-01** [maximegris/angular-electron#173]
I was hoping you could help me add hot reloading to my app. I've added electron-reload but when my electron app reloads I get an error:

net::ERR_FILE_NOT_FOUND

I've read that it might webpack messing with __dirname so I could fix it with a custom webpack config file but I don't want to eject my angular cli project, and it looks like you got around that?

**Comment by maximegris** [comment]
Electron-relad is already present on the project (file `main.ts`). You don't need to add it.
