### ISSUE TITLE
How to use Notifications?

### ISSUE THREAD

**Issue by michaelb-01** [maximegris/angular-electron#174]
I have an electron service which I essentially copied from your electron service and I tried adding Notifications in the same way, e.g:

```
import { Notification } from 'electron';

@Injectable()
export class ElectronService {
  notification: typeof Notification;

  constructor() {
    // Import from Electron API if we are in Electron
    if (this.isElectron()) {
      this.notification = window.require('Notification');
    }
  }

  isElectron = () => {
    return window && window.process && window.process.type;
  }
}
```

However in my electron app it says it can't find the module:

`Cannot find module 'Notification'`

Any idea?

**Comment by maximegris** [comment]
Replace `window.require('Notification').;` by `window.require('electron').remote.Notification;`

```typescript
import { Notification } from 'electron';

@Injectable()
export class ElectronService {
  notification: typeof Notification;

  constructor() {
    // Import from Electron API if we are in Electron
    if (this.isElectron()) {
      this.notification = window.require('electron').Notification;
    }
  }

  isElectron = () => {
    return window && window.process && window.process.type;
  }
}
```

**Comment by travis1234** [comment]
Sorry to bring up a dead issue but could possibly provide a basic example of how you would use/create a notification in a component?

Something like this?

```
test() {
  this.electronService.notification = new Notification('test message');
}
```

**Comment by saurabhabh** [comment]
I am not able to get the Notifications running. @travis1234  did you manage to ? 

>  let opt: NotificationConstructorOptions = {
>       title: "Hello",
>       body: "This is a Message"
>     }
>     let notify = new this.electronservice.notification(opt);
>     notify.show();
