### ISSUE TITLE
Cant create any Files

### ISSUE THREAD

**Issue by bennisen** [maximegris/angular-electron#176]
I have installed NeDB Module or a Database, but i have the Problem that i cant create the Database File. From NeDB i get no Erros. I read that it has something to do with webpacks!? What can i do?

update: i found out that my electron uses indexedDB to store the File in Browser. Is it possible to prevent that?

**Comment by maximegris** [comment]
Can you try to create the neDB database in `main.js` ?
It will force neDB to create a local file as database, not in the indexDB

**Comment by bennisen** [comment]
No i tried it. Maybe that is a Problem with NeDB?

**Comment by maximegris** [comment]
I don't know. You sould ask on NeDB repository they may give you an answer.
