### ISSUE TITLE
Require 3rd party npm packages in main.js

### ISSUE THREAD

**Issue by Clemens-B** [maximegris/angular-electron#18]
Requiring 3rd party modules in electron's main.js results in an error messages "Cannot find modle xy" after building for a plattform and starting the application. For example I require nedb in main.js
```Javascript
//Require nedb here to make sure we have a file instead of IndexDB
const Datastore = require('nedb'),
    db = new Datastore({ filename: path.join(app.getPath('userData'), './data.db'), autoload: true });
global.datastore = db;
```

To solve this I run `npm install` in the /dist folder. Maybe there is a better solution?

**Comment by maximegris** [comment]
Is the library "nedb" in dependencies of package.json ? (not dev dependencies)

**Comment by Clemens-B** [comment]
Yes, it is under the normal dependencies

**Comment by Clemens-B** [comment]
I followed the advice by maltep from here: https://github.com/electron-userland/electron-packager/issues/527#issuecomment-260422388

**Comment by maximegris** [comment]
Hi

Thanks for the workaround. 

I don't implement it because it's actually not the purpose of the repository.
Feel free to open a pull request with an automated solution (no manually command) if you find one.

I close this issue.
