### ISSUE TITLE
TypeORM and 3.x Builds.

### ISSUE THREAD

**Issue by cjackson234** [maximegris/angular-electron#181]
I was looking into updating to the latest version of this repo and I noticed you've done quite a bit of refactoring. It looks like you removed webpack in favor of the angular CLI build. So, I cloned the repo fresh and added back all my dependencies. 

Now, when I add TypeORM, any imports that are functions don't work. 

For instance: 

> import { Entity, PrimaryGeneratedColumn, Column } from "typeorm";
> 
> @Entity('UserInfo')
> export class UserInfoEntity {
> 
>     @PrimaryGeneratedColumn()
>     id: number;
> 
>     @Column({ nullable: true })
>     User: string;
> 
>     @Column({ nullable: true })
>     Pass: string;
> }
> 

None of these imports are working. So the entity gets ignored by TypeORM.

I see you have an "electron.service" that you are using to import native libraries. Do I have to expand this service to cover every single import I need to do from TypeORM?

Please note: I never run in web mode, so the conditional requires isn't needed for my app.

Any insight would be appreciated. Thanks!

**Comment by creadicted** [comment]
I just tried it out to use typeorm. Oddly the compiler options in the ts-config file a is ignored. What are the errors that you get?

**Comment by cjackson234** [comment]
I was able to get this working on both the Angular 4 and 5 branch. I did go back to a build prior to removing the ejected config in 5.
