### ISSUE TITLE
Electron Auto-reload on changes

### ISSUE THREAD

**Issue by creadicted** [maximegris/angular-electron#184]
So you describe a hot reload on the readme. Is the angular reload meant by that? this works fine, but is there a way to recompile electron easier without ending and restarting it with `npm start`? Or is there a watch mode i have not seen?

**Comment by tomaszchlebek** [comment]
I'm working some time, base on this repository and after node module update have same issue, live reload is not working. App crashed, chromium is not visible. I can't find solution. Maybe someone know where is the problem ?

**Comment by nikolajosipovic** [comment]
I think this is meant for Angular.

**Comment by Kaffiend** [comment]
There are a couple options, the watchmode for electron i'm not familiar with but you can use a lib like nodemon manage the electron process in development. Tell it to watch the electron files and give it an execute of `tsc ./path/to/electron/main` and it will kill the main process, compile and run again. the other is with a task runner that has watching, like gulp etc. you can make it watch and kill the process and fire off the build and run again. Does this answer your question?

**Comment by Kaffiend** [comment]
install nodemon globally, or as a dev dep either will work.
```
npm i -g nodemon
```
then just change [this](https://github.com/maximegris/angular-electron/blob/master/package.json#L31) line in package.json to this.
```
"electron:serve": "wait-on http-get://localhost:4200/ && npm run electron:tsc && nodemon --watch ./main.ts --exec \"npm run electron:tsc && electron . \"",
```
This will watch the main.ts electron process file. when you save changes nodemon will run the -exec override and recompile the electron main process code and restart it.

**Comment by maximegris** [comment]
RThans for your answer @Kaffiend :)

**Comment by brucebrit** [comment]
> install nodemon globally, or as a dev dep either will work.
> 
> ```
> npm i -g nodemon
> ```
> 
> then just change [this](https://github.com/maximegris/angular-electron/blob/master/package.json#L31) line in package.json to this.
> 
> ```
> "electron:serve": "wait-on http-get://localhost:4200/ && npm run electron:tsc && nodemon --watch ./main.ts --exec \"npm run electron:tsc && electron . \"",
> ```
> 
> This will watch the main.ts electron process file. when you save changes nodemon will run the -exec override and recompile the electron main process code and restart it.

Hi, I try this. When i made changes to main.ts, i see the word "nodemon ...", but the electron GUI is still running.  Via GUI, i verify that the main.ts changes has not take effect yet.
But when I manually close the GUI, then after a very short while, the GUI will automatically startup again, and I verify that the changes to main.ts has take effect.

I was expecting the GUI to manually close, and restart by itself, the moment i make changes to main.ts, without me having to manually close the GUI. but it does not behave as i expect
