### ISSUE TITLE
Using zerorpc

### ISSUE THREAD

**Issue by yoav-shaham** [maximegris/angular-electron#192]
When adding zerorpc to the electron service provider it raises the error:
`Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)`
but when I add a script to the index html that uses zerorpc it works but I need to connect the zerorpc to my angular. I really appreciate any insight to either connecting the script to the angular or adding a loader for node type files to the angular/cli and to why using zerorpc works in the index.html but not in the services.

P.S.  
I'm probably using the issues feature wrong sorry I'm new to coding and I'm lost.

**Comment by maximegris** [comment]
I close the issue (inactive).
