### ISSUE TITLE
Not bundling assets

### ISSUE THREAD

**Issue by ronnyek** [maximegris/angular-electron#193]
Greetings... I was able to eject my clone of this project and tweak the build scripts to call webpack instead of ng build, and when building dist folder, all the assets are where I'd expect them to be, but when I go to publish an executable in windows with `npm run electron:windows`, images dont show up. I'm able to look at the app-builds unpacked folder and see that assets is indeed missing.

I don't quite understand enough how/where the electron packaging is happening or how it knows to pull files from dist, and if there are filters being applied.

**Comment by ronnyek** [comment]
This was because of not referencing images with the leading ./ vs assets.

**Comment by akatrukhin** [comment]
Add ` <base href="./">` to the index.html
