### ISSUE TITLE
Not allowed to load local

### ISSUE THREAD

**Issue by jpiwek** [maximegris/angular-electron#194]
Hi,

I packaged my electron app for win32. After starting I get this error message: I am using Angular-Electron v3.1.0
![grafik](https://user-images.githubusercontent.com/32235471/40678480-ee876d1c-6380-11e8-85d2-d1951111921b.png)

**Comment by mosapride** [comment]
please try it

main.ts

```typescript
  win = new BrowserWindow({
    x: 0,
    y: 0,
    width: size.width,
    height: size.height,
    webPreferences : {         // add
      webSecurity : false      // add
    }                          // add
  });
```

**Comment by Robbyn666** [comment]
@JiaLiPassion 

Add in your package.json this:

"build": {
    "directories": {
      "output": "release/"
    },


it works by changing the output folder.
