### ISSUE TITLE
Module not found: Error: Can't resolve 'crypto' in '....

### ISSUE THREAD

**Issue by cujslive** [maximegris/angular-electron#195]
Im trying to run ` npm run electron:local ` right after ` npm install `.
It is showing these warnings. But application is successfully launched.

```
WARNING in ./node_modules/zone.js/dist/zone-mix.js
Module not found: Error: Can't resolve 'crypto' in '/home/chandu/Developer/saira-kiosk/node_modules/zone.js/dist'

WARNING in ./node_modules/zone.js/dist/zone-mix.js
Module not found: Error: Can't resolve 'fs' in '/home/chandu/Developer/saira-kiosk/node_modules/zone.js/dist'

WARNING in ./node_modules/zone.js/dist/zone-mix.js
Module not found: Error: Can't resolve 'timers' in '/home/chandu/Developer/saira-kiosk/node_modules/zone.js/dist'
```

**NOTE:** No files are changed since the cloning.

**Comment by fott1** [comment]
I tried `npm install timers` and the warning about timers, is gone. I don't have a clue about the rest though.

**Comment by cujslive** [comment]
yeh. i've also tried ```npm install timers crypto fs```. but only the warning about the timers is gone.

**Comment by jeanRandria** [comment]
I have also these warnings and with `npm install timers` the warning about timers is gone not the rest!!!

**Comment by maximegris** [comment]
Please have a look at the last version (4.1.0) [especially commits  165c50a1e964718cbde9881db230a134194438eb 1c403a80fad3be355ed99d924f4d8601a34aa117 50657d01265ec5c9dddc957e3d3e5288b1220753]
It should makes node modules (and other native libs) working and remove require errors.

**Comment by liuhongbo** [comment]
i just clone master branch, and did npm run ng:serve:web,  those 3 warnings are still there
did i miss something?

**Comment by theCrius** [comment]
I've updated from the version using angular 5.x, to using angular 7.x

Our configuration here is basically having the electron part interfacing with a custom hardware connected to the computer, and loading a remote angular website (hence the updating only angular 5 to 7)

I'd really like some guidance on this issue as this was the first electron app I created and I don't really know where to look.

**Comment by corner100** [comment]
After running `ng update @angular/cli @angular/core` two warnings disappeared.
Just this one left: 

> WARNING in ./node_modules/zone.js/dist/zone-mix.js
Module not found: Error: Can't resolve 'fs' in '/home/user/Projects/AngularElectron/node_modules/zone.js/dist'
