### ISSUE TITLE
Using async breaks the build

### ISSUE THREAD

**Issue by Shawson** [maximegris/angular-electron#197]
I'm trying to use async in my main.ts file for perform a sql call in response to an ipc- however when i run npm start i receive the error;

`main.ts(46,35): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.`

Google suggests I add lib ["es2015"] to the tsconfig.json, but I notice the lib seciton already includes this;

`    "lib": [
      "es2017",
      "es2016",
      "es2015",
      "dom"
    ]`

Is there something wrong here, or am I missing something?

**Comment by leo6104** [comment]
@Shawson Can you try to change this line https://github.com/maximegris/angular-electron/blob/master/package.json#L27 ?
```
    "electron:tsc": "tsc main.ts --allowJs --lib es5,dom,es2016,es2015",
```
