### ISSUE TITLE
not opening the application.

### ISSUE THREAD

**Issue by ndhanorkar** [maximegris/angular-electron#199]
I have created linux build and all the files are same created as demo run.
but when I double click to open the executable file in linux ubuntu, nothing gonna happen. 
No errors there. 
if I run "npm start" everything work fine.

Some logs:
====
akib@akib-ThinkPad-X220 angular-electron (master) $ npm run electron:linux

> angular-electron@4.0.0 electron:linux /home/akib/Michael/project2/angular-electron
> npm run build:prod && npx electron-builder build --linux

> angular-electron@4.0.0 build:prod /home/akib/Michael/project2/angular-electron
> npm run build -- -c production

> angular-electron@4.0.0 build /home/akib/Michael/project2/angular-electron
> npm run electron:tsc && ng build "-c" "production"

> angular-electron@4.0.0 electron:tsc /home/akib/Michael/project2/angular-electron
> tsc main.ts

                                                                                        
Date: 2018-06-18T11:58:07.052Z
Hash: 2294882aa28816dc10c2
Time: 5457ms
chunk {0} runtime.a66f828dca56eeb90e02.js (runtime) 1.05 kB [entry] [rendered]
chunk {1} styles.34c57ab7888ec1573f9c.css (styles) 0 bytes [initial] [rendered]
chunk {2} polyfills.b4daf421c94934f530d4.js (polyfills) 59.6 kB [initial] [rendered]
chunk {3} main.1f2799828b9bf487b95e.js (main) 262 kB [initial] [rendered]
  • electron-builder version=20.14.7
  • loaded configuration file=/home/akib/Michael/project2/angular-electron/electron-builder.json
  • writing effective config file=app-builds-2/electron-builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=linux arch=x64 electron=2.0.2 appOutDir=app-builds-2/linux-unpacked
  • building        target=AppImage arch=x64 file=app-builds-2/angular-electron-4.0.0-x86_64.AppImage
  • application Linux category is set to default "Utility" reason=linux.category is not set and cannot map from macOS docs=https://electron.build/configuration/configuration#LinuxBuildOptions-category

**Comment by nikolajosipovic** [comment]
Hi, does the app start? If yes, try opening dev tools and see if there are errors in the console.

**Comment by maximegris** [comment]
I close the issue due to inactivity
