### ISSUE TITLE
ERROR: electron:mac

### ISSUE THREAD

**Issue by gozeon** [maximegris/angular-electron#203]
￼STOPING
![image](https://user-images.githubusercontent.com/17582116/42011893-319e0422-7ac8-11e8-8fe5-fa01d76688b5.png)

**Comment by hervehobbes** [comment]
Do you have more information about your problem, more details ?

**Comment by gozeon** [comment]
@hervehobbes Hi.
No more information. This is the case after running `npm run electron:mac` and it has been more than one day.
