### ISSUE TITLE
Electron Security Warning (Node.js Integration with Remote Content)

### ISSUE THREAD

**Issue by netlander** [maximegris/angular-electron#213]
Any idea how to suppress this message in the console? It's showing up on a fresh install and due to the non conventional structure of the project I am not able to google for a solution.

**Comment by Kaffiend** [comment]
The "consider loading over https" is really moot point. This is only happening during development when the cli server has a proxy in the electron window to the url, prod build renders from the filesystem.

**Comment by mauris** [comment]
To disable the warnings, in the file `main.ts` of the root directory, add the line:

    process.env.ELECTRON_DISABLE_SECURITY_WARNINGS = '1';

See:

- https://stackoverflow.com/questions/48854265/why-do-i-see-an-electron-security-warning-after-updating-my-electron-project-t
- https://github.com/electron/electron/issues/11970
