### ISSUE TITLE
Step by step instructions to make Angular 6 app an Electron app.

### ISSUE THREAD

**Issue by alan-kharebov** [maximegris/angular-electron#215]
Hi Maxime,

There are instruction steps how to make from Angular2+ app an Electron app, but they all working with pakage.json. 
Angular 6 is using angular.json. 

Your example code is working with Angular 6, but there is no clear picture how to do it with existing Angular 6 app.

Can you provide minimal step converting base angular app (app created by ng new) to become Electron app.

Thank you,
Alan

**Comment by isurendrasingh** [comment]
Just copy and paste your `src/app/` folder in this projects `components/` folder and add all Routing, Modules, Components in the `app.module` and `app.routing` and if you are using lazy loading the configure it accordingly.

**Comment by maximegris** [comment]
Thanks 4 the answer @isurendrasingh !
