### ISSUE TITLE
How to open URLs in default OS browser?

### ISSUE THREAD

**Issue by vyruz1986** [maximegris/angular-electron#218]
I've searched here but not found a solution.
Is there an easy way to have hyperlink's/URL's (`<a href="http://www.example.com">hyperlink</a>`) open in the default OS browser? When passing the `target="_blank"` parameter in the anchor element, Electron seems to open a new window, but this is lacking functionality for external websites.

**Comment by hervehobbes** [comment]
Have a look to this page: https://github.com/electron/electron/issues/1344
