### ISSUE TITLE
Cannot find AsyncIterator and AsyncIterable

### ISSUE THREAD

**Issue by imad-abdou** [maximegris/angular-electron#219]
please help i want get started using this starter so i did clone and npm install and then
npm run electron:local or npm run electron:windows give the following error always

sys info
windows 10
npm v5.6.0
node v8.11.3

Error:
../../../node_modules/@types/graphql/subscription/subscribe.d.ts(17,4): error TS2304: Cannot find name 'AsyncIterator'.
../../../node_modules/@types/graphql/subscription/subscribe.d.ts(29,4): error TS2304: Cannot find name 'AsyncIterable'.

**Comment by hervehobbes** [comment]
Try to update Node.

**Comment by hervehobbes** [comment]
Or see this [link](https://github.com/apollographql/graphql-subscriptions/issues/83)
