### ISSUE TITLE
tsconfig.app.json exclude path needs some adjustments

### ISSUE THREAD

**Issue by lacroixdavid1** [maximegris/angular-electron#220]
If for example, I have a not compiling typescript file in `src/core/broken`, I have to set `tsconfig.app.json` exclude the path to `core/broken`, without the `src` prefix otherwise it compiles it anyway. That means the `exclude` array needs some adjustments.

You should adjust your exclude path to 
```
  "exclude": [
    "**/*.spec.ts",
  ]
```

instead of actual 
```
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts",
    "dist",
    "app-builds",
    "node_modules"
  ]
```

This still build as fast and produces the same output file size.

**Comment by maximegris** [comment]
Hi,

Thanks for the tips :) 
I'll integrate this change in the next release.
