### ISSUE TITLE
Canvas packages fails with error: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by Mihail12** [maximegris/angular-electron#223]
After adding to main.ts:

const Canvas = require('canvas')

and building the project
have the issue:
![image](https://user-images.githubusercontent.com/25564790/43534638-8e7320b6-95c0-11e8-849d-ef19f725e7b7.png)

windows 10

**Comment by hervehobbes** [comment]
Your DLL is missing a dependancy or its compilation failed.
Open the DLL with "Dependency Walker" and see what is missing.
This is not related to Angular or Electron or this project.

**Comment by Mihail12** [comment]
@hervehobbes Thanks, but could tou please tell me, after I found out what DLL is missing how and where could I found them ?

**Comment by hervehobbes** [comment]
The best place is the projetc's homepage (canvas)

**Comment by Mihail12** [comment]
@hervehobbes so as I understand here all DLL the canvas packages is missed ?
![image](https://user-images.githubusercontent.com/25564790/43536089-63f09a7c-95c4-11e8-8321-cee1e9f03270.png)

**Comment by zakariakhorf** [comment]
Hey @Mihail12 can you please tell me how you solved this issue ?
