### ISSUE TITLE
Possibility to work totally offline

### ISSUE THREAD

**Issue by Leonardonline** [maximegris/angular-electron#224]
Imagining working on an offline machine, it would be possible to provide an option that uses only local files? 
I'm talking about cache files of electron and maybe others.

**Comment by hervehobbes** [comment]
Copy assets in local and call them localy

**Comment by Leonardonline** [comment]
I can confirm that after a first run online, the same command works offline.

Sorry for the useless issue, but I was remembering that every compiling of Electron requiring the file to download.

**Comment by Leonardonline** [comment]
I have reopen this issue because I tried today and it's not working.
Maybe it's relative to [this](https://github.com/electron-userland/electron-builder/issues/3208) issue.
Any suggestions?

**Comment by maximegris** [comment]
I close the issue (inactive & not relative to this repo).
