### ISSUE TITLE
Rendering Issues on Scroll

### ISSUE THREAD

**Issue by guyms** [maximegris/angular-electron#225]
![screen shot 2018-08-08 at 21 55 05](https://user-images.githubusercontent.com/8017509/43878804-da13fe06-9b55-11e8-9711-6146af992796.png)
Hello, this is a standard clone of repository, although I removed the background image.
Added a button and a secondary example container. As you can see that there are some rendering/refreshing issues while scrolling?
Has anyone else experienced this?

**Comment by guyms** [comment]
It was an issue with electron v2.0.4, upgraded to 3.0.0b4 and it works. This was only an issue on Mac OS.

**Comment by maximegris** [comment]
Thanks for the feedback !
