### ISSUE TITLE
Feature request for ExpressJS integration

### ISSUE THREAD

**Issue by isurendrasingh** [maximegris/angular-electron#226]
I'm using this project for months & let me tell you, you did a great job. It will be very much easy for developers id you integrate ExpressJS server with Electron & Angular. It is like a mess setting up ExpressJS server in this package. So if it is possible for you please provide a method or directly integrate the ExpressJS server.

**Comment by maximegris** [comment]
Hi,

Simply add this at the end of `main.ts` (the file is at the root of this repo)

```typescript

const express = require('express');
const appExpress = express();

appExpress.get('/', function (req, res) {
  res.send('Hello World!');
});

appExpress.listen(3000, function () {
  console.log('Example app listening on port 3000!');
});
```

Then launch the app and you should query your Express server on http://localhost:3000

**Comment by isurendrasingh** [comment]
Can't even try this coz after i cloned the updated package i'm getting this error.
![screenshot 39](https://user-images.githubusercontent.com/7621607/44357186-02629200-a4cf-11e8-9d7f-acc7078287d2.png)

**Comment by isurendrasingh** [comment]
Thanks!! It works.

**Comment by Suroor-Ahmmad** [comment]
This works great, how can I add nodemon for hot-reload?
