### ISSUE TITLE
Module not found warnings: crypto, fs and timers

### ISSUE THREAD

**Issue by mburakkalkan** [maximegris/angular-electron#227]
When start by `npm run ng:serve:web` these warnings shown up in terminal:
```
WARNING in ./node_modules/zone.js/dist/zone-mix.js
Module not found: Error: Can't resolve 'crypto' in 'd:\Projeler\angular-electron\node_modules\zone.js\dist'

WARNING in ./node_modules/zone.js/dist/zone-mix.js
Module not found: Error: Can't resolve 'fs' in 'd:\Projeler\angular-electron\node_modules\zone.js\dist'

WARNING in ./node_modules/zone.js/dist/zone-mix.js
Module not found: Error: Can't resolve 'timers' in 'd:\Projeler\angular-electron\node_modules\zone.js\dist'
```
and `Uncaught ReferenceError: process is not defined` error in the browser.

**To solve:**

In the `node_modules\@angular-devkit\build-angular\src\angular-cli-files\models\webpack-config\browser.js ` change `node: false` to `node: {crypto: true, fs: 'empty'}`

**Comment by maximegris** [comment]
Hi

The problem should not persist with the last version. 
Some hooks were added on `node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js` file to manage both electron and web mode.
