### ISSUE TITLE
Provide basic instructions to use Electron Service

### ISSUE THREAD

**Issue by isurendrasingh** [maximegris/angular-electron#229]
I'm using this recently and i have to create a new window from button in `home.component.html` and `openWindow()` in  `home.component.ts`. The `BrowserWindow `is necessary as well as `remote `to create a new window but `BrowserWindow `is not present in `ElectronService`. Then i searched Stackoverflow and other forums but nothing is there. So it's a request to provide basic instructions to use the `electronservice`. Also how to create a new window using electron service?

**Comment by maximegris** [comment]
I close the issue (inactive). I'll try to add a charter about how using Electron Service.
