### ISSUE TITLE
Random crash when hot reloading

### ISSUE THREAD

**Issue by coddo** [maximegris/angular-electron#23]
I tried multiple times to change files and see the results with hot reloading, but it randomly crashes after a few changes, or sometimes even at the first change.

I get the following errors in cmd: 

> npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "electron:serve"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-electron@1.3.5 electron:serve: `electron . --serve`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the angular-electron@1.3.5 electron:serve script 'electron . --serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron . --serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-electron
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Coddo\Desktop\Angular4Tutorial\angular-electron\npm-debug.log

The npm-debug.log file contains the following: https://pastebin.com/z7RLt6tw

And I'm not sure if this helps or what actually it is implying, but I get `Electron could not be found. No hard resets for you!` each time I run `npm run electron:serve`.

I have 2 consoles and I've run the app as described in the readme file:
- cmd1: npm start
- cmd2: npm run electron:serve

The crash occurs in cmd2

**Comment by coelhoadler** [comment]
I have the same problem but when I modify someone file, it isn't reload my bundle (js).

**Comment by coelhoadler** [comment]
@coddo try to use only relative paths. Ex: **./src/app/...**

**Comment by coddo** [comment]
@coelhoad

**Comment by coddo** [comment]
@coelhoadler I haven't added anything extra to the template. I just cloned and started fidling with the existing stuff. There are no absolute paths used anywhere and I would never think of using absolute paths in the first place.

**Comment by katherdx** [comment]
@coddo  did you found any solution?
me too getting same issue.

**Comment by Gulivertx** [comment]
I had the same, I updated electron to the last and problem solve, in the same time I also updated Angular to last version 4.2.6
Here is my modified package.json
`
{
  "name": "angular-electron",
  "version": "1.5.0",
  "description": "Angular 4 with Electron (Typescript + SASS + Hot Reload)",
  "homepage": "https://github.com/maximegris/angular-electron",
  "author": {
    "name": "Maxime GRIS",
    "email": "maxime.gris@gmail.com"
  },
  "keywords": [
    "angular",
    "electron",
    "typescript",
    "sass"
  ],
  "main": "main.js",
  "private": true,
  "scripts": {
    "ng": "ng",
    "lint": "ng lint",
    "start": "webpack --watch",
    "start:web": "webpack-dev-server --content-base . --port 4200 --inline",
    "build:electron:main": "tsc main.ts --outDir dist && copyfiles package.json dist && cd dist && npm install --prod && cd ..",
    "build": "webpack --display-error-details && npm run build:electron:main",
    "build:prod": "cross-env NODE_ENV=production npm run build",
    "electron:serve": "npm run build:electron:main && electron ./dist --serve",
    "electron:test": "electron ./dist",
    "electron:dev": "npm run build && electron ./dist",
    "electron:prod": "npm run build:prod && electron ./dist",
    "electron:linux": "npm run build:prod && node package.js --asar --platform=linux --arch=x64",
    "electron:windows": "npm run build:prod && node package.js --asar --platform=win32 --arch=ia32",
    "electron:mac": "npm run build:prod && node package.js --asar --platform=darwin --arch=x64",
    "test": "karma start ./karma.conf.js",
    "pree2e": "webdriver-manager update --standalone false --gecko false --quiet && npm run build",
    "e2e": "protractor ./protractor.conf.js"
  },
  "dependencies": {
    "@angular/animations": "4.2.6",
    "@angular/common": "^4.2.6",
    "@angular/compiler": "^4.2.6",
    "@angular/core": "^4.2.6",
    "@angular/forms": "^4.2.6",
    "@angular/http": "^4.2.6",
    "@angular/platform-browser": "^4.2.6",
    "@angular/platform-browser-dynamic": "^4.2.6",
    "@angular/router": "^4.2.6",
    "core-js": "2.4.1",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "moment": "^2.18.1",
    "normalize-scss": "^7.0.0",
    "rxjs": "5.4.0",
    "weather-icons": "^1.3.2",
    "zone.js": "0.8.11"
  },
  "devDependencies": {
    "@angular/cli": "^1.2.0",
    "@angular/compiler-cli": "^4.2.6",
    "@ngtools/webpack": "^1.5.0",
    "@types/jasmine": "2.5.41",
    "@types/node": "7.0.18",
    "autoprefixer": "6.7.7",
    "codelyzer": "3.0.1",
    "copyfiles": "1.2.0",
    "cross-env": "4.0.0",
    "css-loader": "0.26.1",
    "cssnano": "3.10.0",
    "electron": "^1.7.4",
    "electron-packager": "8.6.0",
    "electron-reload": "1.2.0",
    "exports-loader": "0.6.4",
    "extract-zip": "=1.6.0",
    "file-loader": "0.11.1",
    "html-loader": "0.4.5",
    "istanbul-instrumenter-loader": "2.0.0",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "3.2.0",
    "json-loader": "0.5.4",
    "karma": "1.4.1",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "0.2.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "karma-sourcemap-loader": "0.3.7",
    "less-loader": "2.2.3",
    "minimist": "1.2.0",
    "mkdirp": "0.5.1",
    "postcss-loader": "1.3.3",
    "postcss-url": "6.0.4",
    "protractor": "5.1.1",
    "raw-loader": "0.5.1",
    "sass-loader": "6.0.3",
    "script-loader": "0.7.0",
    "source-map-loader": "0.2.1",
    "style-loader": "0.16.1",
    "stylus-loader": "3.0.1",
    "ts-node": "3.0.2",
    "tslint": "5.1.0",
    "typescript": "2.3.3",
    "url-loader": "0.5.8",
    "webdriver-manager": "12.0.4",
    "webpack": "2.4.1",
    "webpack-dev-server": "2.4.5"
  },
  "license": "SEE LICENSE IN LICENSE.md"
}

`

**Comment by coddo** [comment]
@katherdx I didn't have time to play around with the project since then. Seems a solution was posted right under your comment.

@Gulivertx Sounds great. I'll give it a try during the weekend

**Comment by caiusCitiriga** [comment]
any news on this?

**Comment by Snow-Okami** [comment]
I tried updating like @Gulivertx suggested but only experienced more instability than normal. Had to go back. Mainly in electron's beta. My angular is already up to date. Also I'm not sure what the "@ngtools/webpack": "^1.5.0" is, as I have the regular webpack in my installation.

**Comment by caiusCitiriga** [comment]
If you're on mac/linux maybe this can help.
Put it into your bash_profile and run <code>serveEl</code> instead of <code>npm run electron:serve</code>

<code>
function serveEl(){
    while True;
    do
        npm run electron:serve || echo "Server crashed... restarting..." >&2
        echo "Press Ctrl-C to quit." && sleep 1
    done
}
</code>

I know it's a work around but at least it serves again the application automatically.

**Comment by celestale** [comment]
having the same issue, all workaround above doesn't help. random crashes after edits.

**Comment by ralph-hm** [comment]
Same issue here.

**Comment by shaljain** [comment]
Re: the message - **Electron could not be found.  No hard resets for you!** when running npm serve, I fixed it by modifying the following in main.ts
`if (serve) {
  require('electron-reload')(__dirname, {
    **electron: require(`../node_modules/electron`)**
  });
}`

**Comment by coddo** [comment]
@shaljain I guess you can make a PR with the fix to help all of us :)

**Comment by shaljain** [comment]
@coddo  Just created one.
