### ISSUE TITLE
webcontents.print() not working in new window

### ISSUE THREAD

**Issue by isurendrasingh** [maximegris/angular-electron#230]
I have a new window which runs new angular route. In that HTML there is a pdf & a button. When i clicked the button to print it gives error `undefined`

**Typescript Code:**
```
@ViewChild('pdfContainer') pdfContainer: ElementRef;
print() {
    const content = this.pdfContainer.nativeElement;
    content.webContents.print({silent: false, printBackground: true});
  }
```

**HTML Code:**

```
<pdf-viewer [src]="pdf"
            style="display: block;"
id="pdfContainer" #pdfContainer></pdf-viewer>
<p>
  <button  (click)="print()">Print</button>
</p>

```
The pdf is rendering fine but the print is undefined.
The error is: `ERROR TypeError: Cannot read property 'webContents' of undefined` & if i changed  ` content.webContents.print({silent: false, printBackground: true});` to  `content.print({silent: false, printBackground: true});` it is still not working.

**Comment by maximegris** [comment]
I close the issue (inactive, no answer).
