### ISSUE TITLE
npm run electron:mac generate build but not working properly

### ISSUE THREAD

**Issue by 7867praveen** [maximegris/angular-electron#232]
Hi,

I am using this repo to create a desktop app for Mac. I run the command "npm run electron:mac" and it generates the build but that build is not working properly. In dev mode its working fine without any error. 
I will be thankful if you can help me here.

**Comment by 7867praveen** [comment]
Poojas-MacBook-Pro:angular-electron-master poojatiwari$ npm run electron:mac

> angular-electron@4.2.2 electron:mac /Users/poojatiwari/Documents/angular-electron-master
> npm run build:prod && npx electron-builder build --mac


> angular-electron@4.2.2 build:prod /Users/poojatiwari/Documents/angular-electron-master
> npm run build -- -c production


> angular-electron@4.2.2 build /Users/poojatiwari/Documents/angular-electron-master
> npm run postinstall:electron && npm run electron:serve-tsc && ng build "-c" "production"


> angular-electron@4.2.2 postinstall:electron /Users/poojatiwari/Documents/angular-electron-master
> node postinstall


> angular-electron@4.2.2 electron:serve-tsc /Users/poojatiwari/Documents/angular-electron-master
> tsc -p tsconfig-serve.json


Date: 2018-08-26T05:22:22.172Z
Hash: ecbd7c6587b6d7b6aea3
Time: 101797ms
chunk {0} runtime.b21b7998b455f90aab45.js (runtime) 1.05 kB [entry] [rendered]
chunk {1} styles.affa06a78f98c560ad92.css (styles) 3.63 kB [initial] [rendered]
chunk {2} polyfills.5de5932412a77d65926f.js (polyfills) 62.8 kB [initial] [rendered]
chunk {3} main.c3e331a6b22572986071.js (main) 1.38 MB [initial] [rendered]
  • electron-builder version=20.28.1
  • loaded configuration file=/Users/poojatiwari/Documents/angular-electron-master/electron-builder.json
  • writing effective config file=release/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=darwin arch=x64 electron=2.0.7 appOutDir=release/mac
  • downloading               parts=8 size=49 MB url=https://github.com/electron/electron/releases/download/v2.0.7/electron-v2.0.7-darwin-x64.zip
  • downloaded                duration=2m25.411s url=https://github.com/electron/electron/releases/download/v2.0.7/electron-v2.0.7-darwin-x64.zip
  • skipped macOS application code signing reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=
                                               1) EC0E59422E9A37C5EE8F9BB004713496C082B052 "com.apple.idms.appleid.prd.6b744b4b46473662324d46674c795a68467a666e7a513d3d" (CSSMERR_TP_CERT_EXPIRED)
                                               2) 8F14280774DC95CACA3EA88776E5587675AA9BF8 "com.apple.idms.appleid.prd.6b744b4b46473662324d46674c795a68467a666e7a513d3d" (CSSMERR_TP_CERT_EXPIRED)
                                                  2 identities found

                                               Valid identities only
                                                  0 valid identities found
  • building        target=DMG arch=x64 file=release/angular-electron-4.2.2.dmg
  • building block map blockMapFile=release/angular-electron-4.2.2.dmg.blockmap
Poojas-MacBook-Pro:angular-electron-master poojatiwari$
┌───────────────┬──────────────────────────────────────────────────────────────┐

**Comment by 7867praveen** [comment]
<img width="1134" alt="screen shot 2018-08-26 at 10 59 19 am" src="https://user-images.githubusercontent.com/6420844/44625140-56320880-a91f-11e8-9326-aba2c28b5b06.png">

**Comment by 7867praveen** [comment]
I can share my screen as well to show you the exact issue in development build and production build.

**Comment by mauris** [comment]
I don't see any critical errors from your output that'd prevent the builder from producing your `dmg` and `app` files. Check your `release/mac`  folder for your `.app` file, and `release` folder for your `dmg` file.

You might need to show file extensions on your Finder too.

**Comment by 7867praveen** [comment]
The issue is not with creating the production build. I can see dmg file creates successfully but when I am running the build its not working properly and not giving any error. 
eg. In the application, there is a treeview that can be created dynamically and working fine in development but in production built that functionality is not working. Also it is not giving any error.

**Comment by mauris** [comment]
It seems your problem is more specific to your implementation, rather than in relation to the skeleton code in this repo.

One thing you need to be aware is that:

1) When in dev mode, the "renderer" part of your program being executed using "ng serve". Electron simply serves the content that is on `http://localhost:4200` (and that's how hot-reload can be done). In this mode, you cannot include files via `file:///` from your renderer.
2) When in production mode, the files are served via `file:///` instead of `http://`.

You can see this selection code in `main.ts` of the root folder.

**Comment by 7867praveen** [comment]
@mauris thanks for you response. Can you please help me more on this. I am attaching two screen shot 1. how app looks like in dev(http)
2. how app looks like in production(file://)
Can you suggest a fix for this? Or this issue is related to https://github.com/valor-software/ng2-tree

<img width="464" alt="screen shot 2018-08-26 at 9 33 16 pm" src="https://user-images.githubusercontent.com/6420844/44630235-fae03480-a977-11e8-92e2-7abeb9d9d74f.png">
<img width="442" alt="screen shot 2018-08-26 at 9 33 06 pm" src="https://user-images.githubusercontent.com/6420844/44630236-fae03480-a977-11e8-8330-ee33877b3cc0.png">

**Comment by mauris** [comment]
It does look at a build-related issue. Perhaps you can try running `npm run electron:local`, open devtools and debug what's missing from there?
