### ISSUE TITLE
Can I create a Tray Icon from angular?

### ISSUE THREAD

**Issue by BracketMan** [maximegris/angular-electron#233]
Hey Guys,

I've managed to get most of the API's working from the documentation but i'm struggling to create a Tray from angular. When I add the Tray in main.js/ts it works just fine but I'd love to be able to call methods from angular when a tray context menu item is clicked.

In my electron.service.ts constructor: 
`this.tray = window.require('electron').remote.Tray;`

I've tried importing the Tray module from electron but when I pass the icon path to the constructor I get : ERROR TypeError: electron__WEBPACK_IMPORTED_MODULE_2__.Tray is not a constructor

This is what it looks like in my home.component.ts:
`import { Tray } from 'electron';
let tray = new Tray('/src/favicon.ico');`

Any help would be appreciated, thanks guys!

**Comment by maximegris** [comment]
Hi

Try removing `/` at the beginning of  `/src/favicon.ico`
You can also remove Tray import because you use it through electron remote.

```typescript
      const tray = new this.remote.Tray('src/favicon.ico');
      console.log(tray);
```
