### ISSUE TITLE
tsc not using tsconfig / reconfigure project to allow node child process

### ISSUE THREAD

**Issue by Ketec** [maximegris/angular-electron#234]
I came upon this when trying to use promise in a child process (a promise error due to lack of lib target for es2005).

I assumed tsc uses the tsconfig from the root folder by default - but that does not seem to be the case.

tsconfig-electron.json
`{
    "compileOnSave": false,
    "files": ["main.ts", "process.ts"],
    "compilerOptions": {
        "sourceMap": false,
        "declaration": false,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es5",
        "typeRoots": ["node_modules/@types"],
        "lib": ["es2017", "es2016", "es2015", "dom"]
    },
    "exclude": ["dist", "src", "app-builds", "node_modules"]
}`

And:
`"electron:tsc": "tsc --p tsconfig-electron.json",`

Implementing something like that (perhaps there is a better way?) would make it easier to use child_process with node in the project  (a must have if you have anything that takes time to calc/save/process etc so you don't block main/renderer).

**Comment by maximegris** [comment]
I close the issue (inactive, no answer).

**Comment by Ketec** [comment]
@maximegris "I close the issue (inactive, no answer)." What answer? Isn't it waiting for your reply?
