### ISSUE TITLE
Communicating with the main thread

### ISSUE THREAD

**Issue by dennis-mathew** [maximegris/angular-electron#235]
To persist values across page refresh, I want to store it in the main thread (I can't use the local/session storage as per my use case). 

So from my home component how can I set a value on the main thread? An example of how to use 'remote' (which is available in the ElectronService provider) would be great.

Is this the right approach to persist a value till the application is active?

**Comment by Ketec** [comment]
Use ipcRenderer to send messages between main  and renderer.
Like sendSync for synchronous (can return value but blocks renderer until complete) or send (async, can return a event that you can listen to in renderer).

https://electronjs.org/docs/api/ipc-renderer
