### ISSUE TITLE
Schematics

### ISSUE THREAD

**Issue by GrandSchtroumpf** [maximegris/angular-electron#236]
Hello,
Have you thought of building schematics instead of a boilerplate?
It would enable dev to implement electron after starting a new project or using it with nrwl monorepo architecture for example.
Nativescript uses that to build mobile apps with Angular and I think it's pretty convenient.

**Comment by DmitriKom** [comment]
Hello @GrandSchtroumpf ,
For your convenience, I've found the following repository:
[https://github.com/ShPelles/electron-schematics](url)

Please check it out, it might be helpful.
