### ISSUE TITLE
Error: Cannot find module 'rxjs'

### ISSUE THREAD

**Issue by kgrandly** [maximegris/angular-electron#238]
After running `npm run electronic:windows` I open the exe file and get this error:

![image](https://user-images.githubusercontent.com/29640807/44404751-021ad300-a571-11e8-841e-b66b7f549170.png)

But app is running ok when i call `npm start` or `npm run ng:serve:web` or `npm run build[:prod]`

**Comment by kgrandly** [comment]
node: v8.11.1
npm: v6.0.1
nothing changed

**Comment by kgrandly** [comment]
node: v8.11.1
npm: v6.0.1

**Comment by murilobsd** [comment]
## Informations
- OS: Linux shinigami 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Os Version: Ubuntu 18.04
- Node: v8.11.3
- Npm: 6.3.0
## Run

## Out:

```
****
```

**Comment by gruntz12** [comment]
Any ideas how to fix it without removing rxjs from main.ts?

**Comment by maximegris** [comment]
In your package.json file :
- remove `rxjs` from devDependencies 
- add it in dependencies. 

It will be loaded by electron during build phase and added to the final package.

I added a chapter about this in the README.
