### ISSUE TITLE
use Augury in angular-electron development

### ISSUE THREAD

**Issue by ChenShiyu2** [maximegris/angular-electron#245]
[Augury](https://github.com/rangle/augury) is a Angular Debugging and Visualization Tools.

Is there a way to use Augury in angular-electron project?

**Comment by bampakoa** [comment]
@ChenShiyu2 I think there is no way yet. You can watch [this](https://github.com/rangle/augury/issues/687 ) issue in the Augury repository that describes the problem.

**Comment by maximegris** [comment]
Thanks 4 the answer @bampakoa !
