### ISSUE TITLE
Electron Builder bulding the app inside the dist folder

### ISSUE THREAD

**Issue by vijhhh2** [maximegris/angular-electron#247]
Hi,
I am Trying to activate notifications in windows. When  I am adding app.setUserModalId("<appId>")  in Main.ts and "build": { appId: "<appId>"} in package.json its buldin the app in dist folder and after running the app getting error "no resoursce found log"

**Comment by Hariskool** [comment]
electron-builder.json is available for changing the build location and 
![electronbuilder](https://user-images.githubusercontent.com/31043660/55605055-2936b580-578c-11e9-93f5-94db55319755.PNG)

**Comment by ddelapasse2** [comment]
@vijhhh2  did you resolve this?  My setup has that electron-builder.json but still puts the build artifacts into dist.
