### ISSUE TITLE
Lazy loading modules not working

### ISSUE THREAD

**Issue by isurendrasingh** [maximegris/angular-electron#248]
When using lazy loaded routes, i'm getting this error 
`Error: Uncaught (in promise): Error: Loading chunk 0 failed.`

I have used [this](https://github.com/maximegris/angular-electron/issues/58#issuecomment-331339496) and it's working fine except when i'm using the lazy loading like
`{path: 'records', loadChildren: './components/records/records.module#RecordsModule', canActivate: [AuthGuardService]}`

I thought it is because of `{useHash: true}`, but after removing this the first part was not working.

**Comment by shalomdotnet** [comment]
Try to use an absolute path instead of relative path.
In your case is something like: `loadChildren: 'app/components/records/records.module#RecordsModule'`.

**Comment by isurendrasingh** [comment]
@shalomdotnet I've tried this approach also, but getting same error. The only fix is by changing `<base href="">` to `<base href="./">` But now the problem is that, when i open child window using the approach mentioned i'm getting error 
`Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'index.html'`

**Comment by sandeepsuvit** [comment]
Also in some cases this also worked for me
```
loadChildren: '../components/records/records.module#RecordsModule'
```
depends on where we call the module from.
