### ISSUE TITLE
npm run start gives runtime errors because it lookups "window" global variable which is not available when running in nodejs/electron  and npm run ng:serve:web gives runtime errors because it lookups Nodejs "process" specific variable which is not available when running in browser

### ISSUE THREAD

**Issue by distributev** [maximegris/angular-electron#249]
Your seed project saves a lot of time when integrating angular and electron.

I think I found an issue with **_npm run start_** which is supposed to run under electron but lookups browser specific global variables and with **_npm run ng:serve:web_** which does the other way around in the sense that it lookups nodejs/electron stuff (which are not available under browser)

I followed the angular / angular-cli official documentation steps for integrating bootstrap however I get this runtime error. 

Is there anything which can be done for getting both with **_npm run start_** (electron) and **_npm run ng:serve:web (browser)_** work fine without runtime errors?

![image](https://user-images.githubusercontent.com/19224635/45543016-c8f21d80-b813-11e8-9cd3-b2b41f086ff3.png)

**Comment by distributev** [comment]
Thank you for your answer. 

What you see in the screenshot are the steps for using bootstrap from the official angular/angular-cli documentation. Do you know what is different with angular running under electron that these steps are not sufficient anymore?

**Comment by loic** [comment]
I think there are 2 issues here.

<img width="1319" alt="screen shot 2018-09-22 at 13 41 24" src="https://user-images.githubusercontent.com/36160/45916885-50bbd580-be6d-11e8-81e4-401e75a05e59.png">

The on coverd in the screenshot above seems to be the same as https://github.com/maximegris/angular-electron/issues/196, but the issue persist despite the 4.1.0 fixes, maybe it regressed at some point.
