### ISSUE TITLE
Where put the main-process files?

### ISSUE THREAD

**Issue by nicearma** [maximegris/angular-electron#25]
It's seem to work ok, but i don't see anything about the ipcMain logic, where to put this files and how to charge them

**Comment by nicearma** [comment]
I added one folder main-process where i put all the main process, and i had the same problem #18 i added 
`"build:electron:main": "tsc main.ts --outDir dist  && copyfiles package.json dist && cd dist && npm install && cd .."` to my package.json to fix the problem (i would be better to find something better than `cd dist && npm install && cd ..` )

**Comment by maximegris** [comment]
Hi,

You can add Main process or renderer process logic in any files you want to.

Indeed if you require 3rd party library in your code, the workaround #18 do the job. 
It's not the best solution I agree but I have no time to work on this :/

**Comment by vimes1984** [comment]
can someone explain to me how I then run the build process? ???
