### ISSUE TITLE
All console.logs are from zone-mix.js

### ISSUE THREAD

**Issue by adamk33n3r** [maximegris/angular-electron#252]
Is there a way to make the files and line numbers shown next to the logs be from where they actually are?
![image](https://user-images.githubusercontent.com/1350444/45923170-42d97500-beac-11e8-9f93-b255ed9de503.png)

**Comment by infrarosso78** [comment]
+1

**Comment by maximegris** [comment]
I have just published a new release (up to date with Electron 3 + Angular 7).

I removed the dependency with `zone-mix` in  `polyfill.ts` to make it work with Angular 7.

To upgrade to Angular 6, you can use https://update.angular.io/. When it's done, replace content at the end of of `polyfill.ts` (remove `zone-mix`)

```typescript

[...] 
/***************************************************************************************************
 * Zone JS is required by default for Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.


/***************************************************************************************************
 * APPLICATION IMPORTS
 */
```
