### ISSUE TITLE
Connecting to a Database

### ISSUE THREAD

**Issue by Nektoram** [maximegris/angular-electron#253]
Hello, 
so this is not an issue or something but rather just a question. I am pretty new to Electron, especially with Angular. I love it so far but I can't seem to get any database service working. I have no idea how to connect to a database with this repo, I'd love to use MongoDB with mLab though. I hope this doesn't get closed straight away for not being an issue. Thanks in Advance! 👍 
(By the way, if MongoDB connection isn't possible, I am alright with using MySQL or sth like that aswell)

**Comment by Nektoram** [comment]
Hey, @dhruv217 
I heard a lot about firebase already, I'll probably try to get MongoDB working first and when I got that done I'll take a look at firebase and see which one I like more. Thanks! 👍

**Comment by isurendrasingh** [comment]
This is one way to use MongoDB in this package. First you need to create a Express Server which will listen to database and connect your app to that server. 

Simply add this at the end of main.ts (the file is at the root of this repo)
```
const express = require('express');
const appExpress = express();

var mongoose = require('mongoose');
mongoose.connect('mongodb://127.0.0.1:27017/_database_name_', { useNewUrlParser: true, promiseLibrary: require('bluebird') })
  .then(() =>  console.log('connection successful'))
  .catch((err) => console.error(err));

appExpress.get('/', function (req, res) {
  res.send('Hello World!');
});

appExpress.listen(3000, function () {
  console.log('Example app listening on port 3000!');
});
```

`Change the _database_name_ to your database name`
Then launch the app and you should query your Express server on [http://localhost:3000](http://localhost:3000)

Also you will see connection successful in console. Rest apply your logics to the Express Routes and add them in main.ts.

**Comment by maximegris** [comment]
Thanks @isurendrasingh for the answer. I close the ticket due to inactivity.
