### ISSUE TITLE
Build ARM application?

### ISSUE THREAD

**Issue by kevintrankt** [maximegris/angular-electron#255]
When running 

```bash
npm run electron:linux
```

it builds an x85 AppImage file. Is it possible to build an ARMv7 AppImage?

**Comment by LuizTokuhara** [comment]
Yes, at the package.json change the line:
`"electron:linux": "npm run build:prod && npx electron-builder build --linux"`

To:
`"electron:linux": "npm run build:prod && npx electron-builder build --linux --armv7l"`

Then run again npm run electron:linux
