### ISSUE TITLE
Cannot find name 'BrowserWindow'

### ISSUE THREAD

**Issue by Oleg1983** [maximegris/angular-electron#258]
In folder providers in electron.service.ts I have problem:
```javascript
import { Injectable } from '@angular/core';

// If you import a module but never use any of the imported values other than as TypeScript types,
// the resulting javascript file will look as if you never imported the module at all.
import { ipcRenderer, webFrame, remote, BrowserWindow } from 'electron';
import * as childProcess from 'child_process';
import * as fs from 'fs';

@Injectable()
export class ElectronService {

  ipcRenderer: typeof ipcRenderer;
  webFrame: typeof webFrame;
  remote: typeof remote;
  childProcess: typeof childProcess;
  win: BrowserWindow;
  fs: typeof fs;

  constructor() {
    // Conditional imports
    if (this.isElectron()) {
      this.ipcRenderer = window.require('electron').ipcRenderer;
      this.webFrame = window.require('electron').webFrame;
      this.remote = window.require('electron').remote;
      this.win = window.require('electron').remote.getCurrentWindow();

      this.childProcess = window.require('child_process');
      this.fs = window.require('fs');
    }
  }

  isElectron = () => {
    return window && window.process && window.process.type;
  }
}
```
![screenshot_6](https://user-images.githubusercontent.com/18536448/46531675-be70f400-c8a6-11e8-877f-c85ab551717a.png)
When I write in my project 
`win: BrowserWindow; `
I get error Cannot find name 'BrowserWindow'. What is wrong? I did 
`import { ipcRenderer, webFrame, remote, BrowserWindow } from 'electron';`
I can't rewrite instead `win: typeof BrowserWindow;`
because in method toggleFullScreen() will not be to able method isFullScreen(), show(),setFullScreen(). 
![screenshot_7](https://user-images.githubusercontent.com/18536448/46531941-be252880-c8a7-11e8-8ff4-8156e5746b8c.png)
App work good in develop mode, but I have error and I can't build exe file. How fix that?

**Comment by maximegris** [comment]
👍
