### ISSUE TITLE
Differense between electron:local and npm start

### ISSUE THREAD

**Issue by Goffen** [maximegris/angular-electron#259]
Hi there! Thx for amazing bootstrap-framework.

Im trying to load up a file from assets-folder. But I cant get it to work when using npm start, only using electon:local - but i really like the hot reload.

Im using fs.readFileSync(path.join(__dirname, 'assets', 'file')). What do i need to do to get it working when using npm start?

**Comment by PsyGik** [comment]
When you use `npm start` you're running the application in a local server and it runs at `http://localhost:4200`. 

````
getData() {
  return this.http.get(`./assets/data.json`);
}
````

Should get you file from assets. Regardless of using `npm start` or `npm run electron:local`

**Comment by maximegris** [comment]
Thanks @PsyGik for the anwser. 👍 
I close the issue.
