### ISSUE TITLE
e2e using spectron?

### ISSUE THREAD

**Issue by distributev** [maximegris/angular-electron#260]
I am wondering why Spectron is not integrated for e2e testing here?

Spectron is the default electron testing framework - https://electronjs.org/spectron - spectron is for Electron only and it is independent of angular (which is good for e2e testing)
I used spectron through another electron boilerplate https://github.com/szwacz/electron-boilerplate

I developed a small application using angular-electron boilerplate and having the above spectron experience I tried to run npm run e2e now. This command failed because it tried to connect to localhost:4200/ and failed with "could not locate angular" error message. I know that this is related with the command npm run ng:serve:web; if I run this command localhost:4200/ url will not load and I know the reason. Even if initially I tried to keep both npm run start (electron) application and npm run ng:serve:web (web app) in sync and working together I soon realized I anyway only needed electron apis and needed to build a desktop electron app (and not a web app) so I soon stopped watching if npm run ng:serve:web is working or not. Currently npm run start works fine but npm run ng:serve:web fails because of the electron specific APIs and things used in the application. 

This is the reason I was initially asking about Spectron because spectron is electron specific and I know it will test only the "electron" desktop part of the app. I believe angular-electron tries to integrate angular into electron for building desktop apps so this is why I expected npm run e2e to run against electron -  However I am also fine if I could get somehow the current npm run e2e to avoid loading localhost:4200/ and to work and care only with the "desktop" electron. Is this possible?

**Comment by artemv** [comment]
Also current protractor e2e tests will not work if you use node libs in web app sources, e.g. 
```
// in src/app/components/folders-watch-worker/folders-watch-worker.component.ts
import * as fs from 'fs';
import * as path from 'path';
```
Spectron works with it just fine, just like the Electron app itself.

**Comment by loic-b** [comment]
> Right, current protractor e2e tests will not work if you use node libs in app sources, e.g.
> 
> ```
> // in src/app/components/folders-watch-worker/folders-watch-worker.component.ts
> import * as fs from 'fs';
> import * as path from 'path';
> ```
> 
> Spectron works with it just fine, just like the Electron app itself - so in my app I replaced protractor with Spectron already.

Hi,
I currently trying to do the same and... failed miserably to use spectron to e2e test my app!
Is it possible for you to show how you succeed to do it?

Thanks

**Comment by artemv** [comment]
@loic-b here: https://github.com/artemv/angular-electron-spectron
`npm install && npm run e2e` will run the tests on Spectron

**Comment by loic-b** [comment]
> @loic-b here: https://github.com/artemv/angular-electron-spectron
> `npm install && npm run e2e` will run the tests on Spectron

great job!
many many thanks to you!

**Comment by artemv** [comment]
@loic-b that's another story, I basically wanted to show a working configuration with Spectron. Mocha is definitely better for e2e because it allows tests to be retried easily, that's why I added it with Spectron. Btw I made a [PR](https://github.com/maximegris/angular-electron/pull/317), you can upvote it if you think it's a good idea to replace protractor with Spectron in this boilerplate.
