### ISSUE TITLE
How to add custom .ts files imported by electron main.ts into app bundle?

### ISSUE THREAD

**Issue by TheNightbear** [maximegris/angular-electron#265]
I've split up the `main.ts` of the electron app (not the one used in angular renderer app) into separate files. The idea is to keep business code out of the main.ts file. 

**Source file location**
These files are located in `src/main/`

**Import in main.ts** 
`import { MyService } from './src/main/services/my-service'; `

If I run it with `ng start`, it works perfectly. But when I create an app bundle (e.g. `electron: mac`), those files are not included in the build.

I can't find a place to configure that these classes should be included. 
Does anyone know how to achieve this?

**Comment by Leonardonline** [comment]
How do you are requiring or importing the separate files?

Maybe you need the `import `syntax.

**Comment by Leonardonline** [comment]
How do you are requiring or importing the separate files?

Maybe you need the `import `syntax.

**Comment by TheNightbear** [comment]
Hi @Leonardonline,
thanks for your response.
> How do you are requiring or importing the separate files?
>
> Maybe you need the `import `syntax.

(I've have updated my question.) I use the import statement and it works fine when I run it locally. 
I can't find any of the source files from `src/main` in the asar files, so I assume I have to configure it somewhere to tell the bundling process it has to include the compiled .js files from `src/main`.

Do you have an idea where I could do this?

**Comment by Leonardonline** [comment]
I'm using the same approach except that I import the file directly into the `main` of the angular app and it is working.

**Comment by TheNightbear** [comment]
Sounds promising. What do you mean with
 
> import the file directly

Can you share a code example?

**Comment by Ketec** [comment]
I added mine into the tsconfig-electron.json:

```
{
    "compileOnSave": false,
    "files": ["main.ts", "process.ts"],
    "compilerOptions": {
        "sourceMap": false,
        "declaration": false,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es5",
        "typeRoots": ["node_modules/@types"],
        "lib": ["es2017", "es2016", "es2015", "dom"]
    },
    "exclude": ["dist", "src", "app-builds", "node_modules"]
}
```

**Comment by TheNightbear** [comment]
Thank you. That's finally the same way as I import the file. And as I said the import itself is working (If it is started with `ng start`), finally it's about the **bundling**. I've created a new folder (`main`) within in the `src` folder, which contains source files I want to use within the **electron** main.ts (but not with the Angular).

So I'm looking for a way to add the files from the src/main folder. Would be very thankful if someone could help me here!

**Comment by Ketec** [comment]
Did you try adding the folder under assets in the angular.json?

**Comment by TheNightbear** [comment]
@Ketec sorry, my previous answer was a response to @Leonardonline response with the code example not to yours.

Thank you for response! I've tried the `"files": []` option within the tsconfig.json and made some progress:

I've added to my **tsconfig.json**
```
"files": [
    "my-service.ts"
  ],
```

...changed my import in **main.ts** to
`import { MyService } from './my-service';`

...and moved the **my-service.ts** file from `src/main/services/` to the projects root folder, so it's now in the same folder as the main.ts file.

By this, the bundled app is able to find the file.

As soon as I add more files, this will quickly become very confusing.
I also have to add each file individually to tsconfig.json. 

Hmm, that must work better somehow, so that you can organize the source code in a neat package structure.

**Is there anyone who can show us a clean way to do this?**

**Comment by Ketec** [comment]
@TheNightbear Then look at the electron-buildet.json. It has a list of files/folders it removes on build - and entire remove src from it and add the subfolders you don't want to include.

**Comment by TheNightbear** [comment]
@Ketec Your are absolut right! Thank you!! I played with it before, but maybe it was a little late that night... 

My adjustments to the list to include the required sources:

replaced 
```
        "!src",
````
with 
```
        "!src/*.*",
        "!src/app",
        "!src/assets",
        "!src/environments",
```
