### ISSUE TITLE
Change windows .exe file icon

### ISSUE THREAD

**Issue by GianLaz** [maximegris/angular-electron#268]
Hi, how can I change the .exe file icon? I changed the icons in the "src" folder. I also added the string:

icon     : path.join(__dirname, 'src/favicon.png')

in the object passed to the BrowserWindow function and I also tried with the object:

"win": {
    "icon": "src/favicon.png",
    "target": [
      "portable"
    ]
  }

in the electron-builder.json file and finally I also added the icon files in the "/build" folder but the .exe icon is always the same: the angular icon.
When I run the application in Windows 10 then the displayed icon is right (my icon) but the .exe file icon doesn't change.

**Comment by isurendrasingh** [comment]
This is because you need to include the `.ico or .icns(for mac)` version of your icon in the folder. Just follow along this [tutorial](https://www.christianengvall.se/electron-app-icons/) & you will get the result. Cheers.

**Comment by findela** [comment]
@isurendrasingh I tried the tutorial from above and it doesn't work with latest release with Angular 11.
