### ISSUE TITLE
App icon is broken

### ISSUE THREAD

**Issue by theneverstill** [maximegris/angular-electron#27]
It appears you're not overwriting 'DEFAULT_OPTS.icon' with the new icon path (so that it includes the extension). Also, as it is currently architected, you need to prefix the initial path with 'src/' => 'src/assets/favicon'.

**Comment by maximegris** [comment]
Indeed, the correct path was `src/favicon`

Thanks!

**Comment by theneverstill** [comment]
I didn't even notice the existing favicon. 👍
