### ISSUE TITLE
run tslint

### ISSUE THREAD

**Issue by rameshrc** [maximegris/angular-electron#273]
How to run tslint to report all linting/prettier js issues?

**Comment by vanchisel** [comment]
@rameshrc `tslist` is already in the package.json file, You can also follow the instructions [https://palantir.github.io/tslint/usage/cli/](url) although technical documents can be, well, technical.

This is what I do:

Update to the latest in the package.json file and/or:

$ `npm install -g tslist typescript`

Inside the root of your project folder where `tsconfig.json` is located, type:

$ `tslist -p .`

You should get a list of errors in the console **if** your code brakes the `tslint `rules defined in `tslint.json`. The console will be **really messy** if you set up your rules after you get far into writing your code **and** before you set up the rules.
