### ISSUE TITLE
Electron AutoUpdater Integration

### ISSUE THREAD

**Issue by indranil-tiwary** [maximegris/angular-electron#275]
Hey

Is there any AutoUpdater Integration out-of-the-box? How will it work with this boilerplate?

Thank you for the responses!

**Comment by leonetosoft** [comment]
This is also my doubt, I can not make it work.

**Comment by lgcovizzi** [comment]
I tried tb and I could not to do this!
Did you have any solutions?

**Comment by frankyso** [comment]
waiting for solutions...

**Comment by sarfarazansari** [comment]
@frankyso, @lgcovizzi , @leonetosoft , @indranil-tiwary 
here you go:
put this code in `main.ts` file after `window.loadURL` line.
```
if (!isDev()) {
      setTimeout(() => {
        elog.info('initiated app updater file');
        if (process.platform === 'darwin' || process.platform === 'win32') {
          // tslint:disable-next-line:no-unused-expression
          new AppUpdater();
        }
      }, 60000);
    }
```
and for app updater file look
`https://gist.github.com/sarfarazansari/c2ad6cb832c6e75e7e19a89c1bb736ce.js`

let me know if any issue.

**Comment by SitePointYves** [comment]
Would love to see a electron-builder autoupdate for gitlab/github solution in this repo too :)
