### ISSUE TITLE
karma.conf.js is ignored

### ISSUE THREAD

**Issue by farhad2161** [maximegris/angular-electron#287]
`src/**/*.js` in `.gitignore` file cause to ignore `src/karma.conf.js`

#git check-ignore -v src/karma.conf.js
.gitignore:10:src/**/*.js       src/karma.conf.js

**Comment by TomoyukiAota** [comment]
I created a PR for this issue.
https://github.com/maximegris/angular-electron/pull/303

**Comment by maximegris** [comment]
Thanks @TomoyukiAota , PR merged !
