### ISSUE TITLE
How to set electron-updater

### ISSUE THREAD

**Issue by forestweb** [maximegris/angular-electron#288]
when import `electron-updater` in `main.ts`:
`import { autoUpdater } from "electron-updater"`

and `npm start` the application, It is running failed,
the error message:
`ERROR in node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.d.ts(25,39): error TS1039: Initializers are not allowed in ambient contexts.`

**Comment by menendea** [comment]
I was trying to do the same but without success. Is there any way to solve this issue?

Publishing  a release is a must for doing a great app.

Regards

**Comment by maximegris** [comment]
What's your version of typescript ?

**Comment by az114q** [comment]
I solved the problem.
first, import * as updater from 'electron-updater';
second,  const autoUpdater = updater.autoUpdater;
then you can see it be work.
