### ISSUE TITLE
Change App icon

### ISSUE THREAD

**Issue by krishna2112** [maximegris/angular-electron#29]
can you please tell me how do i change app icon ?

**Comment by maximegris** [comment]
You just need to change favicon in root directory.

**Comment by krishna2112** [comment]
are you referring to favicon.ico in src folder, but when building for windows 

> npm run electron:windows 

is using electron logo as app icon

**Comment by maximegris** [comment]
Yep in `src` folder sorry.
I just tried and it seems to work.

Please check `package.js`. The file uses as app icon is defined here.

**Comment by krishna2112** [comment]
![2](https://user-images.githubusercontent.com/5575673/26879017-380b68b8-4bad-11e7-90cb-6c4c20d85716.PNG)
this is showing fine in task bar but 
![1](https://user-images.githubusercontent.com/5575673/26879040-4ed2ec2e-4bad-11e7-9a94-9821f78c559c.PNG)
showing default icon for exe file

**Comment by krishna2112** [comment]
changing  `const icon` in `package.js `helped, thank you
