### ISSUE TITLE
Integrate monaco editor

### ISSUE THREAD

**Issue by Nemtecl** [maximegris/angular-electron#290]
Hello,
I'm trying to integrate monaco editor using your project. I tried a lot of modules but they all produce an error ("window.require.config is not a function"). Then I followed the electron example of Microsoft (https://github.com/Microsoft/monaco-editor-samples/tree/master/electron-amd). It works only when I build your app. So I think that the problem come from the hot reload.

I'm looking for a way to integrate monaco editor in your app with both build and hot reload.

**Comment by deque-nathan** [comment]
Using nodeIntegration: false should work for you

```
new BrowserWindow({
    webPreferences: { nodeIntegration: false }
  });
```

**Comment by jakehockey10** [comment]
Will using `nodeIntegration: false` break anything that this repository relies on?
