### ISSUE TITLE
Cannot initialize distributed db HyperDb

### ISSUE THREAD

**Issue by saurabhabh** [maximegris/angular-electron#294]
I am trying make a distributed application using this template. I am facing an issue initializing [hyperdb](https://github.com/mafintosh/hyperdb). 
It gives me the error 

> Error: random-access-file is not supported in the browser

What I found is that hyperdb makes use of a module [random-access-file](https://github.com/random-access-storage/random-access-file) used for read/write. This module works fine with electron as can be seen in [Cabal](https://github.com/cabal-club/cabal-core). Only in this template is it giving issues. 

![image](https://user-images.githubusercontent.com/8706481/50478134-98ff0c80-09f5-11e9-9a5f-c4290ad0436d.png)

**Environment**
I am using a Windows 10 machine and my environment is as follows 
![image](https://user-images.githubusercontent.com/8706481/50478267-52f67880-09f6-11e9-8d63-49d7dd4586e1.png)

**Steps to reproduce :** 

- Download the latest version of angular-electron.  

- npm install hyperdb

- In home.component.ts 
var hyperdb = require('hyperdb')

- In home.component.ts 
ngOnInit() {
    var db = hyperdb('./my.db', {valueEncoding: 'utf-8'})
  }

**Comment by maximegris** [comment]
Hi !
Please have a look at `electron.service.ts` file if you want to import dependencies that can only work in a nodejs context.

**Comment by saurabhabh** [comment]
Thank you for the tip. I was able to get it working.
