### ISSUE TITLE
Storybook integration

### ISSUE THREAD

**Issue by jgarec** [maximegris/angular-electron#301]
Hi,

I would like to know if any of you succeed to integrate storybook to this project ?
I tried to follow [this guide](https://storybook.js.org/basics/guide-angular/) but obviously I can not integrate it correctly.

Thx for your help.

**Comment by whyboris** [comment]
I have tried _Storybook_ about a year ago with an production Angular application and found it didn't automatically generate a component gallery - requiring you to manually (and tediously) invoke every element you wanted (and it wasn't easy to get all the component _inputs_ set correctly) ... so pretty low value.

Have you had success with it outside of _angular-electron_? What do you expect this library to provide?
