### ISSUE TITLE
...is not a valid Win32 application

### ISSUE THREAD

**Issue by az114q** [maximegris/angular-electron#302]
Hello，I have some trouble.
My package.json
  "dependencies": {
    "@swimlane/dragula": "^3.7.3",
    "@swimlane/ngx-dnd": "^6.0.0",
    "@types/dragula": "^2.1.34",
    "angularx-qrcode": "^1.2.4",
    "canvas-resize": "^1.1.0",
    "electron-updater": "3.0.3",
    "less": "^2.7.3",
    "machine-uuid": "^1.2.0",
    "mqtt": "^2.18.8",
    "ng-zorro-antd": "^1.8.0",
    "ngx-clipboard": "^11.1.9",
    "nodemailer": "^4.0.1",
    "soe-escpos": "^1.0.3",
    "usb": "^1.5.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.6.3",
    "@angular/animations": "6.1.0",
    "@angular/cli": "6.1.2",
    "@angular/common": "6.1.2",
    "@angular/compiler": "6.1.2",
    "@angular/compiler-cli": "6.1.2",
    "@angular/core": "6.1.2",
    "@angular/forms": "6.1.2",
    "@angular/http": "6.1.2",
    "@angular/language-service": "6.1.2",
    "@angular/platform-browser": "6.1.2",
    "@angular/platform-browser-dynamic": "6.1.2",
    "@angular/router": "6.1.2",
    "@ngx-translate/core": "10.0.1",
    "@ngx-translate/http-loader": "3.0.1",
    "@types/jasmine": "2.8.7",
    "@types/jasminewd2": "2.0.3",
    "@types/node": "8.9.4",
    "codelyzer": "4.2.1",
    "core-js": "2.5.6",
    "electron": "2.0.7",
    "electron-builder": "20.28.1",
    "electron-reload": "1.2.2",
    "jasmine-core": "3.1.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "2.0.2",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage-istanbul-reporter": "2.0.0",
    "karma-jasmine": "1.1.2",
    "karma-jasmine-html-reporter": "1.1.0",
    "npm-run-all": "4.1.3",
    "npx": "10.2.0",
    "protractor": "5.3.2",
    "rxjs": "6.2.2",
    "ts-node": "6.0.3",
    "tslint": "5.10.0",
    "typescript": "2.7.2",
    "wait-on": "2.1.0",
    "webdriver-manager": "12.0.6",
    "zone.js": "0.8.26"
  }

I have no problem packing my project.
But when I run , have some error.

ERROR Error: \\?\C:\Users\Administrator\AppData\Local\Temp\6ec9447f-56e9-42c9-a119-5e26d9261edc.tmp.node is not a valid Win32 application\\?\C:\Users\Administrator\AppData\Local\Temp\6ec9447f-56e9-42c9-a119-5e26d9261edc.tmp.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\收银台\新\soe-hdwms\resources\app.asar\node_modules\usb\usb.js:5:38)
    at Object.<anonymous> (D:\收银台\新\soe-hdwms\resources\app.asar\node_modules\usb\usb.js:526:3)

All other modules are good. Only use 'soe-escpos' ，it tell me error.

**Comment by az114q** [comment]
@maximegris excuse me,
 I think used navtive module cause my error, and maybe postinstall.js can solved my problem.
Could you tell me how to use postinstall:electron in builder win.exe?

**Comment by finaldzn** [comment]
Hello did you manage to fix this error ?
