### ISSUE TITLE
Problems with some Packages

### ISSUE THREAD

**Issue by FuelKubitox** [maximegris/angular-electron#309]
A couple of Month ago i used your Repo to start with a private Project. After the Time passes i changed more and more Things in my Project. Several Times i need to reconfigure Things because something doesnt work. As Example, you cant use SQLite3 with TypeORM with this Build.

I found a Solution for that. I installed the Package ngx-build-plus. With this Package you can add Custom Webpack Configurations in your Project. I needed this to export some Node Modules with the Package webpack-node-externals. I read that the Command ng eject is deprecated and this is the best Solution for this. Maybe you can update this Project with these Configurations.

**Comment by frankyso** [comment]
@FuelKubitox hi, currently im working with same package as you using, can you give me an example how to make it owkring with TypeORM ans SQLite3? thankyou

**Comment by FuelKubitox** [comment]
Install ngx-build-plus and webpack-node-externals with npm or like `this`
`
Install ngx-build-plus:

When using Angular >= 7 and CLI >= 7, you can simply use ng add for installing ngx-build-plus:

ng add ngx-build-plus 
If you are using a monorepo, mention the project you want to install ngx-build-plus for:

ng add ngx-build-plus --project myProject
Alternative: If, and only if, this does not work for you, e. g. because you use an earlier Angular version, you can install the library manually:

npm install ngx-build-plus --save-dev
After this, update your angular.json:

[...]
"architect": {
    "build": {
        "builder": "ngx-build-plus:build",
        [...]
    }
}
[...]
Create a file webpack.extra.js with a partial webpack config that tells webpack to exclude packages like @angular/core:

module.exports = {
    "externals": {
        "webpack-node-externals()"
    }
}
`
After that you have to add ng build --prod --extraWebpackConfig webpack.extra.js to your build Script in angular.json. More Information here https://github.com/manfredsteyer/ngx-build-plus
