### ISSUE TITLE
Is it possible to integrate orbtidb and ipfs?

### ISSUE THREAD

**Issue by lgcovizzi** [maximegris/angular-electron#311]
for an application without a server, how to integrate the orbitdb, as a service? 
I tried to create a service, but to stop this error.

`import { Injectable } from '@angular/core';
import {OrbitDB} from 'orbit-db';
import {IPFS} from 'ipfs';
@Injectable({
  providedIn: 'root'
})
export class DbService {

//ipfs
ipfsOptions = {
  EXPERIMENTAL: {
    pubsub: true
  },
}
ipfs = new IPFS(this.ipfsOptions)
  constructor() { 
    this.ipfs.on('error', (e) => console.error(e))
    this.ipfs.on('ready', async () => {
      // Create a database
      const orbitdb = new OrbitDB(this.ipfs)
      const db = await orbitdb.log('database')
      // Add an entry to the database
      const hash = await db.add('hello')
      // Get last 5 entries
      const latest = db.iterator({ limit: 5 }).collect()
      console.log(JSON.stringify(latest, null, 2))
    })
  }
}
`

ERROR in ./node_modules/zcash-bitcore-lib/lib/crypto/random.js

**Comment by maximegris** [comment]
Sorry I don't know how to use orbtidb and ipfs libraries
By the way if they work in a nodeJS context, I invite you to have a look at `electron.service.ts`
