### ISSUE TITLE
how to add flag --experimental-worker to node?

### ISSUE THREAD

**Issue by emko** [maximegris/angular-electron#312]
i am trying to  use worker_threads and i need to set the flag --experimental-worker, i am looking at the package.json but i can't figure out where to put the flag for node?

https://nodejs.org/docs/latest-v10.x/api/worker_threads.html

anyone know how i can do this?
 thanks

**Comment by aarmora** [comment]
@emko I see that you closed this. I have the exact same need. Did you get it working?
