### ISSUE TITLE
How to require a node.js (.js) file and hot reload this file

### ISSUE THREAD

**Issue by forestweb** [maximegris/angular-electron#318]
I went to set a .js file to read IPC message. Where should I require this .js file? If I  require .js in the main.ts file, it won't work hot reload.

**Comment by Hariskool** [comment]
To read IPC message you have to set your IPC listener in main.ts which will be translated into js on compile time
![mainTs](https://user-images.githubusercontent.com/31043660/55604790-0952c200-578b-11e9-979a-a2c08288eb46.PNG)

**Comment by maximegris** [comment]
Thanks @Hariskool !
