### ISSUE TITLE
Property height 100% not working in Angular 7 + Electron 4

### ISSUE THREAD

**Issue by Oleg1983** [maximegris/angular-electron#319]
I have a component jobs-table.component.html

```
<div class="jobs-table">
 ...
</div>
```

And style jobs-table.component.css:

```
:host {
  flex-grow: 1;
}
.jobs-table {
  height: 100%;
}
```

In Crome v73 and Mozilla v65.0.2 `height: 100%` working good. But in Electron 4 and Opera v58 not working ! I see only two way to fix this in my case use
`height: calc(100vh - 15rem);`
or
`:host {
  flex-grow: 1;
  position: relative;
}
.jobs-table {
  height: 100%;
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
}
`

Are there others ways to fix this ? 
Code here [https://stackblitz.com](https://stackblitz.com/edit/angular-pkipxs)
Thanks advance

**Comment by Hariskool** [comment]
html, body, app-root {
  height: 100%;
  width: 100%;
  margin: 0;
}
try this for full height and width

**Comment by Jakhongiirr** [comment]
Hi. I think you already found solution but think it will be helpful for smb. just go to global css file (comment /* You can add global styles to this file, and also import other style files */ written in it) and add *{margin:0; padding:0}
good luck everyone))
