### ISSUE TITLE
Could we get a minimal angular-electron?

### ISSUE THREAD

**Issue by CodeSwimBikeRun** [maximegris/angular-electron#320]
I cant figure out what all I need to rip out of this thing. 

1. whats the postinstall, why do i need it.
2. whats the poscss.config, why would you need it?
3. why are there so many configs and logos? what is a _config. Why would you force me into travis?
4. why is there so many separate tsconfig vs tsconfig-serve. just use the same. or separate your serve files in a serve folder.
5. Do we really need that many start up scripts?
6. There are a million favicons. why? If i try to rip these out, it doesnt build now.
I'm new to electron, but i know I want typescript and angular, but this project is just overwhelming.

**Comment by thedevbc** [comment]
It looks to me that #1 is pretty important. It's what sets up Angular to be able to use Node's access to the Operating System, as in, being able to access the file system, usb devices, etc. A normal web browser can't access those things, but Electron via node is able to.

**Comment by maximegris** [comment]
Thanks @thedevbc for the first answer 👍 

 @CodeSwimBikeRun I don't force you to use this repo, I think you can find a lightweight project which match what you need :)
