### ISSUE TITLE
How can we debugger the ts file?

### ISSUE THREAD

**Issue by dming4** [maximegris/angular-electron#323]
I want to debug the home.component.ts  file, how should i to do?

**Comment by dming4** [comment]
I want debug the  typescript file of angular in vscode, not the main.ts file, not  in  broswer.

**Comment by nikhilnxvverma1** [comment]
I have the same question. Hoping for a VSCode based solution. The debugger doesn't attach right away on port 4200

**Comment by dming4** [comment]
no long no answer, sad...
