### ISSUE TITLE
Electron Service TypeError: Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by Hariskool** [maximegris/angular-electron#324]
this.electron.ipcRenderer.send('reques-check', email); (i'm using Electron Service provided by you)

im using this in user service in a function .When this  function is called it gives send is undefined property

![problem1](https://user-images.githubusercontent.com/31043660/55492457-ad841e00-5650-11e9-931e-4d757eee7f73.PNG)
![p2](https://user-images.githubusercontent.com/31043660/55492666-0653b680-5651-11e9-9758-69944dad1e11.PNG)

i also added the IPmain.on listerner in the main.ts

**Comment by Leonardonline** [comment]
Did you inject the service in the constructor?

**Comment by Hariskool** [comment]
yes I'd added  the inject the main reason it was blocked by these attribute which id added into my main.ts
      nodeIntegration: false,
      nodeIntegrationInWorker: false,
      allowRunningInsecureContent: false

**Comment by mdabdul330** [comment]
I see the same error in ELectron. But I am not quite sure about injecting the constructors. Could you please explain how it can be done.

**Comment by Hariskool** [comment]
where and on what function you are facing this error?
