### ISSUE TITLE
Using custom fonts

### ISSUE THREAD

**Issue by Leonardonline** [maximegris/angular-electron#325]
I have made many attempts to import custom fonts into the project, but I haven't succeeded yet.

I'm not sure if the problem is related to Angular or Electron.

Someone has the same problem or uses custom fonts in both development and build ?

**Comment by fripso** [comment]
Do you mean CSS font imports? Can't see why that would be related to Angular OR Electron.

**Comment by Leonardonline** [comment]
Yes, I mean CSS font imports.
In some of my try, the fonts working in dev mode, but when I built all, the path of the fonts was referred to the root of the disk, for this reason, I suppose should be related to Electron; probably I should have written electron-builder but I not sure also.

**Comment by fripso** [comment]
Make sure you copy your fonts when building: 
` "assets": [
                            {
                                "glob": "**/*",
                                "input": "./src/assets/yourfontsdirectory",
                                "output": "./assets/yourfontsdirectory/"
                            }
                        ],`

**Comment by Hariskool** [comment]
add your css here if you are using custom fonts or in component css
![css](https://user-images.githubusercontent.com/31043660/55622300-3c13af00-57b9-11e9-97dd-d61786098f5e.PNG)

**Comment by Leonardonline** [comment]
Unfortunately, neither solution works :(

**Comment by fripso** [comment]
You'd have to provide some context/code for us to help you solve the issue!

**Comment by Leonardonline** [comment]
I made a fork and modified some files to replicate my problem.
If I run in dev I can see the custom font, but if I build for windows the font doesn't work.

The link:
https://github.com/Leonardonline/angular-electron

**Comment by Leonardonline** [comment]
Could someone give me a link/repo that uses a custom font?

**Comment by chill-patel** [comment]
we are also facing  same issue in dev mode font is loading properly but after creation build is not loading font any working example would be great.

one more thing I found while debug after build in windows font file location is changed
don't know how this happens
