### ISSUE TITLE
Request: Support Typescript path mapping

### ISSUE THREAD

**Issue by ottosson** [maximegris/angular-electron#330]
I want to share some typings between main and renderer. So I thought Typescript path mapping would be perfect for this so I don't have to write relative paths everywhere.

I've tried to understand how to implement it in my angular-electron project, but with no success. VSCode understands them, but when I build I get errors saying the paths can't be resolved. Weird since @angular imports are also path mapping, and those modules still gets imported without any problems.

I just add these lines to the tsconfig.json:
```
"compilerOptions": {
  "baseUrl": ".",
  ...
  "paths": {
    "@common/*": ["src/common/typings/*"]
  }
}
```

It would be nice if angular-electron supported [Typescript path mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping), out of the box.

Anybody knows how to get this to work?

**Comment by nikhilnxvverma1** [comment]
Hi, can you look at #364
