### ISSUE TITLE
How to use Webview Directive?

### ISSUE THREAD

**Issue by plambe8** [maximegris/angular-electron#332]
Hey, this isn't about this repo in particular but I wanted to ask the maintainer...what makes the webview directive work? I've done exactly what this repo has in my own project, but I get the error that webview is not a valid component:

`compiler.js:2409 Uncaught Error: Template parse errors:
'webview' is not a known element:
1. If 'webview' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("`

What is the part that allows this to work? It's driving me nuts

**Comment by plambe8** [comment]
Got it working. Had to do the import in the module it was being used and not in App Module

**Comment by UoToGK** [comment]
Why can't I use it in the App module?

**Comment by Y2zz** [comment]
@plambe8 Does your project webview work properly?

**Comment by raviada** [comment]
how to use this directive in template?
I imported it in the same module where my component is but still it says <webview> is unknown element.
