### ISSUE TITLE
what do you do to use node modules inside angular code?

### ISSUE THREAD

**Issue by agomezb** [maximegris/angular-electron#333]
Hi, in old versions you eject angular and configure webpack in order to use node modules inside angular code.

How do yo do this in the last versions?

thanks

**Comment by agomezb** [comment]
this is the old solution

https://github.com/maximegris/angular-electron/issues/2

**Comment by ddelapasse2** [comment]
Can you keep the node stuff on the electron side and communicate with ipc?

**Comment by maximegris** [comment]
@ddelapasse2 is right or you can have a look at `electron.service.ts` file
