### ISSUE TITLE
Property 'require' does not exist on type 'Window'.

### ISSUE THREAD

**Issue by mahrmediait** [maximegris/angular-electron#334]
Hello,

if I try to build it with npm run electron:mac I will get the following error:

ERROR in src/app/providers/electron.service.ts(21,33): error TS2339: Property 'require' does not exist on type 'Window'.

Can anybody help me?

Best greetings!

**Comment by danoespinoza** [comment]
You must change Window interface by global Window statement ([src/typings.d.ts]).

`declare var window: Window;
declare global {
  interface Window {
    process: any;
    require: any;
  }
}`
