### ISSUE TITLE
How to create a Windows installer?

### ISSUE THREAD

**Issue by ddelapasse2** [maximegris/angular-electron#338]
First, thanks for this project!  It finally let me combine my Ang7 + Electron + VSCode debugging.

I can see that "npm run electron:windows" creates an exe installer in the dist folder, but it doesn't include my node references.  Would "npm run postinstall" be the final step to pack everything?  I'd prefer that the artifacts go into the /release folder and it appears that the electron-builder.json file is set up to do that but it doesn't seem to be used.

**Comment by sarfarazansari** [comment]
@ddelapasse2 
take a look below snippet for your reference
```
"win": {
    "icon": "src/assets/electron/icon.ico",
    "target": [
      "nsis",
      "nsis-web",
      "zip"
    ],
    "publisherName": "YOUR_COMPANY",
    "certificateSubjectName": "SOME_OTHER"
  },
  "nsis": {
    "oneClick": true,
    "createDesktopShortcut": true,
    "createStartMenuShortcut": true,
    "menuCategory": "Communication",
    "shortcutName": "Kiss",
    "perMachine": false,
    "installerIcon": "src/assets/electron/icon.ico",
    "uninstallerIcon": "src/assets/electron/icon.ico",
    "runAfterFinish": true
  },
  "asarUnpack": "./node_modules/node-notifier/vendor/**",
  "asar": true
```

**Comment by seannowotny** [comment]
For me simply replacing "target" from "portable" to "nsis" worked.
