### ISSUE TITLE
Missing new npm modules in electron in prod build

### ISSUE THREAD

**Issue by theneverstill** [maximegris/angular-electron#34]
If one adds a new npm module that is only used in electron on the backend, it will be missing in prod builds (ie it is not copied to the dist dir). Can you update the readme for this case?

E.g.: https://github.com/mawie81/electron-window-state

**Comment by maximegris** [comment]
Npm module are copied in /dist directory if they are defined in dependencies (not devDependencies) of package.json because of `--prod` parameter of `build:electron:main` script. I will update the README in that way.

I made a try with `electron-window-state` and the module is copied in /dist dir.

**Comment by maximegris** [comment]
I had the same issue indeed. 
I removed my `node_modules` dir (installed with yarn) and I made a `npm install`.
Now when I run prod builds, modules are presents in /dist directory.

Did you install your packages with yarn too ?

**Comment by theneverstill** [comment]
Weird. I have only been using npm (5.0.3), not yarn. Had to clear node_modules and fresh install for it to work. Any idea why?

**Comment by maximegris** [comment]
I upgrade npm to v5 last week. I don't know yet if there are side effects on package installation.

**Comment by theneverstill** [comment]
The install itself was working fine in dev mode. For some reason it would fail in prod mode.

**Comment by maximegris** [comment]
Did you reproduce this error since last time ?
