### ISSUE TITLE
Error When running npm install :(

### ISSUE THREAD

**Issue by arslanmughal5566** [maximegris/angular-electron#341]
after cloning the repo when i install dependencies with npm it gives me the following error 
```
2025 verbose node v11.11.0
2026 verbose npm  v6.7.0
2027 error Unexpected end of JSON input while parsing near '....4","memory-fs":"^0.4'
2028 verbose exit [ 1, true ]
```
also this error changes every time i try `npm i`
`2027 error Unexpected end of JSON input while parsing near '....4","memory-fs":"^0.4'`
i'm trying to solve this from a while nothing works :(
any Idea why this is happening ?

**Comment by arslanmughal5566** [comment]
after few times typing `npm install` 
i succeeded in installing but its not working in one time you have to do `npm install ` several times

**Comment by sarfarazansari** [comment]
@arslanmughal5566 use `yarn` instead it will work fine

**Comment by maxfriedmann** [comment]
https://github.com/maximegris/angular-electron/issues/298#issuecomment-452299556 helped me
