### ISSUE TITLE
compiling errors while using require

### ISSUE THREAD

**Issue by sarfarazansari** [maximegris/angular-electron#343]
@maximegris,
am not able to identify the actual reason why it is happening.

when I start app by `yarn ng:serve:web` it shows me some compiling errors.
while with same code base if I run `npm run start` it works.

below is the snippet that causing errors.
In electron.service.ts file
        ```
this.ipcRenderer =  require('electron').ipcRenderer;
        this.webFrame =  require('electron').webFrame;
        this.remote =  require('electron').remote;
        this.shell =  require('electron').shell;
        this.childProcess =  require('child_process');
        this.fs =  require('fs');
        this.googleAuth =  require('google-auth-library');
        this.http =  require('http');
        this.url =  require('url');
        this.opn =  require('opn');
        this.destroyer =  require('server-destroy');
        this.filereader = require('filereader');
        this.analytics = require('analytics-node');
        this.yaml = require('js-yaml');
        this.semver = require('semver');
```

I tried using `(<any>window).require('electron').ipcRenderer`
it will work in web app but throw errors in packed app.

could you please guide me how to fix this one.

@maximegris thanks in advance

**Comment by ac566** [comment]
You should post the error message. 

I am also having this issue when using yarn, but did not when using npm.

It could be that yarn prevents changing files  in the node_modules directory, causing the postinstall script to do nothing.

**Comment by sarfarazansari** [comment]
@maximegris did you get the time to look into this one?
