### ISSUE TITLE
Serialport

### ISSUE THREAD

**Issue by gtg489w** [maximegris/angular-electron#347]
I'm encountering errors when trying to include the node serialport library in this framework. I'm working in a Windows environment. Below are the steps to reproduce the error:

```
git clone https://github.com/maximegris/angular-electron.git
cd angular-electron/
npm install
npm run electron:windows
```

The above launches as expected. But when serialport is installed and rebuilt then I encounter errors:

`npm install serialport --save`

In main.ts I add the following:

```
const serialport = require('serialport');
serialport.list((err, ports) => {
	console.log('ports', ports);
});
```
And rebuild
`npm run electron:windows`

```
Error: The module ... was compiled against a different Node.js version using
NODE_MODULE_VERSION 47. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

I've tried several of the recommended solutions including modifying package.json but have had no luck. Everything works find when I simply run `npm start`. Thoughts?

**Comment by nthjelme** [comment]
I had a similar issue when upgrading to angular 8 and electron 5. I could not get serialport to rebuild. 

Changed electron version from 5 to 4.0.2 solved my issue.

**Comment by michaelcerne** [comment]
Try:

> If you require serialport as a dependency for an Electron project, you must compile it for the version of Electron your project's using.
> 
> When you first install serialport it will compile against the version of Node.js on your machine, not against the Node.js runtime bundled with Electron.
> 
> To recompile serialport (or any native Node.js module) for Electron, you can use electron-rebuild; more info at Electron's README.
> 
> 1. `npm install --save-dev electron-rebuild`
> 2. Add `electron-rebuild` to your project's package.json's install hook
> 3. Run `npm install`

From https://serialport.io/docs/guide-installation#electron

**Comment by Ronalses** [comment]
@gtg489w did you have a solution?

**Comment by gtg489w** [comment]
I wasn't ever able to get this working. Sadly, I ended up launching the application in development mode with a script since this was a prototype. Some day I'd like to get this working properly.

**Comment by Ronalses** [comment]
@gtg489w  this works for me https://github.com/maximegris/angular-electron/issues/384#issuecomment-535122273

**Comment by maximegris** [comment]
#384
