### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by ssuriyayuvan** [maximegris/angular-electron#350]
/home/babulal/Desktop/angular-electron-master/node_modules/electron/dist/electron: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /home/babulal/Desktop/angular-electron-master/node_modules/electron/dist/electron)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-electron@6.0.1 electron:serve: `wait-on http-get://localhost:4200/ && npm run electron:serve-tsc && electron . --serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-electron@6.0.1 electron:serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-12T08_28_28_689Z-debug.log
ERROR: "electron:serve" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-electron@6.0.1 start: `npm run postinstall:electron && npm-run-all -p ng:serve electron:serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-electron@6.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-12T08_28_28_813Z-debug.log

**Comment by samoka** [comment]
Having the same issue, have you been able to resolve?

**Comment by nopoku** [comment]
Same issue. Anyone have an answer?

**Comment by ASteb** [comment]
Update nodejs

**Comment by PeterTognola** [comment]
I was hitting a similar issue, upgrading electron to 6.0.2 (and dependencies) in the package.json solved the problem for me.

F.Y.I: I am running Node v12.7.0.

**Comment by ssuriyayuvan** [comment]
finally found a solution by using node 10.16.0 and thanks all for replying.
