### ISSUE TITLE
Error when Run the command nom run electron:mac

### ISSUE THREAD

**Issue by sdatrik** [maximegris/angular-electron#352]
I am getting the error when I try to run the build command for Mac. Below is the error.

can someone have faced the similar issue? Please help me.

Mac OS - macOS Sierra version 10.12.6
node version - v10.16.0
"electron": "4.0.0",
"electron-builder": "20.43.0",

![error](https://user-images.githubusercontent.com/37628196/59444620-33001900-8dcc-11e9-9f39-0eefff4725a6.png)

**Comment by maximegris** [comment]
Hi

Can you try to upgrade electron-builder to the latest version ? Does you still have this issue ?
