### ISSUE TITLE
macOS: Karma reconnecting in X seconds… ng test stops watching for changes

### ISSUE THREAD

**Issue by FrancescoBorzi** [maximegris/angular-electron#354]
I'm not sure if this is related with angular-electron, however in my project I'm having the problem described here:  https://stackoverflow.com/questions/56619589/macos-karma-reconnecting-in-x-seconds-ng-test-stops-watching-for-changes

This happens only on Mac, but works fine on Ubuntu.

Is anyone using angular-electron on macOS having the same issue?

**Comment by FrancescoBorzi** [comment]
the issue is still valid

**Comment by cheplv** [comment]
@FrancescoBorzi can you check latest revision (master) is this still happens, due latest change of testing process from chrome to native karma-electron.
