### ISSUE TITLE
Clarity about tsconfig*.json files

### ISSUE THREAD

**Issue by FrancescoBorzi** [maximegris/angular-electron#357]
If I understand correctly there is:

- `src/tsconfig.spec.json` that inherits from `tsconfig.json` that is used for **tests**
- `tsconfig-serve.json` that is used in for both **serve** and **build**

is this correct?

Also there is `src/tsconfig.app.json` that inherits from  `tsconfig.json`. What is this one used for?

**Comment by nikhilnxvverma1** [comment]
It was confusing for me too initially. But when you inspect your demands, you will notice you have different 'targets' with varying idiosyncrasies. All those (leafy) tsconfigs are used in specific targets.

1. `src/tsconfig.spec.json` is used by ng test
2. `tsconfig-serve.json` is used by 'main' process when the flag is set to serve
3. `src/tsconfig.app.json` is used by the main angular app in the (UI process)
4.  `tsconfig.json` is used as a base and by main process during packaging when `serve` flag is not set in command line

**Comment by maximegris** [comment]
All is said :)
Thanks @nikhilnxvverma1  👍
