### ISSUE TITLE
Webview does not work

### ISSUE THREAD

**Issue by Y2zz** [maximegris/angular-electron#362]
1. cloning the project
2. I added in home.component.html in the `<webview src =" http://www.google.com "> </ webview>`
3. `npm start` webview in the window did not load the page

![Snipaste_2019-07-19_06-36-26](https://user-images.githubusercontent.com/252604/61496687-9eeb2800-a9ef-11e9-94e3-7506d21985ab.png)

**Comment by Y2zz** [comment]
Resolved, since electron5 turns off webview by default, it needs to be in [`main.ts`](https://github.com/maximegris/angular-electron/blob/956381cd7487306f67a534e06098d21af299d09d/main.ts#L22) file add line `webview: true`

**Comment by UoToGK** [comment]
are you sure?i do that,but it does't work

**Comment by Y2zz** [comment]
I am sure that it is valid only when using the electron runtime.
