### ISSUE TITLE
ng test fails

### ISSUE THREAD

**Issue by lgLindstrom** [maximegris/angular-electron#364]
Hi

I've written a application based on your template (seed).
Unfortunately tests will not run. (ng test)

Only modification I done to the original tsconfig.json file is adding paths.

```
   "paths": {
      "@components/*": ["src/app/components/*"],
      "@pipes/*": ["src/app/pipes/*"],
      "@dialogs/*": ["src/app/dialogs/*"],
      "@services/*": ["src/app/services/*"],
      "@directives/*": ["src/app/directives/*"],
      "@providers/*": ["src/app/providers/*"],
      "@models/*": ["src/app/models/*"],
    },
```

ng test  gives this error:
`ERROR in app/services/settings.service.ts:4:31 - error TS2307: Cannot find module '@models/userInformation'.`

The strange thing is that the application actually works..... ( npm start )

Anyone to help ...??

**Comment by nikhilnxvverma1** [comment]
May I know the reasoning behind adding those path configurations? Ideally, angular.json stores such configurations. Also, you should use `npm run test`. Did you try running that command on a fresh project with no modifications?

For what it's worth, the actual `ng test` command actually references the tsconfig.spec.json under src. That file extends tsconfig.json in the base directory. You probably already know this. I just wanted to establish this otherwise.

**Comment by lgLindstrom** [comment]
Hi
I use those paths to avoid using relative paths in the application. Have I misunderstood something here. When googling on this, the only answer I have found ( for example this link https://stackoverflow.com/questions/34925992/how-to-avoid-imports-with-very-long-relative-paths-in-angular-2 ) is that they should be put in tsconfig.json.

You are saying that it should be placed in angular.json ,, how ?

`npm run test` gives same error.

Fresh project works.

Yes, I am aware of tsconfig.spec.json .  Putting  path declaration in that file makes no difference.

**Comment by nikhilnxvverma1** [comment]
Thanks for the clarification. My guess is that you will have to put those path declarations in `src/tsconfig.spec.json` keeping in mind to have the right relative paths. This means removing the leading 'src' level from each item. Running ng test again should catch those shortcodes and fetch the correct expansions as they were intended to run from within the src directory.

`npm run test` or `ng test` still needs to run from the base directory.

**Comment by lgLindstrom** [comment]
Just to understand. This line in tsconfig.spec.json

`"extends": "../tsconfig.json",`

Will it not make the compiler to read tsconfig.json

**Comment by nikhilnxvverma1** [comment]
It will but the ng test picks `src/tsconfig.spec.json` directly and it works inside the src directory which is not what tsconfig.json is supplying as it is giving path declarations **relative to the base directory**. The resultant path declarations are equivalent of `src/src/app/components` etc

**Comment by lgLindstrom** [comment]
Okay,,, or 
I added this to the tsconfig.spec.json 
`"@models/*": ["src/app/models/*"],`

It gave me the following ERROR.

```
ERROR in ./node_modules/conf/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\hostedProjects\desktop\kicad-component\node_modules\conf'
resolve 'fs' in 'C:\hostedProjects\desktop\kicad-component\node_modules\conf'
  Parsed request is a module
  using description file: C:\hostedProjects\desktop\kicad-component\node_modules\conf\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in C:/hostedProjects/desktop/kicad-component/
        using description file: C:\hostedProjects\desktop\kicad-component\package.json (relative path: .)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\hostedProjects\desktop\kicad-component\package.json (relative path: ./fs)
            no extension
```

**Comment by nikhilnxvverma1** [comment]
As far as the path declarations go in tsconfig.spec.json, you will have to remove the `src/` part from your `@model/*` entry

**Comment by lgLindstrom** [comment]
Hi

I am suspecting my troubles are from somwhere "not suspected"

- Downloaded a fresh template from your site
`> ng test` works.

- Added a service with relative import
`> ng test` works.

- refactored the service by adding a path to tsconfig.json
`> ng test `works.

- my code uses "electron store"
`> npm i electron-store`
`> ng test`  works

- Added a import in my service for "electron-store" and created a private object.
> `ng test` gives the following error: 
`ERROR in node_modules/conf/index.d.ts(80,53): error TS2694: Namespace 'NodeJS' has no exported member 'TypedArray'.`

According to google I need to update "@types/node"  (https://github.com/sindresorhus/conf/issues/71)

- updated @types/node
`> npm test` fails with the error above.......

```
 ERROR in ./node_modules/conf/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\hostedProjects\desktop\kicad-component\node_modules\conf'
resolve 'fs' in 'C:\hostedProjects\desktop\kicad-component\node_modules\conf'
  Parsed request is a module
  using description file: C:\hostedProjects\desktop\kicad-component\node_modules\conf\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in C:/hostedProjects/desktop/kicad-component/
```


Can I assume that something is not so good in electron-store. I cant find any solutions on google,, can you help ???

**Comment by nikhilnxvverma1** [comment]
`electron-store` (and every other dependency in this project) needs to be listed as a **dev-dependency**. You did 
`npm i electron-store`.

Remove `electron-store` as a dependency from package.json, delete node_modules, do a fresh `npm install`, then do
`npm install --save-dev electron-store`

**Comment by lgLindstrom** [comment]
Makes no difference.
Please check this example out.  
[angula-electron.zip](https://github.com/maximegris/angular-electron/files/3428193/angula-electron.zip)

- I cloned you repository.
`> npm i`
`> ng test`      OK
`> npm i --save-dev electron-store`
`> tg test `    ERROR,,, @types/node to old
 

- Updated @types/node

`> ng test ====> crashes`> ng test ====> crashes

**Comment by nikhilnxvverma1** [comment]
Whats your node version?

**Comment by lgLindstrom** [comment]
v10.15.3

**Comment by lgLindstrom** [comment]
Hi,,,   I still are struggling with this

>ng test gives the following error...



`ERROR in ./node_modules/conf/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\hostedProjects\desktop\kicad-component\node_modules\conf'
resolve 'fs' in 'C:\hostedProjects\desktop\kicad-component\node_modules\conf'
  Parsed request is a module
  using description file: C:\hostedProjects\desktop\kicad-component\node_modules\conf\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in C:/hostedProjects/desktop/kicad-component/
        using description file: C:\hostedProjects\desktop\kicad-component\package.json (relative path: .)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\hostedProjects\desktop\kicad-component\package.json (relative path: ./fs)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\hostedProjects\desktop\kicad-component\fs doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\hostedProjects\desktop\kicad-component\fs.ts doesn't exist`

**Comment by brucebrit** [comment]
> Hi,,, I still are struggling with this
> 
> > ng test gives the following error...
> 
> `ERROR in ./node_modules/conf/index.js Module not found: Error: Can't resolve 'fs' in 'C:\hostedProjects\desktop\kicad-component\node_modules\conf' resolve 'fs' in 'C:\hostedProjects\desktop\kicad-component\node_modules\conf' Parsed request is a module using description file: C:\hostedProjects\desktop\kicad-component\node_modules\conf\package.json (relative path: .) Field 'browser' doesn't contain a valid alias configuration resolve as module looking for modules in C:/hostedProjects/desktop/kicad-component/ using description file: C:\hostedProjects\desktop\kicad-component\package.json (relative path: .) Field 'browser' doesn't contain a valid alias configuration using description file: C:\hostedProjects\desktop\kicad-component\package.json (relative path: ./fs) no extension Field 'browser' doesn't contain a valid alias configuration C:\hostedProjects\desktop\kicad-component\fs doesn't exist .ts Field 'browser' doesn't contain a valid alias configuration C:\hostedProjects\desktop\kicad-component\fs.ts doesn't exist`

I also encounter the same thing. Any idea for the fix?

**Comment by lgLindstrom** [comment]
No.. :(


/mvh
/lg
_____________________________________________________
Lars-Göran Lindström
Consius AB
+46 70 190 23 30
lg.lindstrom@consius.se


Den ons 30 okt. 2019 kl 15:43 skrev brucebrit <notifications@github.com>:

**Comment by Rajdeep97** [comment]
Did you find a solution @lgLindstrom ? 
@maximegris This is a big problem some, including me are facing, can you please have a look at this?

**Comment by lgLindstrom** [comment]
Cant help you
