### ISSUE TITLE
Angular Electron Desktop App Do Not Persist data in SQLite3 Database when App is Closed.

### ISSUE THREAD

**Issue by astroame** [maximegris/angular-electron#366]
I am using SQLITE3 in my angular8-electron5 desktop app to store user login credentials so that when next they launch the app, they do not have to login, their login details will be retrieve from SQLite Database.

It works as expected during development, but when i build the` .exe` file and run the app, it does not persist login credentials once the app is closed.
Below is my SQLite database connection credentials and my `.sqlite3` file.

```
  const connection = await createConnection({
    type: 'sqlite',
    synchronize: true,
    logging: true,
    logger: 'simple-console',
    database: './typeormmodels/data/database.sqlite3',
    entities: [User, Usertoken, Usersession],
  });
```

Please help, i want the app to persist data even after it has been closed, this way users can use it offline without internet.

**Comment by nikhilnxvverma1** [comment]
To me, it seems like the database isn't being embedded correctly. Its probably getting recreated in the production build at each run. May I suggest switching to a NeDB if feasible.

**Comment by astroame** [comment]
I've never used NeDB. Is it reliable and can I use it with Typeorm? I will also appreciate any resources to get started.

**Comment by nikhilnxvverma1** [comment]
NeDB supports a subset of features MongoDB does. Personally, I haven't used it but its promising (>10000 GitHub stars). Its intended use is very much for the sake of persisting data internally within an application's binary. I am not sure if it's compatible with TypeORM though. But, I am pretty sure Sqlite is embeddable too, there is probably something wrong with your config. 

Nice to know you are using an ORM. FWIW, I found this [article](https://www.techiediaries.com/electron-data-persistence/) useful for electron specific database comparisons.

**Comment by JonathanTurnock** [comment]
Just a thought but it sounds as though the dB is recreated or your transaction is not being committed and therefore dB changes are rolled back.

**Comment by twohappy** [comment]
@astroame take a look at the path when running in production. something like this should work:
```typescript
if(environment.production){
            this.dataSubFolder = '/';
            Settings.appPath = remote.app.getPath('userData');
        } else {
            // return folder where app is running
            this.dataSubFolder = 'dist/assets/data';
            Settings.appPath = remote.app.getAppPath();
        }
```

**Comment by astroame** [comment]
I got this working by referencing my database file like this:

```
let fileName = 'database.sqlite3';
let dbpat = `${process.env.NODE_ENV === 'dev' ? `./typeormmodels/data/${fileName}` : app.getPath('userData')}/data/${fileName}`;

  const connection = await createConnection({
    type: 'sqlite',
    synchronize: true,
    logging: true,
    logger: 'simple-console',
    database: `${dbpat}`, 
    entities: [User, Usertoken, Usersession],
  });

```

**Comment by rasyidialwee** [comment]
@astroame hello, i am having the same problem and followed your solution but cant solve it. can you help me?

**Comment by astroame** [comment]
> @astroame hello, i am having the same problem and followed your solution but cant solve it. can you help me?

I'll be glad to help, can you give more details of your source code so I can figure out the issue.

**Comment by rasyidialwee** [comment]
> > @astroame hello, i am having the same problem and followed your solution but cant solve it. can you help me?
> 
> I'll be glad to help, can you give more details of your source code so I can figure out the issue.

Sorry for the late reply, i manage to solve the problem by giving pull path to my apps
``${process.env.NODE_ENV === 'dev' ? `.src/assets/data/database.sqlite` : app.getPath('userData')}/data/database.sqlite`;`
