### ISSUE TITLE
npm start stuck

### ISSUE THREAD

**Issue by shinhwap** [maximegris/angular-electron#369]
Hello,
I'm using angular-electron in ubuntu 18.04, node version 8.16.0, npm version 6.4.1

I can run the npm script  "electron:local"  "electron:linux" and so on
But when I try npm start
![Screenshot from 2019-08-02 15-18-33](https://user-images.githubusercontent.com/22389401/62351725-f08bca80-b538-11e9-8484-cf6fc1f058f5.png)
It will stuck at Compiled successfully
I used wait-on -v to watch the child process
I found http-get://localhost:4200/ will get 503 error 
![Screenshot from 2019-08-02 15-20-51](https://user-images.githubusercontent.com/22389401/62351856-4bbdbd00-b539-11e9-88d4-f7de43add29f.png)
even if Compiled successfully

I can run npm start in windows system with the same project
It will get 999 first, but after complied successfully, it will become 200
![2](https://user-images.githubusercontent.com/22389401/62352224-36955e00-b53a-11e9-9135-2ae36f8ff6e5.JPG)
![1](https://user-images.githubusercontent.com/22389401/62352228-3a28e500-b53a-11e9-9183-74ddbf15165a.JPG)

What's the problem about this?

**Comment by namdien177** [comment]
Facing the same issue.

The interesting thing is, I could run it first, but after closing and restarting `npm start` again, it was frozen. No error output either (same behaviour as yours).

Before that I was messing around with Angular at initialize components, I will investigate this but if you have anything please share 🤙

**Comment by namdien177** [comment]
interesting enough, I downgraded my electronJS version to `5.0.2` since I start facing this error ever since upgrade *manually* to v6 and you guess it...it works!

well... I guess I will be stuck with this then...
