### ISSUE TITLE
[suggested improvement] use node os for arch/platform

### ISSUE THREAD

**Issue by theneverstill** [maximegris/angular-electron#37]
Consider using node os for arch/platform:

```
const os = require('os');
const arch = os.arch();
const platform = os.platform();
```

This way you won't need separate package.json commands for each platform/arch (especially considering electron may not build correctly for any platform/arch outside of the one running the build).

**Comment by theneverstill** [comment]
Also could use process.arch and process.platform...

**Comment by maximegris** [comment]
Feel free to make a pull request on the project. :)

**Comment by socialcode-rob1** [comment]
after updating from previous starting point (ng4) to latest (ng5) my process.platform is now returning 'undefined'.
