### ISSUE TITLE
Use Cypress to e2e test Angular Electron applications

### ISSUE THREAD

**Issue by FrancescoBorzi** [maximegris/angular-electron#373]
[Cypress](https://www.cypress.io/) is currently [working on adding the support for Electron](https://github.com/cypress-io/cypress/issues/4964) and there is already a demo available:

https://github.com/cypress-io/cypress-example-electron

it would be nice if we can configure Cypress as e2e test framework in this repo

**Comment by FrancescoBorzi** [comment]
the issue is still valid

**Comment by FrancescoBorzi** [comment]
https://www.cypress.io/blog/2019/09/26/testing-electron-js-applications-using-cypress-alpha-release/

**Comment by FrancescoBorzi** [comment]
still valid

**Comment by FrancescoBorzi** [comment]
still valid

**Comment by FrancescoBorzi** [comment]
still valid

**Comment by FrancescoBorzi** [comment]
@maximegris can you make it stop?

**Comment by FrancescoBorzi** [comment]
@maximegris

**Comment by WanielDeiss** [comment]
Hey @FrancescoBorzi,
I think is a good first step when you explain why you would like to have cypress. 
Step two: Create a pull-request with your solution.
This is still an open-source project and maintainers needs always help from the community :)
greetings dan

**Comment by FrancescoBorzi** [comment]
@WanielDeiss of course, but first I'd need to know if such a feature would be accepted

**Comment by WanielDeiss** [comment]
maybe the decision is easier for the maintainer when you explain your need.
that is a typically approach when i would like to realize a feature in our product and sell the idea to my product owner.
currently you say: hey! lets use cypress, because reasons.

**Comment by vladimiry** [comment]
As far as I understand Cypress only supports testing the stuff in the web/renderer context. But Electron is more than that. For example, https://github.com/electron-userland/spectron out-of-the-box allows accessing and verifying stuff in the main process too.
