### ISSUE TITLE
*.js/*.js.map no longer generated

### ISSUE THREAD

**Issue by lgLindstrom** [maximegris/angular-electron#382]
Hi
I upgraded angular from 8.0 to 8.2.  Suddenly debugging in chrome debugger stopped working. Searching for the problem I noticed that *.js and *.js.map files no longer is generated. 

Unfortunately I can't understand why. Can anyone point me in correct direction?

**Comment by lgLindstrom** [comment]
Getting frustrated,,,
I cloned latest angular-electron project, installed and tried to debug in chrome debugger. No luck. Same problem that I have spelled out in this thread,,, 

PLEASE help.

**Comment by greg9504** [comment]
Have you verified if "sourceMap": true in tsconfig.json and tsconfig-serve.json?

Can you post the contents of your launch.json file found in the .vscode directory?

**Comment by lgLindstrom** [comment]
ahhh,, now it works. Probably a mistake from my side  ... sorry for inconvenience

**Comment by greg9504** [comment]
@lgLindstrom  Mind posting the launch configuration you are using for debugging?  
Thanks.

**Comment by lgLindstrom** [comment]
Suddenly everythings works. It must have been my mistake.
So sorry for the inconvenience.
