### ISSUE TITLE
I always got error when execute "npm start"

### ISSUE THREAD

**Issue by ubbox** [maximegris/angular-electron#383]
As below error message, I got error message when execute 'npm start'.
I saw same issue, so I try to change node version that solver suggest.
But I also got same error.
I try to change following node version:
- node/10.16.0
  node/11.10.0
  node/12.4.0
  node/12.7.0
  node/12.9.1

Please suggest and share some solution.
Thanks,

-------------------------------------------------------------------------------------------------------------
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-electron@6.1.0 electron:serve: `wait-on http-get://localhost:4200/ && npm run electron:serve-tsc && electron . --serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-electron@6.1.0 electron:serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/intoara/.npm/_logs/2019-08-30T07_53_06_083Z-debug.log
ERROR: "electron:serve" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-electron@6.1.0 start: `npm run postinstall:electron && npm-run-all -p ng:serve electron:serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-electron@6.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/intoara/.npm/_logs/2019-08-30T07_53_06_154Z-debug.log

**Comment by Leonardonline** [comment]
If you change node version you need to re-install all packages.

**Comment by ubbox** [comment]
> If you change node version you need to re-install all packages.

I already removed node_modules directory, and re-install all package after changing node version.
But I got same error message. 
I don't know what is problem for this error. Is there any clue or solution ?

**Comment by ubbox** [comment]
I mistake for my development environment.
I have currently built electron in remote ubuntu server, so "electron ." command not working in my environment. So I remove "electron:serve" in "start" script. 
Sorry for silly question.

**Comment by DieserMerlin** [comment]
I'm on Windows 10 64 bit and get this error with 'npm start':

> internal/child_process.js:366
>     throw errnoException(err, 'spawn');
>     ^
> 
> Error: spawn EPERM
>     at ChildProcess.spawn (internal/child_process.js:366:11)
>     at Object.spawn (child_process.js:551:9)
>     at Object.<anonymous> (C:\Users\email\WebstormProjects\angular-electron\node_modules\electron\cli.js:7:18)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
>     at startup (internal/bootstrap/node.js:283:19)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! angular-electron@6.1.0 electron:serve: `wait-on http-get://localhost:4200/ && npm run electron:serve-tsc && electron . --serve`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the angular-electron@6.1.0 electron:serve script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\email\AppData\Roaming\npm-cache\_logs\2019-09-13T10_48_24_676Z-debug.log
ERROR: "electron:serve" exited with 1.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! angular-electron@6.1.0 start: `npm run postinstall:electron && npm-run-all -p ng:serve electron:serve`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the angular-electron@6.1.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\email\AppData\Roaming\npm-cache\_logs\2019-09-13T10_48_24_916Z-debug.log

I tried deleting package.lock.json and node_modules and reinstalling the dependencies. I also reinstalled npm, tried using yarn and I tried using a completely fresh windows installation.

Does anyone know what to do?

**Comment by DieserMerlin** [comment]
I tried it on 2 other windows 10 environments but it just doesn't start. I went back to https://github.com/maximegris/angular-electron/commit/fb719ab6f8d8fd47c5a8be0bfaa5ca89363d26cd which works fine
