### ISSUE TITLE
Build size is very huge for small app

### ISSUE THREAD

**Issue by vijhhh2** [maximegris/angular-electron#386]
Build size of my app is exceeding 1Gb for a simple app with 2 pages. Is there any way to decrease app size. I have moved all my dependencies to dev dependencies.

**Comment by yosvield** [comment]
Check you do not have in the app directory, you have put some folder, file, because when compiling can be included

**Comment by Leonardonline** [comment]
Add in your file `electron-builder.json` all the files and directories you want to exclude.
To exclude a file just add a "!" before the name.

**Comment by vijhhh2** [comment]
Then also I am getting the app size of 184 MB. Is there any way to reduce to 50 MB.
