### ISSUE TITLE
Error: Requires Constructor Call in extended class

### ISSUE THREAD

**Issue by txtcbenne** [maximegris/angular-electron#388]
I have a couple of custom .ts files that I'm importing into main.ts. One of those files is a class that extends electron's BrowserWindow. However, when I run the entire application after tsc is finished, I receive 'Error: Requires constructor call at new AppWindow'.

The relevant code in srcElectron/AppWindow.ts:
```
import { BrowserWindow } from 'electron';

export class AppWindow extends BrowserWindow {
    public constructor() {
        super({
            webPreferences: {
                nodeIntegration: true
            },
            minWidth: 400,
            minHeight: 450,
            width: 900,
            height: 700,
            show: true,
            titleBarStyle: 'hiddenInset',
            title: 'App Title'
        });
        this.setMenu(null);
    }
}
```

And in main.ts:
```
import { AppWindow } from './srcElectron/app-window'
// ...

win = new AppWindow();
```

My tsconfig.json and tsconfig-serve.json are unchanged.

**Comment by Tobjoern** [comment]
Can you submit a full reproduction?

**Comment by txtcbenne** [comment]
I've created a repository that showcases the error. I run 'npm install' then 'npm start' and the error occurs.
https://github.com/txtcbenne/angular-electron
As you can see, all I've added is an extended class.

**Comment by txtcbenne** [comment]
After a bit of looking around, I found that this was a configuration issue. In the tsconfig and tsconfig-serve files, I had to set "target": "es6" (which allows extension of classes) and the "module": "commonjs". Marking this as closed.
