### ISSUE TITLE
Compiling OK, but Angular doesn't render changes

### ISSUE THREAD

**Issue by aletaschner** [maximegris/angular-electron#391]
I'm a little bit confused by a simple test I've made and it seems like Angular doesn't render changes on the screen. I have made a simple code to show.

On home.component.ts
``` typescript
loaded = false;
  ngOnInit() {
    this.electron.ipcRenderer.send('started', true);
    this.electron.ipcRenderer.on('loaded', (e) => {
      console.log('received "loaded" from main');
      this.loaded = true;
      window.setTimeout(() => console.log(this.loaded), 2000);
    });
  }
```
home.component.html
``` html
<div class="container" *ngIf="loaded">
  <h1 class="title">
    {{ 'PAGES.HOME.TITLE' | translate }}
  </h1>
</div>
<div *ngIf="!loaded" class="container">
  <h1 class="title">
    Loading...
  </h1>
</div>
```

main.ts (inside createWindow function)
``` typescript
ipcMain.on('started', (e) => {
    console.log('received "started" from window');
    setTimeout(() => {
      console.log('few seconds later, sendind loaded to window');
      win.send('loaded', ":D");
    }, 3000);
  });
```

Even when checking the logs, everything seems to work out great:
node console:
![image](https://user-images.githubusercontent.com/15621127/65509498-fce13380-dea8-11e9-98d0-4edce9816833.png)
dev tools console:
![image](https://user-images.githubusercontent.com/15621127/65509528-0f5b6d00-dea9-11e9-85d1-7c6a62997c98.png)

Yet, what I get on screen is the "loading..." text and it does not refresh.

Am I doing something wrong?

Thanks in advance!

**Comment by txtcbenne** [comment]
I've had this issue before as well. I solved it by injecting ChangeDetectorRef and detecting the changes after the data was changed. In your case:

```
  loaded = false;
  constructor(private electronService: ElectronService, private change: ChangeDetectorRef) { }
  ngOnInit() {
    this.electron.ipcRenderer.send('started', true);
    this.electron.ipcRenderer.on('loaded', (e) => {
      console.log('received "loaded" from main');
      this.loaded = true;
      this.change.detectChanges()
      window.setTimeout(() => console.log(this.loaded), 2000);
    });
  }
```

**Comment by aletaschner** [comment]
Great! This actually worked. Thank you very much.

Althought it would be great to know why it doesn't simply work, this already helps me a lot!
