### ISSUE TITLE
pixijs component not rendered in dev mode

### ISSUE THREAD

**Issue by nphias** [maximegris/angular-electron#392]
all works fine except for my pixi.js (webgl) module..
post built it works fine and is rendered (electron & electron.local)
but in start mode (hot reload).. i see nothing
I guess that i need to do some custom webpack configuration to be able to render pixi in electron-reload / serve mode?...  where is the webpack.config file?
it could be that i need to use ChangeDetectorRef as in the other issue about things being compiled and not being rendered. (https://github.com/maximegris/angular-electron/issues/391#issue-497641719)
also to note i am using ngzone.runOutsideAngular for pixi (if that makes any difference)
and all my modules are in devDependencies.

**Comment by CCourbet** [comment]
Same issue here with another module, did you find a solution?
Thanks

**Comment by nphias** [comment]
> Same issue here with another module, did you find a solution?
> Thanks

yes found another repo for electron-angular-webpack    ...  works well for dev testing  
https://github.com/lbassin/electron-angular-webpack
(its updated to ng 8)

**Comment by CCourbet** [comment]
Thanks !
