### ISSUE TITLE
Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by Crazie-ash** [maximegris/angular-electron#394]
<--- Last few GCs --->

[6148:000002303255CC60]   216692 ms: Mark-sweep 1323.3 (1427.4) -> 1323.0 (1427.4) MB, 734.9 / 0.0 ms  (average mu = 0.077, current mu = 0.008) allocation failure scavenge might not succeed
[6148:000002303255CC60]   217351 ms: Mark-sweep 1323.1 (1427.4) -> 1323.0 (1427.9) MB, 656.1 / 0.0 ms  (average mu = 0.040, current mu = 0.004) allocation failure GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0000033850BDC5C1]
    1: StubFrame [pc: 0000033850B8D64B]
    2: ConstructFrame [pc: 0000033850B8D1E3]
    3: StubFrame [pc: 0000033850C09DFD]
Security context: 0x01d67c01e6e9 <JSObject>
    4: __referencing [00000265847BD469] [D:\Fuse-electron\backup 28\node_modules\eslint-scope\lib\scope.js:437] [bytecode=000000A64FFA4189 offset=91](this=0x01372542a149 <Scope map = 0000001048B501D1>,node=0x02d9483c9dc9 <Node map = ...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6F7A7C6AA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
 2: 00007FF6F7A57416 node::MakeCallback+4534
 3: 00007FF6F7A57D90 node_module_register+2032
 4: 00007FF6F7D7189E v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF6F7D717CF v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF6F7F57F94 v8::internal::Heap::MaxHeapGrowingFactor+9620
 7: 00007FF6F7F4EF76 v8::internal::ScavengeJob::operator=+24550
 8: 00007FF6F7F4D5CC v8::internal::ScavengeJob::operator=+17980
 9: 00007FF6F7F56317 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF6F7F56396 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF6F8080637 v8::internal::Factory::NewFillerObject+55
12: 00007FF6F80FD826 v8::internal::operator<<+73494
13: 0000033850BDC5C1
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! fuse@8.0.0 build: `npm run postinstall:electron && npm run electron:serve-tsc && ng build "-c" "production"`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the fuse@8.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2019-09-28T06_37_09_130Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! fuse@8.0.0 build:prod: `npm run build -- -c production`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the fuse@8.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Crazie-ash** [comment]
I tried injecting electron in Angular 8 fuse theme's skeleton.... The app was running fine... but while building the app it shows the above error.

I also tried changing the memory limit to 8048, but not resolved.

I'm using windows 10. Kindly help me out resolving it

**Comment by jakehockey10** [comment]
@Crazie-ash Did you figure this out?  I'm running into this issue as well
