### ISSUE TITLE
 require is not defined

### ISSUE THREAD

**Issue by zombodotcom** [maximegris/angular-electron#395]
![image](https://user-images.githubusercontent.com/13477955/65846177-c749a980-e2f1-11e9-934e-d0885e730155.png)
```
Uncaught ReferenceError: require is not defined
    at Object.url (index.js:36)
    at __webpack_require__ (bootstrap:726)
    at fn (bootstrap:100)
    at Object../node_modules/webpack-dev-server/client/utils/createSocketUrl.js (createSocketUrl.js:4)
```

**Comment by zombodotcom** [comment]
Trying to fix 

https://github.com/currency-cop/currency-cop

**Comment by cheplv** [comment]
I'v found that this issue produced by postinstall switching between envs (electron/web). Need to switch to @angular-builders/custom-webpack - will add pull request next week

**Comment by Brandon9598** [comment]
@zombodotcom What version of Electron were you using? Also, have you figured out a fix?

**Comment by cheplv** [comment]
Will try give commit today. It's quite simple ))

**Comment by cheplv** [comment]
@zombodotcom @Brandon9598 @maximegris 
Did a simple change with custom-webpack module.
This correctly builds for electron-renderer and web targets

**Comment by zombodotcom** [comment]
thanks, i forgot I posted this. I got a lot further on my app. Thanks <3

**Comment by uzumakinaruto123** [comment]
I am still getting this! Pulled the latest master

```
external "url":1 Uncaught ReferenceError: require is not defined
    at Object.url (external "url":1)
    at __webpack_require__ (bootstrap:79)
    at Object../node_modules/webpack-dev-server/client/utils/createSocketUrl.js (createSocketUrl.js:4)
    at __webpack_require__ (bootstrap:79)
    at Object.<anonymous> (client:20)
    at Object../node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:0/sockjs-node&sockPath=/sockjs-node (vendor.0e7e1a4672132539a6d0.js:375324)
    at __webpack_require__ (bootstrap:79)
    at Object.0 (main.ts:18)
    at __webpack_require__ (bootstrap:79)
    at checkDeferredModules (bootstrap:45)
```

main.ts: 18
```

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));
```

**Comment by cheplv** [comment]
@maximegris Need to reopen ticket - I'v found another one thing that needs to be added.
electron security issue - today i has found this and fixed - but not commited
@uzumakinaruto123 just wait some days ((

**Comment by zombodotcom** [comment]
sorry i was the one who closed it. i forgot what i did to fix it, didn't realize this was such a large issue.

**Comment by cheplv** [comment]
yeah )) thx

**Comment by cheplv** [comment]
@maximegris PR that fixes security issue serving app on localhost
https://github.com/maximegris/angular-electron/pull/408

**Comment by cheplv** [comment]
@uzumakinaruto123 can you check my PR and confirm that changes solve your issue?

**Comment by cheplv** [comment]
it seems that some days ago angular devs added support for custom webpack configuration:
https://github.com/angular/angular-cli/commit/9f5c0f3c510dd84739171c1da9eae88f74d666aa

**Comment by uzumakinaruto123** [comment]
I pulled your PR and apparently everything was working. I think I messed up some dependencies while merging another project into this one. 

Steps to make an existing project compatible with this one would be helpful. Like, mentioning minimum dependencies and their versions. 

I tried merging https://github.com/akveo/ngx-admin/blob/master/package.json in angular-electron.

**Comment by cheplv** [comment]
@uzumakinaruto123 you need to merge deps of project (package.json) step by step, seems that src and e2e folder can be just copy/paste with override.
Will try to do merge ngx-admin with angular-electron - will give you a feedback.

**Comment by uzumakinaruto123** [comment]
@cheplv Thanks a lot!  I just tried it once and for the first attempt I decided to keep the latest versions of the two for common dependencies.

**Comment by ardai96** [comment]
I just clone master branch and saw this error on browser. Any news about this isuse?

**Comment by cheplv** [comment]
@ardai96 can you describe - how you get that error - step by step

**Comment by ardai96** [comment]
@cheplv 
1. Clone repository
2. npm i
3. npm start
4. Open google chrome on localhost:4200.
5. Open dev tools and have error on console.

**Comment by cheplv** [comment]
@ardai96 "npm start" is intended to use only in electron environment i.e. opening direct localhost:4200 in browser will produce "require error" due build is for electron.
Use "npm run ng:serve:web" if you want to run in browser without electron.

**Comment by fbaldo31** [comment]
Hi all,
I have currently the same issue (in electron environment) so with `npm start`

**Comment by cheplv** [comment]
@fbaldo31 how you face this error? if you used steps which mentioned in https://github.com/maximegris/angular-electron/issues/395#issuecomment-558791059 - so this is incorrect use - you need only 3 first steps - opening in localhost etc is not intended - use internal electron app dev tools

**Comment by fbaldo31** [comment]
`npm start` launch the app properly the navigator is useless.
But for unknown reason the error does not come anymore on my side

**Comment by cheplv** [comment]
@fbaldo31 ensure that you are latest master - due there was many changes in build/test process.

**Comment by fbaldo31** [comment]
I have solve my issue, probably due by moving files :/

**Comment by cheplv** [comment]
@zombodotcom @maximegris think that we can close this issue

**Comment by maximegris** [comment]
Thanks @cheplv
