### ISSUE TITLE
Style Sheets

### ISSUE THREAD

**Issue by bitmasta** [maximegris/angular-electron#4]
I've created a new style sheet named 'test.css' in the 'src' folder and I've added it to the styles array in the .angular-cli.json file but it isn't being loaded. What am I doing wrong?

**Comment by maximegris** [comment]
The easiest way is to import your test.css file  directly at the top of `styles.scss` like this :

`@import'./test.css'`

**Comment by bitmasta** [comment]
That works. Thanks!

**Comment by maximegris** [comment]
You're welcome :)
