### ISSUE TITLE
After rebuild, page not changed.

### ISSUE THREAD

**Issue by Sakuara** [maximegris/angular-electron#401]
steps:
i.  change home.component.html, replace {{ 'PAGES.HOME.TITLE' | translate}} with 'hello world'
ii.  excute npm run electron:local
finally, the page still render App works rather than 'hello world'.
compare dist/main.js and electron app's main.js, i find they are different.

**Comment by cheplv** [comment]
@Sakuara you need to run "npm start" and you will get app with hot reload
"npm electron:local" is for final check of work without hot reload and prod build

**Comment by fbaldo31** [comment]
With npm start, renderer is reloaded but not main process.

**Comment by cheplv** [comment]
@fbaldo31 think that main process no need to be changed due it's functioning only for bootstrapping. Your app has full access to node env - all changes must be done in src/.
Can you explain your task - what you want to achieve changing main.ts?
