### ISSUE TITLE
Can't bind to 'ngModel' since it isn't a known property of 'input'.

### ISSUE THREAD

**Issue by foxip** [maximegris/angular-electron#402]
If I add this to home.component.html

`<input type="text" [(ngModel)]="test" />`

And this to home.compontent.ts

`public test: string = 'hello world';`

I get the following error: Can't bind to 'ngModel' since it isn't a known property of 'input'.

How to use ngModel?

**Comment by int128fly** [comment]
Make sure to import ReactiveFormsModule in your module.

**Comment by foxip** [comment]
Thanks for your suggestion, but it still does not work, here is a copy of app.module.ts

`import 'reflect-metadata';
import '../polyfills';

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpClientModule, HttpClient } from '@angular/common/http';
import { CoreModule } from './core/core.module';
import { SharedModule } from './shared/shared.module';
import { AppRoutingModule } from './app-routing.module';

// NG Translate
import { TranslateModule, TranslateLoader } from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';

import { HomeModule } from './home/home.module';
import { AppComponent } from './app.component';

// AoT requires an exported function for factories
export function HttpLoaderFactory(http: HttpClient) {
  return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
    HttpClientModule,
    CoreModule,
    SharedModule,
    HomeModule,
    AppRoutingModule,
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: HttpLoaderFactory,
        deps: [HttpClient]
      }
    })
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {}`

**Comment by int128fly** [comment]
I really don't think that this is an issue with angular-electron or electron at all, I would suggest you to setup a new project with just this issue and share the whole project so we can offer you better help.

**Comment by maximegris** [comment]
Hi

You have to import FormsMudule in `shared.module.ts` 

```typescript
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { TranslateModule } from '@ngx-translate/core';

import { PageNotFoundComponent } from './components/';
import { WebviewDirective } from './directives/';
import { FormsModule } from '@angular/forms';

@NgModule({
  declarations: [PageNotFoundComponent, WebviewDirective],
  imports: [CommonModule, TranslateModule, FormsModule],
  exports: [TranslateModule, WebviewDirective, FormsModule]
})
export class SharedModule {}
```

**Comment by foxip** [comment]
Hi Maxim, thanks for your help, now it works.
