### ISSUE TITLE
Using jimp and native libraries

### ISSUE THREAD

**Issue by LateralKevin** [maximegris/angular-electron#406]
Thanks for all your hard work on this project.

I'm trying to understand how to use native libraries in angular and don't really understand the "correct" way to do this.

I tried adding jimp to electron.service.ts following the same pattern as child process, remote etc but this doesn't seem to work.

I can get it to work by adding it to index.html
     window.jimp = require('jimp')

but I would like to know the correct way of doing this for jimp and other native libraries.

**Comment by irustm** [comment]
I think that in electron you can not use nodejs libraries.

Try use angular in native Desktop: Angular Nodegui https://github.com/irustm/angular-nodegui

**Comment by maximegris** [comment]
Hi, 
can you share your implementation of `electron.service.ts` please ?

**Comment by maximegris** [comment]
This should works : 

```typescript
import { Injectable } from '@angular/core';

// If you import a module but never use any of the imported values other than as TypeScript types,
// the resulting javascript file will look as if you never imported the module at all.
import { ipcRenderer, webFrame, remote } from 'electron';
import * as childProcess from 'child_process';
import * as fs from 'fs';

import Jimp from 'jimp';

@Injectable({
  providedIn: 'root'
})
export class ElectronService {
  ipcRenderer: typeof ipcRenderer;
  webFrame: typeof webFrame;
  remote: typeof remote;
  childProcess: typeof childProcess;
  fs: typeof fs;
  jimp: typeof Jimp;

  get isElectron() {
    return window && window.process && window.process.type;
  }

  constructor() {
    // Conditional imports
    if (this.isElectron) {
      this.ipcRenderer = window.require('electron').ipcRenderer;
      this.webFrame = window.require('electron').webFrame;
      this.remote = window.require('electron').remote;

      this.childProcess = window.require('child_process');
      this.fs = window.require('fs');

      this.jimp = Jimp;

      // TEST
      this.jimp.read('https://picsum.photos/id/396/200/300')
        .then(image => {
          // Do stuff with the image.
          console.log('image', image);
        })
        .catch(err => {
          // Handle an exception.
          console.log('err', err);
        });
    }
  }
}
```

**Comment by LateralKevin** [comment]
Thanks for the update.

OK, I've copied your electron.service.ts code which I'm then using in an angular service

The following code works fine, reading and writing the local file system using the window jimp

```
  constructor(public es :ElectronService) {
   const Jimp = (window).jimp;
  Jimp.read('/Users/XXX/Documents/Test.JPG')
    .then( async img => {
      await  img.resize(400,300).quality(100).write('/Users/XXX/Documents/Test_preview.JPG');
    });

   }
```

If I change const Jim to use the electron service it doesn't work


```
 const Jimp = this.es.jimp;

```

The code fails initially with

```
core.js:4002 ERROR Error: Uncaught (in promise): Error: HTTP Status 404 for url 
```

So changing the read to file:// allows the file to be read from the local system but won't allow writing

```
core.js:4002 ERROR Error: Uncaught (in promise): Error: Cant access the filesystem. You can use the getBase64 method.
Error: Cant access the filesystem. You can use the getBase64 method.
    at Jimp.write (jimp.js:41175)
 ```

**Comment by cheplv** [comment]
You need to use native libs in:

**Comment by cheplv** [comment]
@LateralKevin which os you use - this can be to os security issue related

**Comment by LateralKevin** [comment]
I'm running on MacOS.

**Comment by cheplv** [comment]
@LateralKevin may be you can get me an access to your private repo to reproduce your problem?

**Comment by LateralKevin** [comment]
The code above should reproduce the problem, the issue is the line

```
const Jimp = (window).jimp;  // This works as it uses the reference from index.html window.jimp = require('jimp')
const Jimp = this.es.jimp; // This fails as it uses the reference from ElectronService

```

**Comment by cheplv** [comment]
@LateralKevin ok - will try to repro this thing with clean master in 2-3 days seems that this is some kind of behaviour

**Comment by cheplv** [comment]
@LateralKevin I'v added some code as an example of jimp use into my branch.
Please check and give some feedback: https://github.com/cheplv/angular-electron/tree/jimp-native-library
