### ISSUE TITLE
npm run test fails with "Can't resolve 'fs'"

### ISSUE THREAD

**Issue by brucebrit** [maximegris/angular-electron#409]
Version of maximegris/angular-electron: Latest as of 15 nov 2019

Using this framework, i just only barely start developing my application, when I encounter this error upon executing npm run test. 
Is some configuration or libs missing in this framework resulting in this error?

Below is a service class generated using Angular CLI

```typescript
import { Injectable } from '@angular/core';
import * as crypto from 'crypto'
import * as fs from 'fs'

@Injectable({
  providedIn: 'root'
})
export class FileIntegrityService{

  constructor() { }

  getCheckSum_MD5(filePath: string, cbFn:(string)=>void){
      let hash = crypto.createHash('md5')
      let s = fs.createReadStream(filePath)
      s.on ('data', (data)=>{
        hash.update(data)
      })

      s.on ('end', ()=>{
        let checksum = hash.digest('hex')
        cbFn(checksum)
      })
    
      s.on ('error', (err)=>{
        throw err
      })
  }
```

on top of the jasmine file generated by Angular Cli, i merely add the below
```javascript
import { TestBed } from '@angular/core/testing';

import { FileIntegrityService} from './file-integrity-service';

describe('FileIntegrityServiceService', () => {
  beforeEach(() => TestBed.configureTestingModule({
   
  }));

 /**Below is what I add*/
  it('non-existent file should throw error 1', () => {
    let service = new FileIntegrityService()
    expect(service.getCheckSum_MD5("non-existent.txt", undefined)).toThrow();
  });
```

**Comment by cheplv** [comment]
@brucebrit this happens is due testing now is processed in web env - so node modules is not available in that env.

**Comment by brucebrit** [comment]
> @brucebrit this happens is due testing now is processed in web env - so node modules is not available in that env.

Thanks. Any resolution for this? 

If there is resolution for this, perhaps the maximegris/angular-electron could consider include the resolution fix.  So that developer using this framework do not have to worry for this issue anymore.

**Comment by cheplv** [comment]
@brucebrit what I see as a solution is just switch from jasmine testing to jest with jsdom.
Seems that in this request also problem is same: https://github.com/maximegris/angular-electron/issues/348

**Comment by cheplv** [comment]
@brucebrit find out problem - will try to add PR tomorrow - i'v got working proto with karma in electron env

**Comment by cheplv** [comment]
Check PR: https://github.com/maximegris/angular-electron/pull/411

**Comment by brucebrit** [comment]
> @brucebrit Check PR: #411
> Hope this is a correct solution

Ok. Thanks! By the way what does PR stands for ?

In the changes u made below, i assume all those changes u made for those non-eslint related should be the resolution to the issue I encounter. If yes, I can try to apply your changes to my own codes, and test it out.
![image](https://user-images.githubusercontent.com/55586134/69148060-65960680-0b0e-11ea-921d-60249771eee7.png)

**Comment by cheplv** [comment]
@brucebrit that changes change behaviour of karma testing to native karma-electron - so your tests shoud run on latest from master

**Comment by brucebrit** [comment]
> @brucebrit that changes change behaviour of karma testing to native karma-electron - so your tests shoud run on latest from master.
> Please check and if all things are good - think that this ticket can be closed ))

Perfect! Its working. No longer encounter the issue. Thanks!
