### ISSUE TITLE
Cannot find module 'html-webpack-plugin'

### ISSUE THREAD

**Issue by nanhapy** [maximegris/angular-electron#41]
I got an error 'Cannot find module 'html-webpack-plugin', when i enter `npm start`

 angular-electron@1.5.0 start D:\xhhm\desktop
  webpack --watch

module.js:471
    throw err;
    ^

Error: Cannot find module 'html-webpack-plugin'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\xhhm\desktop\webpack.config.js:4:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-electron@1.5.0 start: `webpack --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-electron@1.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lerry\AppData\Roaming\npm-cache\_logs\2017-07-07T03_34_16_751Z-debug.log

Here's the `2017-07-07T03_34_16_751Z-debug.log`:
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\lerry\\AppData\\Roaming\\npm\\node_modules\\.npm_npminstall\\npm\\5.1.0\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.1.0
3 info using node@v6.11.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular-electron@1.5.0~prestart: angular-electron@1.5.0
6 info lifecycle angular-electron@1.5.0~start: angular-electron@1.5.0
7 verbose lifecycle angular-electron@1.5.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle angular-electron@1.5.0~start: PATH: C:\Users\lerry\AppData\Roaming\npm\node_modules\.npm_npminstall\npm\5.1.0\npm\bin\node-gyp-bin;D:\xhhm\desktop\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\tools\ruby22\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\80\Tools\Binn\;C:\Program Files\Microsoft SQL Server\90\DTS\Binn\;C:\Program Files\Microsoft SQL Server\90\Tools\binn\;C:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C:\Program Files (x86)\Microsoft SQL Server\90\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\90\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE\PrivateAssemblies\;D:\Program Files\TortoiseSVN\bin;d:\Program Files\Git\cmd;C:\Program Files (x86)\Java\jdk1.7.0_55\bin;D:\Android\android-sdk\tools;D:\Android\android-sdk\platform-tools;C:\Users\lerry\AppData\Roaming\npm;C:\ProgramData\chocolatey\bin;C:/git-tf;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\dotnet\;D:\Program Files\nodejs\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Users\lerry\.dnx\bin;D:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\lerry\AppData\Local\Microsoft\WindowsApps;C:\Users\lerry\AppData\Roaming\npm;
9 verbose lifecycle angular-electron@1.5.0~start: CWD: D:\xhhm\desktop
10 silly lifecycle angular-electron@1.5.0~start: Args: [ '/d /s /c', 'webpack --watch' ]
11 silly lifecycle angular-electron@1.5.0~start: Returned: code: 1  signal: null
12 info lifecycle angular-electron@1.5.0~start: Failed to exec start script
13 verbose stack Error: angular-electron@1.5.0 start: `webpack --watch`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\lerry\AppData\Roaming\npm\node_modules\.npm_npminstall\npm\5.1.0\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\lerry\AppData\Roaming\npm\node_modules\.npm_npminstall\npm\5.1.0\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:891:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid angular-electron@1.5.0
15 verbose cwd D:\xhhm\desktop
16 verbose Windows_NT 10.0.15063
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lerry\\AppData\\Roaming\\npm\\node_modules\\.npm_npminstall\\npm\\5.1.0\\npm\\bin\\npm-cli.js" "start"
18 verbose node v6.11.0
19 verbose npm  v5.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error angular-electron@1.5.0 start: `webpack --watch`
22 error Exit status 1
23 error Failed at the angular-electron@1.5.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Epsil0neR** [comment]
You just like. You missed command:
npm install

**Comment by maximegris** [comment]
I close this issue :)
