### ISSUE TITLE
Template parse errors: 'webview' is not a known element

### ISSUE THREAD

**Issue by cyluxx** [maximegris/angular-electron#412]
Hello,
I am trying to use the webview, but it does not seem to work.

### Steps to Reproduce
1. clone repository
2. `npm i`
3. add `webviewTag: true` to _BrowserWindow_ in the _main.ts_ file as described [here](https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md#new-browserwindow-webpreferences-)
4. append `<webview src="https://www.github.com/"></webview>` to _home.component.html_
5. `npm start`

Then I receive the following error:
```
Uncaught Error: Template parse errors:
'webview' is not a known element:
1. If 'webview' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
```

### What I've tried so far
After some investigation I found out that the selector of the _WebviewDirective_ is declared as an  [attribute directive](https://angular.io/guide/attribute-directives). Is this intended? Is there a reason for that?

### Appendix:
Related to #332

**Comment by maximegris** [comment]
I don't think so. 

Good catch 👍
