### ISSUE TITLE
How can I add v8 compile cache in the entry module

### ISSUE THREAD

**Issue by didiokener** [maximegris/angular-electron#414]
Hi, it is not an issue actually. I am trying to figure out how I can add the package v8-compile-cache [https://www.npmjs.com/package/v8-compile-cache](url), in its documentation only says to add require('v8-compile-cache'); in your entry module. Is there a way to add it in this amazing project? How can I do this? Thanks for listening my doubt.

**Comment by cheplv** [comment]
@didiokener it's not intended to use in electron app, but for apps that run on prod to speedup launch. Packages electron are packed itself in 1 file (asar) so there is no benefit of using this module.
But if you want to test this module with electron:
1) npm i --save v8-compile-cache
2) add first line in main.ts: require('v8-compile-cache');

**Comment by didiokener** [comment]
Ok Thanks, I will follow your lead  👍
