### ISSUE TITLE
weird rendering issues when using window.unmaximize or window.restore

### ISSUE THREAD

**Issue by jakehockey10** [maximegris/angular-electron#415]
I have an issue where I removed the file menu and made the window frameless:

```typescript
...

  // Create the browser window.
  win = new BrowserWindow({
    x: 0,
    y: 0,
    width: size.width,
    height: size.height,
    webPreferences: {
      nodeIntegration: true,
      allowRunningInsecureContent: serve ? true : false
    },
    frame: false
  });

...

  if (serve) {
    win.webContents.openDevTools();
  }

  win.webContents.once("did-finish-load", () => {
    win.setMenuBarVisibility(false);
  });

...
```
I am attempting to have my app header control window resize and window position by double clicking and dragging:

```html
<!-- app.component.html -->
<clr-main-container>
  <clr-header (dblclick)="headerDblClicked($event)"
              style="-webkit-app-region: drag">
...
```
```typescript
  // app.component.ts
  headerDblClicked(event) {
    const window = this.electronService.remote.getCurrentWindow();
    window.isMaximized() ? window.unmaximize() : window.maximize();
  }
```
The following gif shows the issue I'm seeing:
![Peek 2019-12-01 19-26](https://user-images.githubusercontent.com/1821383/69926496-f0adbf80-1471-11ea-8b03-c8324dcb9eea.gif)

Basically, after the window is `unmaximized`, there seems to be a rendering issue.  I can usually get the rendering issue to "go away" by interacting with the inside of the window some how (in the gif, I'm double clicking the second header that is showing).

I've tried using `NgZone` to run the `headerDblClicked` body inside the angular zone and outside of angular.  I've tried using the `ChangeDetectorRef` to `detectChanges` in the `'resize'` event of the `window`.  I've tried running `window.reload()` on the `'resize'` event of the `window`.  I can't think of what else to try.

I'm not sure if this is an angular problem, and electron problem, or what.  I couldn't find anything related to this in my google searches for angular and electron individually.  I ultimately decided to open the ticket here because I'm using the `ElectronService` in a clone of this repository, and I was wondering if this was an angular & electron problem.

**Comment by jakehockey10** [comment]
If it helps any, this issue does not occur if the DevTools are open (either attached or detached)

**Comment by cheplv** [comment]
@jakehockey10 Seems your problem is related to https://github.com/electron/electron/issues/13193,https://github.com/electron/electron/issues/12971
Think that this custom solution can fix prob: https://github.com/electron/electron/issues/12971#issuecomment-403956396

And it's windows platform affected: https://github.com/Microsoft/vscode/issues/52265#issuecomment-410531924

**Comment by jakehockey10** [comment]
@cheplv Thanks for the response.  Sorry it took so long for me to respond.

It kind of seems related in a way.  Unfortunately, the custom solution you mentioned seemed to only make it not happen 100% of the time.  But it still happens a majority of the time.  I've been playing around with the time passed into the `setTimeout` function, but I still can't get it to avoid doing this all the time.

I'm running this on linux at the moment and have not tried any other operating systems quite yet.

I also tried the `thickFrame: true` options, but it didn't seem to make a difference :(

Thanks for the suggestions!  Hopefully I can find a solution to this!

**Comment by jakehockey10** [comment]
This is still an issue for me. Can I "unstale" this issue?

**Comment by nikhilnxvverma1** [comment]
jake is right, please unstale the issue ASAP
