### ISSUE TITLE
Internal backend in separate thread

### ISSUE THREAD

**Issue by khwerhahn** [maximegris/angular-electron#419]
Hi, I'm a little new to Electron and need to figure out how I can create a "local backend api" to do some background work such as data polling and then communicating with the frontend via classical angular services. 

An example would be something similar to[ this .NET example](https://scotch.io/@rui/how-to-build-a-cross-platform-desktop-application-with-electron-and-net-core), but the "node way".

Is it possible for example to run an "express" backend in a seperated thread?

**Comment by santino83** [comment]
When you starts electron in main.ts, you should starts your backend api, eg express webserver. Depends on your need, you could start electron without regards on expressjs status

**Comment by Css-IanM** [comment]
I'm not certain that express runs in its own thread, i think it's just asynchronous by design, as in it doesn't block the event loop. You would have to use the node [process](https://nodejs.org/dist/latest-v12.x/docs/api/child_process.html) API to actually put it in its own thread.
