### ISSUE TITLE
not work with mysql

### ISSUE THREAD

**Issue by gassyou** [maximegris/angular-electron#423]
hi

i want add connect mysql feature base on your code.
it work fine when i run `npm rum start`.

but when i want build a windows app using `npm run electron:windows`.
and following problem is happend.

```
Error: Received packet in the wrong sequence.
    at u._parsePacket (file:///C:/Users/Mars/AppData/Local/Temp/1VTEfjB4MFi1QQbqOIxHf4cp9sc/resources/app.asar/dist/main.434c406….js:1:281511)
    at u.KBiZ.u._parsePacket (file:///C:/Users/Mars/AppData/Local/Temp/1VTEfjB4MFi1QQbqOIxHf4cp9sc/resources/app.asar/dist/main.434c406….js:1:162890)
    at u.KBiZ.u.write (file:///C:/Users/Mars/AppData/Local/Temp/1VTEfjB4MFi1QQbqOIxHf4cp9sc/resources/app.asar/dist/main.434c406….js:1:157155)

```

i add following content in package.json file
```
 "dependencies": {
    "mysql": "2.17.1"
  }
```

and do connection in `HomeComponent`

```
 connect() {
    const connection = mysql.createConnection({
      host     : 'XXXX',
      port     : '3306',
      user     : 'XXXX',
      password : 'XXXX',
      database : 'demo',
    });

    connection.connect(
        err => {
            if (err) {
              console.log(err);
              console.log('Connection error!');
            }
            else {
              console.log('Connected!');
            }
        }
    );
}
```

Thanks a lot.

**Comment by maximegris** [comment]
Seems related to https://github.com/mysqljs/mysql/issues/1548 and file optimisation (uglify) when building in production.

Try settinb `buildOptimizer : false` and/or `optimization: false` in angular.json production profile (line 71 and 79). It may works. Otherwise you should overide the webpack configuration to fixe the default mangling behaviour.

**Comment by gassyou** [comment]
Yes, It work fine.
Thank you very much.
