### ISSUE TITLE
Context-aware native module support?

### ISSUE THREAD

**Issue by cyrilfr** [maximegris/angular-electron#425]
I added sqlite3 native module with TypeORM to my project. Here is my new angular.webpack.json file:

```
/**
 * Custom angular webpack configuration
 */

const path = require('path');

module.exports = (config, options) => {
    config.target = 'electron-renderer';
    if (options.customWebpackConfig.target) {
        config.target = options.customWebpackConfig.target;
    } else if (options.fileReplacements) {
        for(let fileReplacement of options.fileReplacements) {
            if (fileReplacement.replace !== 'src/environments/environment.ts') {
                continue;
            }
            let fileReplacementParts = fileReplacement['with'].split('.');
            if (['dev', 'prod', 'test', 'electron-renderer'].indexOf(fileReplacementParts[1]) < 0) {
                config.target = fileReplacementParts[1];
            }
            break;
        }
    }
    config.externals = {
        'typeorm': "require('typeorm')",
        'sqlite3': "require('sqlite3')",
        'react-native-sqlite-storage': 'react-native-sqlite-storage'
    };
    config.resolve = {
        alias: {
            typeorm: path.resolve(__dirname, '../node_modules/typeorm/typeorm-model-shim')
        }
    };
    return config;
}
```
I get this warning at compile time:

> Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information

Any clue on how to prevent this?

**Comment by Css-IanM** [comment]
You shouldn't try to do this in the render process, this should be handled in the main electron process or a worker thread. Serialize your payload and send it via IPC to the main process and use sql and typeorm there.

**Comment by Css-IanM** [comment]
Where are you using it? In the renderer process or main process? I would hazard to guess you're using maybe an angular service to try to do the SQL and ORM tasks. Try doing this in the main process, send your payload via IPC to the main process and handle it there. Apart from electron complaining you may also run into zonejs issues with these kinds of modules in the renderer process.

**Comment by cyrilfr** [comment]
Yes I use it in a service and I create the connection in my application.module.ts:
```
import { createConnection } from 'typeorm';

export function DatabaseLoaderFactory() {
  return () => createConnection({
    type: 'sqlite',
    database: 'src/app/vesta.db',
    entities: [User],
    synchronize: true,
    logging: false
  });
}

@NgModule({
  ...
  providers: [
    {
      provide: APP_INITIALIZER,
      useFactory: DatabaseLoaderFactory,
      multi: true
    }
  ]
  ...
})
export class AppModule { }
```
 

> Try doing this in the main process, send your payload via IPC to the main process and handle it there.

How can I do that?

**Comment by Css-IanM** [comment]
You would use [this](https://electronjs.org/docs/api/ipc-main) to communicate between the main ('main.ts') process, dispatched using [this](https://github.com/maximegris/angular-electron/blob/master/src/app/core/services/electron/electron.service.ts) service from the renderer process. You wont see the warning, and more importantly since its a deprecation your app will work in future versions.

For more information regarding the context of the electron processes see [here](https://electronjs.org/docs/tutorial/application-architecture#main-and-renderer-processes)

**Comment by cyrilfr** [comment]
OK thanks, I'll try to use [ngx-electron](https://www.npmjs.com/package/ngx-electron) to do it.

**Comment by Css-IanM** [comment]
looks like that does the same thing as the included electron service in the repo...but the same concepts still apply. Happy Coding
