### ISSUE TITLE
remote.app.focus() not working

### ISSUE THREAD

**Issue by koiszzz** [maximegris/angular-electron#426]
`
      const ret = this.remote.globalShortcut.register('Control+Alt+T', () => {
        console.log(this.webFrame);
        this.remote.app.focus();
      });
`TypeScript
I try to show the app on the top when I click the shortcut,but it failed .

**Comment by Css-IanM** [comment]
The context of your shortcut is only within the application while it has focus. Are you trying to focus an parallel renderer process window or focus a control within the same renderer process?
