### ISSUE TITLE
process.platform return undefined

### ISSUE THREAD

**Issue by abruneau** [maximegris/angular-electron#43]
I'm using some npm packages that rely on `process.platform` 
The problem is that this command returns `undefined` when run in angular context.
But when I run it in the developper tool console, I get the right information.

Am I missing something ?

**Comment by abruneau** [comment]
From my understanding, the developper tool console is pointing to `electron.remote.process`.
Question now is how to point node modules to `electron.remote.process` ?

**Comment by maximegris** [comment]
node modules are mapped to window global variable (check out `electron.service.ts`.

you can do `this.process = window.require('process')`

**Comment by abruneau** [comment]
Thanks @maximegris,
this solves it when you call `process.platform` from Angular but node packages don't see it.

I solved it by moving this part of the logic in the electron `main.ts` with `ipc`

**Comment by maximegris** [comment]
Glad you fixed it. I close the issue.
