### ISSUE TITLE
CSS paths cannot be resolved in prod

### ISSUE THREAD

**Issue by cyrilfr** [maximegris/angular-electron#432]
I created a `theme.scss` file in `src` with variables:

```
$body-background-color: white;
$body-background-image: url("/assets/images/bg-hexa-gray-flat.png");
$body-background-position: top left;
$body-background-repeat: repeat;

$sidepanel-background-color: white;
$sidepanel-background-image: url("/assets/images/bg-hexa-red-flat.png");
$sidepanel-background-position: top left;
$sidepanel-background-repeat: repeat;
```

It works with `npm start` but once I run electron in prod, I get an error file `file:///assets/images/bg-hexa-gray-flat.png` not found. How do you make your CSS paths work in prod?

**Comment by dev0tion** [comment]
Try changing your asset urls to:
`$body-background-image: url("./assets/images/bg-hexa-gray-flat.png");`
and 
`$sidepanel-background-image: url("./assets/images/bg-hexa-red-flat.png");`

**Comment by cyrilfr** [comment]
Hi, it's not resolved at compile-time then and I get this error:
![screen](https://camo.githubusercontent.com/7e802c24b06aa30e5b834939bff31063bf378f71/68747470733a2f2f692e6962622e636f2f477068664b30712f53637265656e73686f742d66726f6d2d323032302d30312d31352d31302d30362d34302e706e67)

Relative paths aren't well resolved when I import the `theme.scss` file in a component for example.

**Comment by dev0tion** [comment]
I remember having this problem at some point, but I fail to recall how I solved it.
Definitely remove the . again before the assets url.

Try setting base href to ./ in index.html
`<base href="./">`
Also add it to compilerOptions in tsconfig.json
`"baseUrl": "./",`

**Comment by cyrilfr** [comment]
I already set  `--base-href ./` and I checked the output to be sure to have `<base href="./">`.
I have `"baseUrl": "./"` in my tsconfig.json and `"baseUrl": ""` in my tsconfig.app.json file.

**Comment by cyrilfr** [comment]
I found a solution by adding an alias to the webpack config file:
```
config.resolve = {
  alias: {
    assets: path.resolve(__dirname, "src/assets")
  }
};
```
and then use url like this: `url("~assets/images/bg-hexa-gray-flat.png")`.

**Comment by bnohad** [comment]
the only way i found how to fix it in builds is to specify the base-href attribute to be the same as the path i plan to deploy, for example:
ng build --base-href ui
deploy the app under www.example.com/ui/

and then in the SCSS file use: `background-image: url('~/assets/icon.svg')`.

after building the app, the ~ char is replaced with whatever value you provide to the --base-href attribute.
