### ISSUE TITLE
Your project is not using the default builders for "build". The Angular Material schematics cannot add a theme to the workspace configuration if the builder has been changed.

### ISSUE THREAD

**Issue by jrayga** [maximegris/angular-electron#437]
I'm trying to add Angular Material using `ng add @angular/material `for my test project buy I'm currently facing this error.

> Your project is not using the default builders for "build". The Angular Material schematics cannot add a theme to the workspace configuration if the builder has been changed.

Is there a way to implement Angular Material for this project?

Thanks.

**Comment by johnny68** [comment]
Hi, I had run into the same problem.
I installed Angular Material manually.
You would need the following:
In your `angular.json` file add this : 
```
"styles": [
              "node_modules/@angular/material/prebuilt-themes/indigo-pink.css",
            ],
``` 
or whatever theme you want to use.
the options are : 

> "node_modules/@angular/material/prebuilt-themes/indigo-pink.css"
> "node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css"
> "node_modules/@angular/material/prebuilt-themes/pink-bluegrey.css"
> "node_modules/@angular/material/prebuilt-themes/purple-green.css"

The material package is installed, these are the steps that it does upon installation.
So you shouldn't run into any problems

**Comment by Rajdeep97** [comment]
Incase some is looking for how to install Angular Material manually, see this:

https://github.com/angular/components/commit/ca7fff51603602abe682c510b1f67c17f475044e?short_path=27d0824

**Comment by drewmperkins** [comment]
I was struggling with this as well.. but this project is setup with one module per component to help with tree-shaking.

Which means if you are going to be adding Material components, you need to add them under the page module (ex: home.module.ts) .. and not app.module.ts.

**Comment by prince-chrismc** [comment]
Following the manual install guide noted above [rendered](https://github.com/angular/components/blob/ca7fff51603602abe682c510b1f67c17f475044e/guides/getting-started.md), I had an error `'@angular/material/index.d.ts' is not a module` Seems like 2019 is out of date. This helped https://stackoverflow.com/a/60111086/8480874
