### ISSUE TITLE
Bindings not updating automatically

### ISSUE THREAD

**Issue by fredlebel** [maximegris/angular-electron#44]
After some research I had to change the imports of `zone.js` to `zone.js/dist/zone-mix` in `src/app/app.module.ts` and `src/polyfills.ts`.

See: https://github.com/angular/zone.js/issues/537

**Comment by maximegris** [comment]
Weird... 
Is `src/polyfills.ts` a new file you add in your project or do you mean add `import 'polifills'` in `app.module.ts` ?

**Comment by fredlebel** [comment]
`src/polyfills.ts` is in this repo.

The change I made was:
```diff
-import 'zone.js/dist/zone';  // Included with Angular CLI.
+import 'zone.js/dist/zone-mix';  // Included with Angular CLI.
```

and in `src/app/app.module.ts`
```diff
-import 'zone.js';
+import 'zone.js/dist/zone-mix';  // Included with Angular CLI.
```

You need to change both to not get the error `Zone already loaded`.

**Comment by saurabhabh** [comment]
Was working with the latest version of the repo. Found that the zone-mix is reverted back to zone in polyfills.ts.

**Comment by PunkHaz4rd** [comment]
Why was this closed ? It's still not working.
