### ISSUE TITLE
electron app on windows - difference between app icon in win-upacked vs release

### ISSUE THREAD

**Issue by maku** [maximegris/angular-electron#441]
I've been fighting for a long time to get the right icon for my application. 

When I build the app (`npm run electron:windows`) I get an exe in release/win-unpacked. In this exe the icon is perfect. But the icon I get for the release version is "pixeled" (release folder)

Can anybody explain what is going on?

**Comment by johnny68** [comment]
Try one of the recommended size [link](https://www.electron.build/icons#windows-nsis)
I too ran into this issue.
