### ISSUE TITLE
ngFor not rendering data from obserable until a link is clicked

### ISSUE THREAD

**Issue by decreasenl** [maximegris/angular-electron#443]
I have been having issues trying to render a list of items. I have injected a service to fetch an observable with a list of strings.  Trying to render the data does not work until i click a link somewhere on the page. Not that the link does not have a **(click)** event binding attached to it.

I have tried to return the observable directly and implement the `async` pipe but the problem remained. After that I tried to track the items using a `trackBy` function but to no avail.

If i try to detect the changes using the `ChangeDetectorRef` I get an error on a different line where variable databases is used:

```
main.ts:15 TypeError: Cannot read property 'databases' of null
```

my Template:

```
<li *ngFor="let database of databases">
      <a  href="#">
          {{ database }}
      </a>
    </li>
```

My implementation to subscribing to the observable:
```
this.databaseService.query(this.queryRepository.showDatabases()).subscribe((databases: [{ Database: string }]) => {
      this.databases = databases.map(db => db.Database);
    })
```

My observable:

```
query(sql: string) {
    const queryObservable = new Observable(observer => {
      this.mysqlConnection.query(sql, (errors, results, fields) => {
        observer.next(results);
        if(errors) {
          observer.error(errors);
        }
      });
    })
    
    return queryObservable;
  }
```

**Comment by johnny68** [comment]
What function is triggering the observable ?

**Comment by decreasenl** [comment]
This function is called in the constructor of a component.

```
this.databaseService.query(this.queryRepository.showDatabases()).subscribe((databases: [{ Database: string }]) => {
      this.databases = databases.map(db => db.Database);
    })
```

**Comment by decreasenl** [comment]
Its working now. For some reason calling `detectChanges()` after each datachange renders the `*ngFor` correctly.

```
this.databaseService.query(this.queryRepository.showDatabases()).subscribe((databases: [{ Database: string }]) => {
      this.databases = databases.map(db => db.Database);
      this.chRef.detectChanges();
    })
```

**Comment by decreasenl** [comment]
Please note that any reactive variables assigned only update after calling for `  this.changeDetectorRef.detectChanges();`
