### ISSUE TITLE
Cant use Rxjs module in mainProcess

### ISSUE THREAD

**Issue by samsamm777** [maximegris/angular-electron#45]
Using rx js gives errors when trying to include in the mainProccess

```typescript
import { Observable } from 'rxjs/Observable';
import 'rxjs/Rx';
```

```shell
node_modules/rxjs/Observable.d.ts(69,60): error TS2693: 'Promise' only refers to a type, but is being used as a value here.
node_modules/rxjs/operator/toPromise.d.ts(3,79): error TS2693: 'Promise' only refers to a type, but is being used as a value here.
```

## Repro steps
```shell
$ git clone https://github.com/maximegris/angular-electron.git
$ cd angular-electron/
$ npm i
```

Add the following lines to main.ts at top.

```typescript
import { Observable } from 'rxjs/Observable';
import 'rxjs/Rx';
```

```shell
$ npm start
$ npm run electon:serve
```

**Comment by samsamm777** [comment]
This is a huge blocker for us, so any help would be appreciated.

**Comment by maximegris** [comment]
Hi,

Please check last comments of https://github.com/ReactiveX/rxjs/issues/2422 to fix your error.

**Comment by samsamm777** [comment]
Infact I worked out a solution to this. The smoking gun, is that the 'build:electron:main' command ignores the tsconfig.ts file. [See here](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html)  Resulting in a compile using no config. In order to build the typescript using ES6 which is needed for Observables i amended the command.

```tsc main.ts --experimentalDecorators --emitDecoratorMetadata --module commonjs --moduleResolution node --types node --target es6 --typeRoots node_modules/@types --outDir dist --sourceMap && copyfiles package.json dist && cd dist && npm install --prod && cd ..```

**Comment by maximegris** [comment]
Glad you find a solution :) 👍
