### ISSUE TITLE
app.allowRendererProcessReuse is deprecated

### ISSUE THREAD

**Issue by FrancescoBorzi** [maximegris/angular-electron#454]
I'm getting:

> (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397

should I do something about it?

**Comment by navarrojandg** [comment]
If you want to get rid of this message just simply add
```
app.allowRendererProcessReuse = true
```
In the app.whenReady callback function

**Comment by deadcoder0904** [comment]
@navarrojandg I tried doing that but still get warnings. Am I doing it right?

```js
// main.js
app.whenReady(() => {
  app.allowRendererProcessReuse = false
})
```

**Comment by navarrojandg** [comment]
No, its supposed to be true

**Comment by deadcoder0904** [comment]
Yep, I set it to `true` & `false` both. But it still gives me the same error 😂

If it helps, I’m using `electron-forge`

**Comment by roscoevanderboom** [comment]
@deadcoder0904 Try putting it outside the app.whenReady()

That worked for me. Here is my sample
https://github.com/roscoevanderboom/Electron-React-Webpack-MaterialUI-Boilerplate/blob/master/public/electron.js

**Comment by maximegris** [comment]
Hi  
This was added in the project. The message should not be displayed anymore.

**Comment by deadcoder0904** [comment]
Ha was wondering about this today only. Thanks [it worked](https://github.com/maximegris/angular-electron/blob/7c5c43bad76b34142d77622cb2931d0845271039/main.ts#L56) ✨

Related commit: https://github.com/maximegris/angular-electron/commit/7c5c43bad76b34142d77622cb2931d0845271039 :)

**Comment by Xcry84** [comment]
scusate dove trovo pp. allowRendererProcessReuse nel mio raspberry mi potete aiutare
