### ISSUE TITLE
scss files in styles block of angular-cli.json not being injected into html

### ISSUE THREAD

**Issue by faustind** [maximegris/angular-electron#46]
I have been trying to use angular-bootstrap-md following the instructions here https://www.npmjs.com/package/angular-bootstrap-md .

I updated package.json to solve unmet dependency problems.

no error raised for running npm start and npm run electron:serve.

I deleted the content of styles.scss and home.component.scss.
And changed home.component.html to
```html
<h1 class="title">
    {{title}}
</h1>
<button type="button" class="btn btn-primary">btn</button>
```

Here screen shot of the result
![angular_electron_mdb](https://user-images.githubusercontent.com/22149223/28401714-bdfddb52-6d56-11e7-95e1-e82bcc81dda7.png)

updated styles bloc in angular-cli.json:
```json
"styles": [
    "../node_modules/font-awesome/scss/font-awesome.scss",
    "../node_modules/angular-bootstrap-md/scss/bootstrap/bootstrap.scss",
    "../node_modules/angular-bootstrap-md/scss/mdb.scss",
    "./styles.scss"
],
```
app.module.ts now looks like
```ts
...
import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
...
import { MDBBootstrapModule } from 'angular-bootstrap-md';

@NgModule({
    ...
  imports: [
    ...
    MDBBootstrapModule.forRoot()
  ],
  schemas: [ NO_ERRORS_SCHEMA ],
  ...
})
export class AppModule { }
```
thank you!

**Comment by maximegris** [comment]
Once `eject` command is used, you're not using the CLI as a build system anymore. Whatever is in angular-cli.json is irrelevant for builds.

You can directly import your scss file in `style.scss`
