### ISSUE TITLE
How to shared custom .ts files between main.ts and angular app?

### ISSUE THREAD

**Issue by otsybulsky** [maximegris/angular-electron#460]
Hi! I found how to add custom files to main.ts  #265 But I need to use the same files in the Angular app.
```
shared/window.service.ts

main.ts
import { windowService } from 'shared/window.service.ts'
const  _winService = new windowService()

src\main.ts
import { windowService } from 'shared/window.service.ts'
const  _winService = new windowService()
```
Please tell me how to do this.

**Comment by JeffSallans** [comment]
The key is to make sure your files are included in your angular build.  So make sure they are included in the /src directory and imported in your angular app.  For example, I have some common ipc message interfaces I share between both and this is where I put them.

![image](https://user-images.githubusercontent.com/1188772/78403382-42a25580-75ca-11ea-9d8d-bfc169253d9a.png)


app.component.ts
```
import { ToolShowHideMessage } from './core/ipc-models/tool-show-hide.message';
// ...
private onToolShowHideMessage(event: IpcRendererEvent, message: ToolShowHideMessage) {
    console.debug('onToolShowHideMessage', message);
    this.showTool = message.showTool;
}
```

main.ts
```
import { ToolShowHideMessage } from './src/app/core/ipc-models/tool-show-hide.message';
// ...
{
    label: 'Show/Hide Tools',
    accelerator: 'CommandOrControl+T',
    click: async () => {
        showTool = !showTool;
        const message: ToolShowHideMessage = {
            messageType: MessageTypes.ToolShowHide,
            showTool,
        };
        console.debug('onToolShowHideMessage', message);
        window.webContents.send('onToolShowHideMessage', message);
    },
}
```

**Comment by otsybulsky** [comment]
Thank you!

**Comment by ShreyanshDaga** [comment]
Hello @JeffSallans,

I followed your recommendation by moving my shared types inside src/spp folder of the angular project
![image](https://user-images.githubusercontent.com/6823110/199208398-4ea22f51-2c6d-4565-9491-272354f8a893.png)

And updated the electron-builder.json as you suggested

However when I launch the exe I still see the issue 
![image](https://user-images.githubusercontent.com/6823110/199208526-f6018c6d-ce0e-4e8d-be59-739674c74ab9.png)

I am not sure where I am going wrong, would you have any pointers ?
