### ISSUE TITLE
Node Modules Support

### ISSUE THREAD

**Issue by dr-nyt** [maximegris/angular-electron#464]
Hey! I'm new to Angular and currently struggling with adding node modules. In an old 'closed' issue, @maximegris had said he would add instructions on how to use Node Modules in the ReadMe, but he hasn't done it so far. Any guidance would be appreciated.

**Comment by MrSurana** [comment]
@dr-nyt

Which node module are we specificaly talking about here ?

And is it related to the combination of angular and electron or is it just an angular specific issue and not relevant to if it is run with electron or not ?

> To install a node module you can run `npm install`

**Comment by dr-nyt** [comment]
@MrSurana I managed to figure it out. I was just trying to import a node module into an angular component like so: `const fs = require('fs');`, but after hours of button smashing I found out it was pretty simple `const fs= (<any>window).require("fs");`.

I hope someone finds this helpful 💃

**Comment by MrSurana** [comment]
Awesome!

By the way, you can also inject the `ElectronService` from `src/app/core/services` which already has the `fs` module imported in it.

**Comment by Hybueno09** [comment]
It's a different problem but in web worker, it's any solution to import node native module(such as fs or net)
