### ISSUE TITLE
Angular Material: No project index HTML file could be found.

### ISSUE THREAD

**Issue by theocerutti** [maximegris/angular-electron#470]
Hello,

I would like to install material angular (https://material.angular.io/) but I've some problems..
I cloned this repo and run npm install and then run ``npm run ng add @angular/material``.
First try I install it by choose the Indigo/Pink theme and answer yes for all others options but it throws me an error:

![Screenshot from 2020-04-17 21-33-01](https://user-images.githubusercontent.com/44285344/79607314-4c13dd80-80f3-11ea-9fa7-8aa8cc71c5fd.png)

Then, I tried to install it without theme but there is another error:

![Screenshot from 2020-04-17 21-33-35](https://user-images.githubusercontent.com/44285344/79607323-4fa76480-80f3-11ea-8848-54961a2aeca4.png)

Thanks for help !

**Comment by alexisbeaulieu97** [comment]
run command 
ng add @angular/material


then add
@import '@angular/material/prebuilt-themes/indigo-pink.css';
to your src/styles.scss file
