### ISSUE TITLE
Anyone using google analytics + google tag manager with this?

### ISSUE THREAD

**Issue by prameshbajra** [maximegris/angular-electron#472]
Hi all,

This is not an angular-electron per se, but I would like to know how you guys are implementing google analytics and google tag manager if you are.

Running `ng serve` gives proper analytics tracking but packaging it as a windows installer does not give you tracking details.

Any help is appreciated.

Thanks.

**Comment by Ronalses** [comment]
Hello @prameshbajra 

This post can help you use google analytics 

https://medium.com/@PurpleGreenLemon/how-to-properly-add-google-analytics-tracking-to-your-angular-web-app-bc7750713c9e

Saludos!

**Comment by prameshbajra** [comment]
Thanks for the reply @Ronalses,

I did already try this. Worked in web app, did not work in an electron app (primarily windows).

**Comment by kdumontnu** [comment]
@prameshbajra I'm using Google Analytics on an application. I found this useful: https://kilianvalkhof.com/2018/apps/using-google-analytics-to-gather-usage-statistics-in-electron/

I ended up initializing analytics in the main thread and creating an Angular Service to handle tracking in the render thread.
