### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by zindelluib** [maximegris/angular-electron#48]
Hi ! I Just like to ask how to include the some npm modules and call it in the components (e.g. mysql - for connecting database).I already read the documentation but I need more detailed information on calling node modules in the component/services.Thank you

https://github.com/mysqljs/mysql
How can I achieve this one  in your boilerplate? 

var mysql      = require('mysql');
var connection = mysql.createConnection({
  host     : 'localhost',
  user     : 'me',
  password : 'secret',
  database : 'my_db'
});

connection.connect();

connection.query('SELECT 1 + 1 AS solution', function (error, results, fields) {
  if (error) throw error;
  console.log('The solution is: ', results[0].solution);
});

connection.end();

**Comment by FrancescoBorzi** [comment]
@maximegris what is the solution for this question? In particular, would it be possible to import a node module (in this case mysql) only when on electron?

**Comment by FrancescoBorzi** [comment]
@maximegris any thoughts about my question?
