### ISSUE TITLE
How to update existing project?

### ISSUE THREAD

**Issue by Rajdeep97** [maximegris/angular-electron#480]
Suppose I started with Electron 8 & Angular 9. After few months they got upgraded to Electron 9 and Angular 10 and you release the changes with a new branch.
How do I update my existing project to the New versions?
It would be really helpful if someone could list down the steps.

**Comment by Rajdeep97** [comment]
@maximegris Any Idea?

**Comment by hannesw** [comment]
@Rajdeep97 I also asked this in #447 and sadly got no answer. For me the solution is as followed:

- Check which version of angular-electron you are using (e.g. for me 7.0.5)
- Go to releases for this repo on github and use the compare view (https://github.com/maximegris/angular-electron/compare/7.0.5...7.1.0)
- If you have to update multiple versions e.g. from 7.0.0. to 7.1.0 I recommend to do this release by release continousily testing after each update and not directly compare 7.0.0 to 7.1.0. This keeps the changes small.
- Manually merge this changes to your codebase where applicable
- Keep track which angular-electron version you are now on. (I do this within my readme.md file)
- When a new release comes out repeat the process

Hope this helps

**Comment by Rajdeep97** [comment]
Wow! @hannesw That's a painfully slow and long process.
Thank you so much for letting me know.
