### ISSUE TITLE
Can load the app in the browser, Can't resolve 'fs'

### ISSUE THREAD

**Issue by Mohamed-Elshaarawy** [maximegris/angular-electron#481]
when I run `npm run ng:serve:web` i got a webpack exception
one of my components depends on Electron Service when I remove that dependency the app works fine 
ERROR in ./node_modules/electron/index.js
Module not found: Error: Can't resolve 'fs' in 
also, I can't open a new window with a URL 
please can anyone help me?
EDIT: after updating angular CLI I got also
ERROR in ./node_modules/electron/index.js
Module not found: Error: Can't resolve 'path' in

**Comment by nikensss** [comment]
That's because fs and path are modules only accessible from NodeJS (they are NodeJS native libraries). When you are using the web, you don't have a NodeJS execution framework to back you up.

It is explained here: https://github.com/maximegris/angular-electron#browser-mode

**Comment by Mohamed-Elshaarawy** [comment]
I do the check in the electron service but I got the same issue
