### ISSUE TITLE
Mark as template repository

### ISSUE THREAD

**Issue by minomikula** [maximegris/angular-electron#483]
Hello,

Did you consider marking your repo as "template repositary" in github? It is a new github feature (from june 2019) https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/

It will simplify creating new repos based on your boilerplate.

Thanks!!

**Comment by validity-check** [comment]
It's already a template.
![image](https://user-images.githubusercontent.com/63739210/85224344-a0705d80-b3c1-11ea-8a58-a83b6c1c41a7.png)

**Comment by validity-check** [comment]
Are we going to close this

**Comment by minomikula** [comment]
Thanks!
