### ISSUE TITLE
Child Process close events not firing

### ISSUE THREAD

**Issue by vijhhh2** [maximegris/angular-electron#487]
Hi,
I spawned a child process.
Close event of the child process is firing when I route to another page and come back to the same page.

```
  ngOnInit(): void {
    this.subscription = this.runPowershellScript().subscribe(data => {
      console.log('data from observable', data);
    });
  }

runPowershellScript(): Observable<any> {
    const ps = this.electroService.childProcess.spawn("powershell.exe", [
      "Write-Host Hello Powershell",
    ]);

    return Observable.create((obs: Observer<any>) => {
      let finalData = '';

      ps.stdout.on("data", (data) => {
        console.log('data event fired');
        finalData += data;
      });

      ps.stderr.on("data", (data) => {
        console.log("error", data);
        obs.error(data);
      });

      ps.on("close", (code) => {
        console.log(`Application exit with code ${code}`);
        obs.next(finalData);
        obs.complete();
      });
    });
  }
```

Just clone the code from git and add the above code in home.component.ts to reproduce the issue.
If I try to run the runPowershellScript method again then close event fires for the old one and starts a new one.

I checked by running electron with plain javascript it's working there.

I think there is an issue with integration with angular. Can anyone check on this, please?

OS: Windows 10

**Comment by lyuan520** [comment]
I have the same problem !!
