### ISSUE TITLE
Can't build in prod mode

### ISSUE THREAD

**Issue by erynion123** [maximegris/angular-electron#49]
When trying to build in prod mode getting module note found error :

`ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Applications/MAMP/htdocs/abc/src'
resolve './$$_gendir/app/app.module.ngfactory' in '/Applications/MAMP/htdocs/abc/src'
  using description file: /Applications/MAMP/htdocs/abc/package.json (relative path: ./src)
  after using description file: /Applications/MAMP/htdocs/abc/package.json (relative path: ./src)
    using description file: /Applications/MAMP/htdocs/abc/package.json (relative path: ./src/$$_gendir/app/app.module.ngfactory)
      no extension
        /Applications/MAMP/htdocs/abc/src/$$_gendir/app/app.module.ngfactory doesn't exist
      .ts
        /Applications/MAMP/htdocs/abc/src/$$_gendir/app/app.module.ngfactory.ts doesn't exist
      .js
        /Applications/MAMP/htdocs/abc/src/$$_gendir/app/app.module.ngfactory.js doesn't exist
      .scss
        /Applications/MAMP/htdocs/abc/src/$$_gendir/app/app.module.ngfactory.scss doesn't exist
      .json
        /Applications/MAMP/htdocs/abc/src/$$_gendir/app/app.module.ngfactory.json doesn't exist
      as directory
        /Applications/MAMP/htdocs/abc/src/$$_gendir/app/app.module.ngfactory doesn't exist`

**Comment by Kaffiend** [comment]
Getting the same thing..

**Comment by maximegris** [comment]
It's a bug in angular-cli .
(See https://github.com/angular/angular-cli/issues/4551)

This workaround works : `npm install enhanced-resolve@3.3.0`

**Comment by polyglotinc** [comment]
Did this as recommended by some:
`npm i @angular/cli@1.2.4`
but that did not fix the problem.
Did this:
`npm install enhanced-resolve@3.3.0`
and it fixed the problem for my relatively simple app
