### ISSUE TITLE
Remove OS from electron-builder CLI

### ISSUE THREAD

**Issue by kdumontnu** [maximegris/angular-electron#490]
Is there a reason we specify the OS for electron-builder in `package.json`? I believe electron-builder should detect the OS it is building for by default. It's a bit cumbersome to remember to add electron:windows, electron:mac etc. when building cross-platform, especially using a CI tool.

I'd propose merging all three to:
`"electron:build": "npm run build:prod && electron-builder build",`

**Comment by maximegris** [comment]
Hi @kdumontnu 

Things have changed since the first version of electron-builder when I started this project. :)
I will take a look this weekend on it.

**Comment by maximegris** [comment]
Merged on master branch.

**Comment by Lazza** [comment]
Could it be possible to keep both? It's a bit harder to cross-build for Windows or another platform now.

Thank you! 🙂

**Comment by Lazza** [comment]
OK. 😞

**Comment by maximegris** [comment]
Hi @Lazza 

You can still make cross-build with the commands below

* `npm run electron:build -- --windows`
* `npm run electron:build -- --mac`
* `npm run electron:build -- --linux`

**Comment by Lazza** [comment]
@maximegris thank you, I didn't know that. Great!
