### ISSUE TITLE
Can't make a .msi installer. Is there a speciall package?

### ISSUE THREAD

**Issue by MaxGER2019** [maximegris/angular-electron#491]
I have a problem. Is it possible to make a msi installer with the [electron-windows-installer](https://github.com/electron-userland/electron-installer-windows)?

Because i tried it and it doesnt work with this template. Is there a speciall way or package to make an installer out of the .exe?

**Comment by 313hemant313** [comment]
Please check If this works for you

https://github.com/maximegris/angular-electron/issues/338#issuecomment-495466366
