### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by jaboj78** [maximegris/angular-electron#5]
Hi

First of all, thank you for this fabulous angular-electron bootstrap.

I think there's a typo i package.json "electron:dist" script - "ru1" instead of "run".

To build an app on mac/os, I've to change "." to "dist" in "electron:mac" script. This also makes it equal build scripts for other platforms. I'm not sure how it's ment to work, but for me this is the only way I can make the app work on mac.

Regards
Jacob

**Comment by maximegris** [comment]
Hi,

Thanks for your feedback.

You're totally right! I forgot to change electron-packager folder in "electron:mac" script. I'm not a Mac owner so I didn't test this script :/ 

But no excuse for the typo "ru1" :)

I fixed & pushed both issues.

Regards
