### ISSUE TITLE
Cannot import node 'fs' module

### ISSUE THREAD

**Issue by zuckerruebe** [maximegris/angular-electron#503]
Doing

`import { readFileSync } from 'fs'`

in my code yields a build (or runtime?) error saying

`Can't resolve 'fs' in 'C:\_work\src\tsopen\test-editor\src\app\data-table'`

when I do `npm run start`.

I've done `npm install @types/node` so the typing information should be there. Also Visual Studio Code isn't complaining. I've also tried `import * as fs from 'fs'` and various other forms to no avail.

I guess this isn't really a bug but I've kind of run out of options here and was hoping you might be able to help me out.

Cheers,
Damian

**Comment by mikaeljensen** [comment]
Looks like you are trying this in the Angular/Renderer/Client-side. "fs" is a core node module and is not available in the renderer, only in main. The "normal" approach (I think) would be to contact main through IPC, have main do the fs work, and return the result to the renderer through IPC.

**Comment by SaraStoimenovska** [comment]
If you want to use fs in the Angular, take a look at the ElectronService and import fs from there
