### ISSUE TITLE
Unable to build for development

### ISSUE THREAD

**Issue by habloo94** [maximegris/angular-electron#504]
I am getting the below error once i do npm start to build for development after cloning and installing dependencies.

Unknown error: Error: No valid exports main found for 'C:\Users\hp\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\uuid'

**Comment by mikaeljensen** [comment]
Problem is specific to your global cli, hence `...\AppData\Roaming\npm\node_modules@angular\cli\node_modules\uuid'`
Try updating your global Angular cli, and see if that helps.

**Comment by habloo94** [comment]
Thanks! it worked
