### ISSUE TITLE
Project sementation

### ISSUE THREAD

**Issue by Tomekske** [maximegris/angular-electron#505]
What is the best approach to segmentize an angular-electron project ? Some clarification: Where should I store plain typescript files which can be accessed by all angular modules and by main.ts file used by electron ?

**Comment by mikaeljensen** [comment]
Everything Angular goes into the src/app folder and below (lots of references available on how to structure an Angular project)
Everything Electron goes into src and below, except for src/app. Electron apps can be very different, so might be a bit harder to make a structural guide that fits all purposes.
