### ISSUE TITLE
Does it able to call third partly dll libraries in electron

### ISSUE THREAD

**Issue by habloo94** [maximegris/angular-electron#506]
i am working on a native application project with the stack below.
Electron JS
.net Core for calling functions and method third party dll libraries.
Angular JS for frontend
sqlite for database.

so my question is that possible of calling dll files in electron and access the function with angular front end.

Please guide me with reference.

**Comment by maximegris** [comment]
Have a look at [IPC Main Electron](https://www.electronjs.org/docs/api/ipc-main) to communicate between electron (Main Process) and angular (Renderer Process)
