### ISSUE TITLE
Changing nodeIntegration to false breaks entire app

### ISSUE THREAD

**Issue by adamk33n3r** [maximegris/angular-electron#508]
I'm trying to use your template but when I change `nodeIntegration` to `false` and run the app, an error is thrown in the console and doesn't load.

![image](https://user-images.githubusercontent.com/1350444/88903459-bd4e4b00-d221-11ea-8d80-3eb94f0beb4d.png)

**Comment by maximegris** [comment]
Replace `"start": "npm-run-all -p ng:serve electron:serve"`
by  `"start": "npm-run-all -p ng:serve:web electron:serve"`
in `package.json`

See https://github.com/maximegris/angular-electron/issues/60#issuecomment-586623106

This should fix the error.

**Comment by adamk33n3r** [comment]
@maximegris thank's a lot! worked great. I did remove the `-o` from the script so that it wouldn't ALSO open it up in my browser. What is the reason this works? I didn't see anything in the angular,json that was different with the `web` configuration

**Comment by maximegris** [comment]
The trick is done in `angular.webpack.js` file.

By default, it sets the target to `electron-renderer` which is needed to run the compiled Electron app (when assets are on file system or during tests)

Target has to be changed to `web` when you run the app in web context. 
There was an issue when nodeIntegration is set to false.

**Comment by adamk33n3r** [comment]
Gotcha, thanks a lot!

**Comment by mastakillahBlitzar** [comment]
thank you!
