### ISSUE TITLE
Import a node module

### ISSUE THREAD

**Issue by zindelluib** [maximegris/angular-electron#51]
I want to use mysql(https://github.com/mysqljs/mysql - Node module.Not the database) for my electron app. I just like to ask how to import it in components/services.

Is using the code below(which is written in your documentation) applicable to my concern?

"externals": {
    "electron": 'require(\'electron\')',
    "child_process": 'require(\'child_process\')',
    "fs": 'require(\'fs\')'
    ...
  }
Need a reply. Thanks!!!

**Comment by maximegris** [comment]
I close this issue (duplicate #48)
