### ISSUE TITLE
Typescript compiler 'unused file' warnings

### ISSUE THREAD

**Issue by distributev** [maximegris/angular-electron#510]
https://github.com/maximegris/angular-electron/issues/461 is still happening when I run

npm run start

![image](https://user-images.githubusercontent.com/19224635/89642038-48c77c00-d8b3-11ea-9540-9ee35d9e2cc3.png)

**Comment by zwif** [comment]
Same here!
I was able to fix this by modifying `src/tsconfig.app.json`:

Replace this:
```json
// ...
"include": [
    "**/*.ts",
  ],
// ...
``` 

with:
```json
//...
"include: [
  "main.ts",
  "polyfill.ts"
],
//...
```
