### ISSUE TITLE
ES5 deprecated in Angular 10

### ISSUE THREAD

**Issue by nphias** [maximegris/angular-electron#513]
Hi, wondering why the tsconfig files still target ES5?..  it is being deprecated in 10+
problems arise with the imports in the electron service file

I fixed it by changing my target to ES6
and adding  "module": "commonjs",
so that the main.js file doesnt cause an error.

also electron (chromium) is the target here.. that doesnt need ES5

**Comment by chenc041** [comment]
> Hi, wondering why the tsconfig files still target ES5?.. it is being deprecated in 10+
> problems arise with the imports in the electron service file
> 
> I fixed it by changing my target to ES6
> and adding "module": "commonjs",
> so that the main.js file doesnt cause an error.
> 
> also electron (chromium) is the target here.. that doesnt need ES5

when you change the target to es6 and adding module: commonjs, the file of ts transform is same with target es5 generated;
and the tsconfig files still target es5, because of the electron is not support es6;
related [Support Node 13's ES Modules](https://github.com/electron/electron/issues/21457)
