### ISSUE TITLE
Bindings not updated inside of ipcRenderer event

### ISSUE THREAD

**Issue by JRCocos** [maximegris/angular-electron#516]
Bindings wont update inside of an ipcRenderer event, have to use ChangeDetectorRef as a workaround

```typescript 
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
const electron = (<any>window).require('electron');

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit
{
  status = "";

  constructor(private router: Router) { }

  ngOnInit(): void
  {
    electron.ipcRenderer.on("requested", (event, args) =>
    {
      this.status = "wont update";
    });
  }
}
```

**Comment by maximegris** [comment]
Did you try to wrap your `ipcRenderer callback` in [ngZone.run](https://angular.io/api/core/NgZone#run) or fire  [ChangeDetectorRef.detectChanges](https://angular.io/api/core/ChangeDetectorRef#detectChanges) ` ?

This should refresh your Angular component.

**Comment by georgematos** [comment]
I am having a similar problem, I got the error in console:
ERROR TypeError: Cannot read property '0' of null
    at EventEmitter.i.send.i.sendSync

I have a component I injected a ElectronService and call it:
let file = this.electronService.ipcRenderer.sendSync('convertFileToBlob', 'filename.save');

The app runs without no errors when I execute npm start, but after build with npm run electron:build the error is throwned
