### ISSUE TITLE
e2e not working

### ISSUE THREAD

**Issue by zwif** [maximegris/angular-electron#523]
Executing `npm run e2e` fails:
```
Error: Failed to create session.
session not created: This version of ChromeDriver only supports Chrome version 83
```

Pretty sure this originates from the [Electron 10 Update](https://github.com/maximegris/angular-electron/commit/b71c514dcc1fd0453905ffc3808a14bf44d910a7).
It seems like [Spectron](https://github.com/electron-userland/spectron) has not released an electron 10 compatible Version, yet. (See https://github.com/electron-userland/spectron/issues/693)

**Comment by maximegris** [comment]
Yes you're rigth, 👍 
 
I'm waiting to see if Spectron maintainer can do something about it.

I may need to move to another e2e testing solution (ex: Cypress)

**Comment by maximegris** [comment]
Hi

The issue is not yet closed & we are still waiting for a longterm solution but a workaround is available.
So I have just upgraded the project to Electron 10
