### ISSUE TITLE
Cannot read property '0' of null, after packaged app

### ISSUE THREAD

**Issue by georgematos** [maximegris/angular-electron#524]
I am having a problem, I got the error in console:
ERROR TypeError: Cannot read property '0' of null
at EventEmitter.i.send.i.sendSync

I have a component I injected a ElectronService and call it:
let file = this.electronService.ipcRenderer.sendSync('convertFileToBlob', 'filename.save');

The app runs without no errors when I execute npm start, but after build with npm run electron:build the error is throwned

**Comment by mscteck** [comment]
Hi. Im having the same problem. Have you found a solution?
