### ISSUE TITLE
help

### ISSUE THREAD

**Issue by dada0z** [maximegris/angular-electron#527]
"npm run electron:serve" not work
I think firewall blocked all ports.
But "ng serve" works well.
May be "wait-on tcp:4200" has some problem?
![91383475-ca7d4a80-e85e-11ea-97df-d21f024fbea5](https://user-images.githubusercontent.com/6371260/92562570-c3b3f600-f2a8-11ea-85b8-ce2519fd7d4b.png)

**Comment by colinskow** [comment]
Looks like an issue with Windows firewall. It works fine for me on Linux.
