### ISSUE TITLE
Where is the default menu defined?

### ISSUE THREAD

**Issue by dheerajbhaskar** [maximegris/angular-electron#532]
Please forgive me if this sounds like a noob question.

## Environment
```
C:\Users\Dheeraj>node -v
v14.7.0

C:\Users\Dheeraj>ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 10.1.1
Node: 14.7.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1001.1
@angular-devkit/core         10.1.1
@angular-devkit/schematics   10.1.1
@schematics/angular          10.1.1
@schematics/update           0.1001.1
rxjs                         6.6.2

C:\Users\Dheeraj>systeminfo
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18363 N/A Build 18363
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Dheeraj
Registered Organization:   Microsoft
Product ID:                00330-80000-00000-AA731
Original Install Date:     02-08-2019 Fri, 03:04:04 PM
System Boot Time:          13-08-2020 Thu, 03:10:54 PM
System Manufacturer:       LENOVO
System Model:              80MK
System Type:               x64-based PC

<truncated unneeded info from this command>
```

## Question
Where is the default menu, sub menu, etc defined?

I already see a menu with items: File, Edit, View, Window, Help. There are a lot of submenus defined as well.

## Steps to reproduce
1. clone repo (I'm on Angular 10 & Electron 9 : (master))
2. run `npm run electron:build`
3. run the .exe in release

## What I've already tried
1. Run search in src folder for menu, file, window, help, etc
2. Run search in github repo for menu
3. Search for a top-level package named menu
4. Guessed it must be defined in `webFrame` in ElectronService, tried to find its declarations, found menu class and tried to find it's references. Maybe the editor (vscode) is only finding references inside the same file and couldn't lead me to other files

Thanks for any help you might offer.

**Comment by EngJay** [comment]
@dheerajbhaskar Electron [automatically creates a default menu if no menu is set](https://www.electronjs.org/docs/api/menu#menusetapplicationmenumenu). The [Electron docs](https://www.electronjs.org/docs) provide [an example](https://www.electronjs.org/docs/api/menu#examples) of how a menu can be created and set in the main process.
