### ISSUE TITLE
Mac App Store Private API Rejection

### ISSUE THREAD

**Issue by ParryQiu** [maximegris/angular-electron#542]
Guideline 2.5.1 - Performance - Software Requirements

Your app uses or references the following non-public APIs:

• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerGetBytePtr
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSYankFromKillRing
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSDrawCarbonThemeListBox
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSInitializeKillRing
• Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__CFCopySystemVersionDictionary
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerRangeCopyEndMarker
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_CGFontRenderingGetFontSmoothingDisabled
• Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__kCFSystemVersionProductNameKey
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerRangeCopyStartMarker
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSNewKillRingSequence
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_IOBluetoothPreferenceSetControllerPowerState
• Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__CFCopyServerVersionDictionary
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__LSSetApplicationLaunchServicesServerConnectionStatus
• Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__kCFSystemVersionProductVersionKey
• Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__kCFSystemVersionBuildVersionKey
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerCreate
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_NSTextInputReplacementRangeAttributeName
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerRangeGetTypeID
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerGetLength
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerRangeCreate
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_SetApplicationIsDaemon
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSSetKillRingToYankedState
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerGetTypeID

The use of non-public APIs is not permitted on the App Store, because it can lead to a poor user experience should these APIs change.

We are constantly reevaluating and identifying non-public APIs that you may have been using for an extended period of time. You should always use public APIs and frameworks and ensure they are up-to-date to prevent this issue in the future.

**Comment by ParryQiu** [comment]
"devDependencies": {
    "@angular-builders/custom-webpack": "10.0.1",
    "@angular-devkit/build-angular": "0.1001.3",
    "@angular-eslint/builder": "0.4.0-beta.2",
    "@angular-eslint/eslint-plugin": "0.4.0-beta.2",
    "@angular-eslint/eslint-plugin-template": "0.4.0-beta.2",
    "@angular-eslint/template-parser": "0.4.0-beta.2",
    "@angular/cli": "10.1.3",
    "@angular/common": "10.1.3",
    "@angular/compiler": "10.1.3",
    "@angular/compiler-cli": "10.1.3",
    "@angular/core": "10.1.3",
    "@angular/forms": "10.1.3",
    "@angular/language-service": "10.1.3",
    "@angular/platform-browser": "10.1.3",
    "@angular/platform-browser-dynamic": "10.1.3",
    "@angular/router": "10.1.3",
    "@ngx-translate/core": "13.0.0",
    "@ngx-translate/http-loader": "6.0.0",
    "@types/jasmine": "3.5.14",
    "@types/jasminewd2": "2.0.8",
    "@types/mocha": "8.0.3",
    "@types/node": "12.12.6",
    "@typescript-eslint/eslint-plugin": "4.2.0",
    "@typescript-eslint/eslint-plugin-tslint": "4.2.0",
    "@typescript-eslint/parser": "4.2.0",
    "chai": "4.2.0",
    "conventional-changelog-cli": "2.1.0",
    "core-js": "3.6.5",
    "cross-env": "7.0.2",
    "electron": "10.1.2",
    "electron-builder": "22.8.1",
    "electron-reload": "1.5.0",
    "eslint": "7.10.0",
    "eslint-plugin-import": "2.22.1",
    "jasmine-core": "3.6.0",
    "jasmine-spec-reporter": "6.0.0",
    "karma": "5.2.3",
    "karma-coverage-istanbul-reporter": "3.0.3",
    "karma-electron": "6.3.1",
    "karma-jasmine": "4.0.1",
    "karma-jasmine-html-reporter": "1.5.4",
    "mocha": "8.1.3",
    "npm-run-all": "4.1.5",
    "rxjs": "6.6.3",
    "spectron": "12.0.0",
    "ts-node": "9.0.0",
    "tslib": "2.0.1",
    "typescript": "3.9.7",
    "wait-on": "5.0.1",
    "webdriver-manager": "12.1.7",
    "zone.js": "0.11.1",
  },

**Comment by InterwebCounty** [comment]
This seems rather important.
