### ISSUE TITLE
Enable Remote Module in Karma

### ISSUE THREAD

**Issue by kdumontnu** [maximegris/angular-electron#543]
After updating to electron 10 I was failing `ng test` with:
```
TypeError: Cannot read property 'app' of undefined
            at new ElectronService
```
`enableRemoteModule: true` needs to be set in `src/karma.conf.js` in order to pass ng test using the remote module. It seems like this isn't something you want to support by default, but perhaps it's worth adding to the comment on line 29 in [electron service](https://github.com/maximegris/angular-electron/blob/master/src/app/core/services/electron/electron.service.ts)

**Comment by maximegris** [comment]
Thank for this feedback !

I just set enableRemoteModule to true in order to use remote module with `ng test`.
