### ISSUE TITLE
Separate the original devDependencies into dependencies

### ISSUE THREAD

**Issue by hanhan9449** [maximegris/angular-electron#545]
Why only devDependencies? We should separate dependencies into `dependencies` field.

**Comment by maximegris** [comment]
Electron builder adds 3rd party lib of `dependencies` entry in the final bundle.
You don't need them when it is a pure frontend library like Angular.

Sample without `dependencies` : 48Mo
Sample with frontend (angular, ...) `devDependencies` moved in `dependencies`  : 56Mo
