### ISSUE TITLE
Importing css from node modules

### ISSUE THREAD

**Issue by mbujes** [maximegris/angular-electron#55]
I am trying to import bootstrap css file from npm module.

In angular-cli.json:

```
 "styles": [
        "styles.scss",
        "../node_modules/admin-lte/bootstrap/css/bootstrap.css"
]
```

In webpack.config

```
 "styles": [
      "./src/styles.scss",
      "./node_modules/admin-lte/bootstrap/css/bootstrap.min.css"
]
```
Styles are in the style.bundle but don't applied on the DOM

Can someone help me?

Regards

**Comment by glaucomorais** [comment]
In your angular.cli.json is defined to use scss extension for stylesheet?
Run this and see if it work: `ng set defaults.styleExt scss`.

**Comment by mbujes** [comment]
Solved replacing in web.config css files management

```
{
        "exclude": [
          path.join(process.cwd(), "src/styles.scss")
        ],
        "test": /\.css$/,
        "loaders": ['style-loader', 'css-loader'],
        "include": [/node_modules/]
      },
```
