### ISSUE TITLE
How to use Node JS native "OS" module?

### ISSUE THREAD

**Issue by mostasim** [maximegris/angular-electron#551]
I am unable to Use "os" module in my project.
It gives an error "Module not found: Error: Can't resolve 'os' " when I try to use it in my component.

**Comment by vicentvidal** [comment]
Maybe adding at angular.webpack.js 

module.exports = (config, options) => {
    config.target = 'electron-renderer';
    **config.node = {
        os: 'empty',
      }**
    ....

**Comment by mostasim** [comment]
> Maybe adding at angular.webpack.js
> 
> module.exports = (config, options) => {
> config.target = 'electron-renderer';
> **config.node = { os: 'empty', }**
> ....

This will fix the Module not Found issue, but unable to get `os.hostaname()` getting `null`

**Comment by vermilion** [comment]
@mostasim, maybe that helps
For typeorm I used to make it work with the following snippet
```js
  config.target = 'electron-renderer';
  config.externals = {
    typeorm: "require('typeorm')",
    sqlite3: "require('sqlite3')",
  };
```

**Comment by mostasim** [comment]
> @mostasim, maybe that helps
> For typeorm I used to make it work with the following snippet
> 
> ```js
>   config.target = 'electron-renderer';
>   config.externals = {
>     typeorm: "require('typeorm')",
>     sqlite3: "require('sqlite3')",
>   };
> ```

Thanks @vermilion

**Comment by mostasim** [comment]
I am closing this issue. The solution is given from @vermilion 's comment.

**Comment by mostasim** [comment]
I am closing this issue. The solution is given from @vermilion 's comment.
