### ISSUE TITLE
window close for frameless window not working

### ISSUE THREAD

**Issue by coder-ashwin** [maximegris/angular-electron#553]
when the window is frameless, I am not able to close the window programmatically using `electron.remote.getCurrrentWindow().close()` and also not throwing any errors but the minimize function works `electron.remote.getCurrrentWindow().minimize()`. And also the close function works for windows with frames. Also, this used to work for frameless windowsas well in your previous version which I took around 5 months back (July 2020).

**Comment by SolarIceMedia** [comment]
works for me. I'm building a frameless window with custom title bar and min/max/close icons (via font awesome)

**Comment by SolarIceMedia** [comment]
try this video, hes using an older branch I believe, but its what I based mine on and it works for me:

https://www.youtube.com/watch?v=Ea2lWsumTrM&list=PLHNb3f8cN49Hud29vfjGNFBMzCs90BnuR&index=1&t=2022s

**Comment by coder-ashwin** [comment]
@SolarIceMedia That's what I am saying it worked for me also in that older branch but its not working in the latest one. P.S: I also followed that video while using the older branch.

**Comment by SolarIceMedia** [comment]
hmm dunno then, works perfectly for me

**Comment by whyboris** [comment]
I have a frameless app [Video Hub App](https://github.com/whyboris/Video-Hub-App) and it seems to close correctly with this code:
```ts
import { BrowserWindow } from 'electron';
BrowserWindow.getFocusedWindow().close();
```
