### ISSUE TITLE
Problem with Karma package

### ISSUE THREAD

**Issue by ErickSvalinn** [maximegris/angular-electron#558]
There's an error with the "karma" modules, angular 11 uses karma 5.1.0, but you in the package.json uses the version 5.2.3, generating the following error:
![image](https://user-images.githubusercontent.com/15113124/100027172-07f46400-2dcb-11eb-8d66-4a80c28f37f9.png)

I cloned the repository and just used npm install.

**Comment by maximegris** [comment]
Hi, please change karma version to ~5.1.0 in package.json. 
I will commit the change asap.

**Comment by ErickSvalinn** [comment]
Thank you, i will try i
