### ISSUE TITLE
Request  Github  build action example

### ISSUE THREAD

**Issue by richard457** [maximegris/angular-electron#566]
It is important to build and release an app, would be nice if you provide an example within this repo.

**Comment by developer239** [comment]
@richard457 Wouldn't something like this work? 🤔 https://github.com/marketplace/actions/electron-builder-action

**Comment by richard457** [comment]
@developer239 What was my suggestion is to have a GitHub action built-in with example https://github.com/features/actions

**Comment by maximegris** [comment]
Hi

CI has just been moved from travisCI to github Actions.

You can find workflows [here](https://github.com/maximegris/angular-electron/tree/master/.github/workflows)
