### ISSUE TITLE
Packaging Issue

### ISSUE THREAD

**Issue by Jilaba** [maximegris/angular-electron#57]
This application has been packaged successfully. When opening .exe file it displays the below error, kindly advice on this☺

![package_error](https://user-images.githubusercontent.com/20086829/30467653-d641fa98-9a03-11e7-9535-b25cef4339ba.PNG)

**Comment by Jilaba** [comment]
No response

**Comment by thechausenone** [comment]
Did you ever get this to work because I'm also running into the same issue now...

**Comment by Jilaba** [comment]
Hi,

I got a solution and I resolved that issue
