### ISSUE TITLE
Build (npm run electron:build)

### ISSUE THREAD

**Issue by tatsujb** [maximegris/angular-electron#570]
After I made some rather [minor edits](https://github.com/tatsujb/boilerplate-edits) to your boilerplate, I ran npm run electron:build on ubuntu 20.10 64bit and on windows 10 64bit in both cases the resulting binary fails to run.

I'd like some help with this.

for clarification your boilerplate in the state you provide it in builds and that build runs without issue but my modifications somehow introduced changes that make the resulting built executable instantly crash when run. (build itself is without issue, likewise for npm start).

I don't understand what I could have possibly done to break it.

**Comment by danbete** [comment]
same here...
the html page load with some static text but angular not.
will update if i find anything...
