### ISSUE TITLE
Missing Angular 10 Branch

### ISSUE THREAD

**Issue by nsacerdote** [maximegris/angular-electron#575]
In the [README.md](https://github.com/maximegris/angular-electron/blob/master/README.md) file, both Angular 9 and Angular 10 branches are linked to [angular9 branch](https://github.com/maximegris/angular-electron/tree/angular9).

It would be nice if a branch for Angular 10 is created and linked, I think the branch should be created on [this commit](https://github.com/maximegris/angular-electron/commit/e0fb53998c87e815664732f2c1b07ca8e29e54a0).

**Comment by maximegris** [comment]
You're right. 👍 
[Branch Angular10](https://github.com/maximegris/angular-electron/tree/angular10)
Thanks !
