### ISSUE TITLE
Some remote properties and methods return undefined from ElectronService

### ISSUE THREAD

**Issue by Juansecu** [maximegris/angular-electron#579]
Some `remote` properties and methods return undefined from `ElectronService`, such as:
- `globalShortcut`
- `Menu`
- `getCurrentWindow()`

**Comment by whyboris** [comment]
It looks like _Electron_ is doing away with `remote` and requires migrating to `@electron/remote` - see [Guide](https://github.com/electron/remote#migrating-from-remote)

Short summary:

```sh
$ npm install --save @electron/remote
```
then:
```js
// in the main process:
require('@electron/remote/main').initialize()
```
finally:
```js
// Before
const { BrowserWindow } = require('electron').remote

// After
const { BrowserWindow } = require('@electron/remote')
```

**Comment by maximegris** [comment]
Hi

The latest version (9.0.5 - master) of the project now use `@electron/remote`. 
Electron adn Angular were updated to latest version (Electron v12.0.1 - Angular v11.2.6)

Regards.
