### ISSUE TITLE
ng add @angular/material doesn't work

### ISSUE THREAD

**Issue by ZentoDH** [maximegris/angular-electron#581]
I have tried to add Angular Material with the `ng add @angular/material` but unfortunately to no avail. I also tried to do it this way: `npm install @angular/material @angular/cdk @angular/animations --save` but no results. All the "fixes" only tell to do the following: 

            "styles": [
              "src/styles.scss",
              "node_modules/@angular/material/prebuilt-themes/indigo-pink.css" <---- add this line
            ],

But that doesn't work either. I imported the mat button module, but the `<button mat-raised-button>test</button>` is still the regular button and not the styled Angular Material button. 

I'm stuck on this for way too long already. Anybody any suggestions? I would be forever in your depth.

**Comment by maximegris** [comment]
https://github.com/maximegris/angular-electron/issues/470
