### ISSUE TITLE
exclude angular dependencies  for packing

### ISSUE THREAD

**Issue by tensor1014** [maximegris/angular-electron#583]
macOS Big Sur 11.2.1, Mac mini (M1, 2020)
`yarn add @angular/animations @angular/cdk @angular/material lodash`
build electron app `yarn electron:build`, will include the dependencies of the angular web (package size increases about 40M).

Should I add all web dependencies into devDependencies ? It confuses me. If this is the correct way to solve it, how about add a note  into `README.md`  ?

or separate a new web package.json from  nodeJS package.json ?

**Comment by maximegris** [comment]
You're right.
3rd party librairies used in renderer process (like angular) should be added in devDependencies to not increase the final package's size.
Another way is to follow the [Two package structure](https://www.electron.build/tutorials/two-package-structure) of `electron-builder`
