### ISSUE TITLE
Failed to parse file 'tsconfig.serve.json/tsconfig.json': Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by Joysingh1709** [maximegris/angular-electron#584]
npm start

> angular-electron@9.0.4 start
> npm-run-all -p electron:serve ng:serve

> angular-electron@9.0.4 ng:serve
> ng serve -c web -o

> angular-electron@9.0.4 electron:serve
> wait-on tcp:4200 && npm run electron:serve-tsc && npx electron . --serve

Your global Angular CLI version (11.2.4) is greater than your local version (11.2.0). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Warning: 'outputHashing' option is disabled when using the dev-server.
/ Generating browser application bundles (phase: building)...
> angular-electron@9.0.4 electron:serve-tsc
> tsc -p ./tsconfig.serve.json

error TS5014: Failed to parse file 'tsconfig.serve.json/tsconfig.json': Unexpected token u in JSON at position 0.

**Comment by Joysingh1709** [comment]
while running npm start it gets stuck at this error 

error TS5014: Failed to parse file 'tsconfig.serve.json/tsconfig.json': Unexpected token u in JSON at position 0.

i found that running

> npm install typescript --save-dev 
will solve this error but it doesn't

**Comment by Rajdeep97** [comment]
Can't you try deleting nodejs, this project folder, install nodejs 14, clone this project and running non install... May fix the issue...

I downloaded a fresh copy and I don't have such problems.
