### ISSUE TITLE
app.quit() does not work when resizeable is true

### ISSUE THREAD

**Issue by Jeerrryyyy** [maximegris/angular-electron#585]
## Issue
When I set `resizeable: true` in the options of the BrowserWindow, it is not possible for me the close the app via `app.quit()`.
I was not sure if this is an Electron Issue or a Issue of this Boilerplate Template.

**Comment by maximegris** [comment]
I think this a more an issue related to electron project than mine.

**Comment by Jeerrryyyy** [comment]
Hey, I already found a solution and maybe the reason why this is happening. `app.quit()` needs all windows to be close before closing the main window and killing the application. Somehow it should give you a prompt where you can deceide if you want to close it. This promt never showed up. My solution now is, to get all Child Windows of the main window, iterate through them with forEach and close them. Now `app.quit()` does its job and closes the application. As a possible solution you also can use `app.exit()` but I was not sure if thats the best way to go. 

I will close this as it is not an issue of your project. Thanks for your work tho. Its a very nice project!
