### ISSUE TITLE
ESLint: Parsing error

### ISSUE THREAD

**Issue by shifatul-i** [maximegris/angular-electron#586]
Creating a simple `ts` file (i.e animations.settings.ts) throws `Parsing error`

![image](https://user-images.githubusercontent.com/3328263/111890769-f4888c80-89a9-11eb-95d9-1d33cf84cbb1.png)

![image](https://user-images.githubusercontent.com/3328263/111890792-31ed1a00-89aa-11eb-812d-1d33f8b07918.png)

**Comment by maximegris** [comment]
Hi

This commit should fix your issue : https://github.com/maximegris/angular-electron/commit/08ce0221aa2344d8e4117f3760b1efb8e9bea3c2
