### ISSUE TITLE
Hot reloading takes about 4000ms to 5000ms

### ISSUE THREAD

**Issue by NetJagaimo** [maximegris/angular-electron#589]
When I using `npm start` to run for development, it took about 4000ms to 5000ms for hot reloading.
Is that normal?
I didn't change anything to it.

My environments:
OS: macOS 10.15.7
Node: v14.16.0
npm: 7.7.6

**Comment by NetJagaimo** [comment]
I took some research about it, it seems like some settings in the `angular.json` cause hot reloading takes time so long.
I took these three settings (aot, extractLicenses, vendorChunk) out and it reloads so fast.
Not sure why we need these settings when developing.
`
"architect": {
  "build": {
    "configurations": {
      ......
      "web": {
          "aot": false,
          "extractLicenses": true,
          "vendorChunk": false,
      }
     ......
  }
}
`

**Comment by MuizMahdi** [comment]
@NetJagaimo Maybe create a PR?

**Comment by Rajdeep97** [comment]
@NetJagaimo : aot, extractLicenses, vendorChunk must be there in prod build not on dev build.

**Comment by maximegris** [comment]
Here is the hot reload time duration with current `angular.json` on my laptop (Windows 10)

```bash
√ Browser application bundle generation complete.

Initial Chunk Files | Names |    Size
main.js             | main  | 4.77 MB

3 unchanged chunks

Build at: 2021-05-30T11:07:07.492Z - Hash: b476b17ae227486572d9 - Time: 929ms

√ Compiled successfully.
```

**You can speed up the compilation time by setting `sourcemap` option to `false`  but it might be more difficult to debug your source code if you do that. (see compilation time below)** 

```bash
√ Browser application bundle generation complete.

Initial Chunk Files | Names |    Size
main.js             | main  | 4.77 MB

3 unchanged chunks

Build at: 2021-05-30T11:12:24.063Z - Hash: c3b9a30bb1d4bb02c299 - Time: 194ms

√ Compiled successfully.
```
