### ISSUE TITLE
[feature-request] Add support for auto updates

### ISSUE THREAD

**Issue by okonon** [maximegris/angular-electron#59]
@maximegris it would be really nice if you could add support for "auto updates" ! Maybe using something like `electron-builder` that accordingly to their documentation *A complete solution to package and build a ready for distribution Electron app with “auto update” support out of the box * I am still new to Electron but learning fast maybe i can help with something

**Comment by maximegris** [comment]
Hi @okonon 
Auto update of Electron app is not in the current scope of this sample. 
Unfortunately I have no time to invest on this subject. Fell free to try to replace current building stack by `electron-builder` in your project :)

**Comment by abruneau** [comment]
We could take example on [electron-webpack](https://github.com/electron-userland/electron-webpack).
I like the way it separates `main` and `renderer`

**Comment by maximegris** [comment]
Feel free to make a pull request on the project. :)

**Comment by maximegris** [comment]
#86
