### ISSUE TITLE
Where to place "ipcMain" processes or files... 

### ISSUE THREAD

**Issue by vimes1984** [maximegris/angular-electron#590]
I've been trying to tackle this for the last couple of hours and can't wrap my head around it. 
I have this in a component: 
```
        testfunc (){
          alert('test');
          let electronService = new ElectronService();
          electronService.ipcRenderer.send('testFunc', 'test');
        };
```

I can place in my main.ts file this: 
```
function testfuncServer(){
  ipcMain.on('testFunc', (event, arg) => {
    console.log(arg) // prints "Vagrant"
  });
}
testfuncServer();
````
And I WILL detect the change and log it to the console... my issue arises if I try to extract the last snippet from main.ts into another file... 
Where is the best place to put these functions, I really don't want a 600 line main.ts file...

**Comment by vimes1984** [comment]
Ok I fixed this like so:

I created a folder under app/details/server/server-calls.ts
I placed the following at the top of the file "var electron = require('electron');"
I included my code below:
electron.ipcMain.on('testFunc',function(event, arg){ console.log(arg); });

in my main.ts file I included it like so: require('./src/app/details/server/server-calls.ts'); This then runs on a click even on a button on the frontend: this.electronService.ipcRenderer.send('testFunc', 'test');

**Comment by vimes1984** [comment]
this still doesn't work when you compile the code it's self into a  .app for mac it errors out :(

**Comment by ShiJbey** [comment]
Thanks for asking this. I came across your question while dealing with the same problem. 

This is what I did:
1. Created a directory called **_main-process_** at the root of the project (at the same level as package.json, src, main.ts, etc.)
2. Changed the _**tsconfig.serve.json**_ file to include both the **_main-process_** directory and _**main.ts**_ file in the compilation. So, you remove the _**"files"**_ entry in the  _**tsconfig.serve.json**_ and replace it with an  _**"include"**_ entry (see examples below).
```JSON
// Before
{
  "compilerOptions": {
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "types": [
      "node"
    ],
    "lib": [
      "es2017",
      "es2016",
      "es2015",
      "dom"
    ]
  },
  "files": [
    "main.ts"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ]
}
```
```JSON
// After
{
  "compilerOptions": {
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "types": [
      "node"
    ],
    "lib": [
      "es2017",
      "es2016",
      "es2015",
      "dom"
    ]
  },
  "include": [
    "main.ts",
    "main-process/**/*"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ]
}
```
3.  Now, you should be able to place all your extra functionality inside the _**main-process**_ directory and import them into the root-level _**main.ts**_.

I hope this helps.

**Comment by vimes1984** [comment]
thanks @ShiJbey !!! this kind of works for me aswell... my issue now appears to be that it doesn't like me having third party node modules included... 
I'm using 
```include {sudo-prompt} from  'sudo-prompt'; and that now fails to be included in the compiled version :)

**Comment by maximegris** [comment]
Hi @vimes1984 

Please have a look at the MR https://github.com/maximegris/angular-electron/pull/611

It is how I migrate this project in order to use electron builder two package.json structure.
It will simplify how to import third party node modules in both main/renderer process.

**Comment by maximegris** [comment]
Hi @vimes1984 

Please have a look at the MR https://github.com/maximegris/angular-electron/pull/611

It is how I migrate this project in order to use electron builder two package.json structure.
It will simplify how to import third party node modules in both main/renderer process.
