### ISSUE TITLE
Current lint configuration doesn't find all files

### ISSUE THREAD

**Issue by agreeff** [maximegris/angular-electron#591]
**Describe the bug**

Running `ng lint` command does not check files located in all subfolders in the `src/` folder.

**To Reproduce**

1. clone project
2. change `src/app/app.module.ts`, intensionally breaking ESLint rules
3. run `ng lint`
4. output will show no errors found

**Expected behavior**

The `src/app/app.module.ts` file (as per steps above) should report a linting error.

**Screenshots**

Not sure if this is required, please let me know if it is..

**Additional context**

 - OS: "Pop!_OS 20.10" Linux
 - NodeJS: `v14.16.0`
 - NPM: `v6.14.11`

I did manage to fix the issue by changing both https://github.com/maximegris/angular-electron/blob/10065081de9261e82cababc71c25adbdcc77d87a/angular.json#L128 and https://github.com/maximegris/angular-electron/blob/10065081de9261e82cababc71c25adbdcc77d87a/angular.json#L144 from `{dir}/**.ts` to `{dir}/**/*ts`

Since this change is so small, I thought it would be easier to log an issue rather than forking, updating, and sending a PR... If you would prefer me to do this with a PR, I'm happy to oblige.

**Comment by maximegris** [comment]
Nice catch ! The issue is fixed. :)
