### ISSUE TITLE
Getting Error after packing for Mac

### ISSUE THREAD

**Issue by utd1878** [maximegris/angular-electron#596]
**Describe the bug**
After packing a Mac app, I get the following error:
![image](https://user-images.githubusercontent.com/5215011/114611951-c459a400-9c5e-11eb-9eb2-5549faf4d2c0.png)

**To Reproduce**
From electron-builder docs, run npm run electron-builder to package a mac app.  It technically packages the dmg and zip, but when running, I see the error from above.

**Expected behavior**
Should run without the error

**Screenshots**
See Above

**Additional context**
 - OS: Mac

Running npm start will bring up the electron app (browser fails to load) and function properly.
running npm run electron:local will result in the electron app not loading.

**Comment by utd1878** [comment]
I have this line in the main.js file: if (!AppConfig.production) which imported the environments folder....

**Comment by Thessalene** [comment]
I have the same error (with other file imported in main.ts file) and do not know how to solve it.
