### ISSUE TITLE
Angular Material Installation fail

### ISSUE THREAD

**Issue by xeinebiu** [maximegris/angular-electron#597]
:angular-electron-master arzan.nebiu$ ng add @angular/material
ℹ Using package manager: npm
✔ Found compatible package version: @angular/material@11.2.9.
✔ Package information loaded.
✖ Package installation failed: npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: angular-electron@9.0.7
npm ERR! Found: @angular/core@11.2.8
npm ERR! node_modules/@angular/core
npm ERR!   dev @angular/core@"11.2.8" from the root project
npm ERR!   peer @angular/core@"^11.0.0 || ^12.0.0-0" from @angular/material@11.2.9
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"11.2.9" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"11.2.10" from @angular/animations@11.2.10
npm ERR! node_modules/@angular/animations
npm ERR!   peer @angular/animations@"^11.0.0 || ^12.0.0-0" from @angular/material@11.2.9
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"11.2.9" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/arzan.nebiu/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:

**Comment by bakman23** [comment]
Have you resolved your problem ? because I installed material but I have no css displayed :(

**Comment by xeinebiu** [comment]
> Have you resolved your problem ? because I installed material but I have no css displayed :(

You need to import it on your styles.scss

**Comment by bakman23** [comment]
thanks for your response ! 
importing this do nothing : @import "../node_modules/@angular/material/theming.scss";

**Comment by bakman23** [comment]
it works with this !  @import "~@angular/material/prebuilt-themes/purple-green.css";
:D 
Thanks !!

**Comment by oderon-sp** [comment]
Can you elaborate how did you manage to install material via `ng add @angular/material` command?
Having the same error.

**Comment by xeinebiu** [comment]
> Can you elaborate how did you manage to install material via `ng add @angular/material` command?
> Having the same error.

I did not.

I installed it manually.

**Comment by oderon-sp** [comment]
Thanks.

I managed to install it via this approach:

1. Run `npm install --save @angular/material @angular/animations @angular/cdk **--legacy-peer-deps**` 
2. Then run `ng add @angular/material`.  <- actually I'm not sure it is necessary, but i remember i ran it.
3. Add to your global style.scss: `@import '~@angular/material/prebuilt-themes/indigo-pink.css';`

**Comment by crwgregory** [comment]
The [README says](https://github.com/maximegris/angular-electron#use-web-3rd-party-libraries-like-angular-material-bootstrap-) that you want to install the ui specific dependencies using the `--save-dev` flag because
> it will significantly increase the size of your final package
if not. Did you try that?

It doesn't look like the framework supports using `ng` to install dependencies but I haven't tried. The documentation is a little sparse when it comes to defining the best practices for dependency management and how it works :(

**Comment by nishant** [comment]
i am also having this same issue with @angular/forms as well

**Comment by maximegris** [comment]
Angular Materials installation was added in README (Thanks to @Rajdeep97 )

**Comment by ArmandoPerdomo** [comment]
> Thanks.
> 
> I managed to install it via this approach:
> 
> 1. Run `npm install --save @angular/material @angular/animations @angular/cdk --legacy-peer-deps`
> 2. Then run `ng add @angular/material`.  <- actually I'm not sure it is necessary, but i remember i ran it.
> 3. Add to your global style.scss: `@import '~@angular/material/prebuilt-themes/indigo-pink.css';`

I try this and it works for me

Thats the manual installation of material
