### ISSUE TITLE
Import Fonts and assets

### ISSUE THREAD

**Issue by abruneau** [maximegris/angular-electron#6]
I'm having trouble importing fonts and assets.
I'm having the error `URL.startsWith is not a function`
When I print the `URL` I get this : 

```
{ url: '~ionicons/dist/fonts/ionicons.eot?v=3.0.0-alpha.3',
  pathname: '~ionicons/dist/fonts/ionicons.eot',
  absolutePath: '/Users/abruneau/GitHub/Cmp2_Angular4/src/app/~ionicons/dist/fonts/ionicons.eot',
  relativePath: '~ionicons/dist/fonts/ionicons.eot',
  search: '?v=3.0.0-alpha.3',
  hash: '' }
``` 

This is when I try to do `@import "~ionicons/dist/scss/ionicons";`

**Comment by maximegris** [comment]
Hi,

There was en error in the method `postcssUrl` of the webpack config file generated by angular-cli. 

I juste fixed it and also add an example of an image assets (see `app.component.scss`)

About ionic icons, there are some issues with webpack (like this one https://github.com/driftyco/ionicons/issues/436)

I made it work by override ioniccons variables like that in `styles.scss`

```sass
$ionicons-version: ""; // Temporaly fix issue 436
$ionicons-font-path: "~ionicons/dist/fonts/"; // There is also an error with relative root path defined in ionicons-variables.scss with the current webpack config
@import "~ionicons/dist/scss/ionicons";
```
 
Maybe it's not the cleanest solution but it's working with elelectron (I checked in dev & prod configuration). Feel free to edit webpack config by yourself to import Ionic Icons in the best way.

Regards
