### ISSUE TITLE
Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning.ts(1219)

### ISSUE THREAD

**Issue by varadero** [maximegris/angular-electron#601]
**Describe the bug**

Same as this one - https://github.com/maximegris/angular-electron/issues/567  but it happens to me in both VSCode and Visual Studio - same error "Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning. ts(1219)" when you open any component.

**To Reproduce**
1. Clone this repository
2. npm install
3. Open with VSCode or Visual Studio 
4. Open home.component.ts or any other component TypeScript file
5. The name of the component class is underlined with red lines - hovering over the name shows error "Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning.ts(1219)"

**Expected behavior**
No errors

**Screenshots**
![image](https://user-images.githubusercontent.com/7610713/115608590-26657980-a2ef-11eb-8514-f9d54cb629ad.png)

**Additional context**
 - OS: Windows 10
 - NodeJS v14.15.5

**Comment by daerogami** [comment]
Found this solution for VSCode: https://ihatetomatoes.net/how-to-remove-experimentaldecorators-warning-in-vscode/

```
In VSCode go to preferences -> settings, you will see an option to enable/disable experimentalDecorators. Check it and save the settings file. Done
```

Just a workaround until a proper fix comes along, but it should serve to make development less annoying.

**Comment by borisBelloc** [comment]
I have exactly the same problem after cloning this repo...

Did you find a real solution? 
I don't think we are supposed to disable an option inside VScode preference...
![image](https://user-images.githubusercontent.com/37147299/118301445-574a6000-b4e3-11eb-8c54-8525c874d1d1.png)

**Comment by Lakston** [comment]
Same problem here, and I agree that disabling warnings in IDEs is a great workaround, especially if you work in a team

**Comment by koraykural** [comment]
Adding following line to the `.vscode/settings.json` worked for me:

`"js/ts.implicitProjectConfig.experimentalDecorators": true`
