### ISSUE TITLE
Request: Make this project ready for production following electron security best practices 

### ISSUE THREAD

**Issue by symis84** [maximegris/angular-electron#602]
The following Electron security best practise is to use a context bridge,  disabling  remote module, disabling node integration and enabling context isolation. 
In this scenario, it's obvious the developer needs to spend more effort on the electron side of the project because he needs to write there all the middle-layer logic to interact with node_modules libraries.

It's up to the user to setup this kind of settings but one useful thing we can add to this repository is the possibility to bundle the electron source files. 
Using the current version of this project i'm able to unpack the .asar file and to see all the electron source files.
 
Should be nice to use for example Rollup to bundle only the user electron .ts/js files.

If you agree on this feature request i will create a PR for that.

**Comment by Rajdeep97** [comment]
@symis84 : This is a interesting topic which I have not been able to find good articles of, do you have some link, from which we can read up and find the best practices in Electron?

**Comment by maximegris** [comment]
Hi @symis84 

I totally agree with you, it should be nice to bundle electron source in one way or another.

Your PR is welcomed :) Tell me if you want to any kind of help.
