### ISSUE TITLE
How should I install a package ? "Cannot set property '@electron/remote' of null"

### ISSUE THREAD

**Issue by borisBelloc** [maximegris/angular-electron#606]
**Describe the bug**

Hello :wave:

When I try to install [ng-bootstrap](https://ng-bootstrap.github.io/) with this command : 
`npx ng add @ng-bootstrap/ng-bootstrap`
There is an error message: `Cannot set property '@electron/remote' of null`

```
$ npx ng add @ng-bootstrap/ng-bootstrap
ℹ Using package manager: npm
✔ Found compatible package version: @ng-bootstrap/ng-bootstrap@9.1.1.
✔ Package information loaded.
✔ Package successfully installed.
Cannot set property '@electron/remote' of null
```
![image](https://user-images.githubusercontent.com/37147299/118357060-6e875d00-b578-11eb-968f-d2a83b6ae047.png)

**To Reproduce**
1. Clone repo
2. `npm i`
3. `npx ng add @ng-bootstrap/ng-bootstrap`

:mega: Any idea how can I fix this problem ? I don't find anything with Google.
I'm trying this command because I have seen here : https://github.com/maximegris/angular-electron/issues/554 that maximegris tell to use `npx ng add ngx-bootstrap` to install `ngx-bootstrap`

Edit : When I read the angular-electron doc : 
`3rd party librairies used in electron's renderer process (like angular) have to be added in devDependencies of package.json`

Does it mean am I supposed to install ng-bootstrap with this command : `npm install @ng-bootstrap/ng-bootstrap --save-dev` ?
I don't have any error messages when using this command.

:key: Can someone tell me what is the command to install a package on angular-electron ?
is it `npm install<package> --save-dev` or is it something else ?
I'm going to install bootstrap too, in a classic angular project, I would use `npm i bootstrap` should I use 
`npm i bootstrap  --save-dev` ?
 

thank you :beers:

**Additional context**

```
Angular CLI: 11.2.7
Node: 12.16.1
OS: win32 x64

Angular: 11.2.8
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.5
@angular-devkit/build-angular   0.1102.7
@angular-devkit/core            11.2.5
@angular-devkit/schematics      11.2.7
@angular/cli                    11.2.7
@schematics/angular             11.2.7
@schematics/update              0.1102.7
rxjs                            6.6.6
typescript                      4.0.5
```

**Comment by maximegris** [comment]
Hi

I just changed how electron & web dependencies are loaded in the final bundle (with electron builder two packages feature).

So I was able to move all angular deps in  `dependencies` section instead of `devDependencies` without increase final bundle size.

Now there is two package.json : 
*  in root folder => the one used by renderer process (ie. Angular)
* in app/ folder => the one used by electron main process (ie NodeJS)

`npx ng add @ng-bootstrap/ng-bootstrap` should now work.
