### ISSUE TITLE
Class was missing valueDeclaration -OR- non-class had no interface declarations when running build

### ISSUE THREAD

**Issue by pieterdb4477** [maximegris/angular-electron#610]
**Describe the bug**
When running build:dev npm crashes with the following error:
`Class was missing valueDeclaration -OR- non-class had no interface declarations`
This seems to be [caused by a bug in typescript v4.0.5](https://github.com/angular/angular-cli/issues/19317) and can be fixed by upgrading to v4.1.x (tested with v4.1.5)

**To Reproduce**
1. Clone the project
2. Run `build:dev`

**Expected behavior**
The build process succeeds and the /dist folder is succesfully created.

**Additional context**
 - node v14.17.0
 - npm v6.14.13
 - Windows 10 20H2
 - Ran from Jetbrains Webstorm 2021.1.1

**Comment by maximegris** [comment]
Hi @pieterdb4477 

Typescript version is now 4.1.5 on `angular11` branch 

`master` branch was updated to angular 12.
