### ISSUE TITLE
Electron Builder doesn´t work - Cannot find module 'serialport'

### ISSUE THREAD

**Issue by mrtglez** [maximegris/angular-electron#612]
**Describe the bug**
When I use electron-builder I can't import serialport:

Uncaught Exception:
Error: Cannot find module 'serialport'

But with npm start or electron . it works.

**To Reproduce**
1. Install serialport
2. Build with electron rebuilder

**Additional context**
 - OS: Ubuntu

**Comment by Leonardonline** [comment]
Try to take a look here: https://github.com/maximegris/angular-electron#how-to-import-3rd-party-libraries
