### ISSUE TITLE
Material elements not recognized (after manual install of @angular/material)

### ISSUE THREAD

**Issue by sneaker102** [maximegris/angular-electron#613]
**Describe the bug**
Installing material with ng add @angular/material throw error: 
could not resolve dependency tree,
manual install: 
npm install --save @angular/material @angular/cdk
ng add @angular/material
(✔ Packages installed successfully.
No project index HTML file could be found.)

**To Reproduce**
1. Clone repo and build
2. bash: ng add@angular/material
3. manual install material
4. npm run electron:local =>
     Error: src/app/home/home.component.html:8:1 - error NG8001: 'mat-card' is not a known element: 
     1. If 'mat-card' is an Angular component, then verify that it is part of this module.
      2. If 'mat-card' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this 
     component to suppress this message.

**SHARED MODULE**
@NgModule({
  declarations: [PageNotFoundComponent, WebviewDirective],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [CommonModule, TranslateModule, FormsModule, MatCardModule,
    MatButtonModule],
  exports: [TranslateModule, WebviewDirective, FormsModule]
})
export class SharedModule { }

**HOME MODULE**
@NgModule({
  declarations: [HomeComponent],
  imports: [CommonModule, SharedModule, HomeRoutingModule]
})
export class HomeModule {}

**HOME HTML**
  Contains only button (mat-raised-button) and mat-card empty

**Comment by maximegris** [comment]
I think you need to add `MathCartModule` and `MatButtonModule` in the exports of `SharedModule` to make them available in `HomeModule`

**Comment by Ross-Patterson** [comment]
I'm seeing this issue also. After installing using:

`ng add @angular/material`

I get: "No project index HTML file could be found"

Trying to use any material component (with relevant Mat Module imported into the module), I don't get the material styling.
