### ISSUE TITLE
@electron/remote not bundled into final build

### ISSUE THREAD

**Issue by vincios** [maximegris/angular-electron#615]
**Describe the bug**
If I try to use Electron remote, once I build the application I get this error into the renderer process (and the application won't load)

```
ERROR Error: Cannot find module '@electron/remote'
```

because Angular doesn't include `@electron/remote` into the final bundle.

**To Reproduce**
1. Clone the repo
2. Uncomment lines referred to remote into `electron.service.ts` (lines 31-32)
3. Run `electron:build` script
4. Launch the final binary and open the Developers Console

**Expected behavior**
The application should run normally and `globalShortcut` object sholud be logged into the console.

**Additional context**
 - OS: Windows 10

**Workaround**
As workaround I've manually added `@electron/remote` to the final bundle.

```json
// --> in electron-builder.json

"extraResources": [
  {
    "from": "dist",
    "to": "dist",
    "filter": [
      "**/*"
    ]
  },
  {
    "from": "node_modules/@electron/remote",
    "to": "node_modules/@electron/remote",
    "filter": [
      "**/*"
    ]
  }
]
```

Now application works, but I don't know if there is a more cleaner solution.

**Comment by maximegris** [comment]
This project use [electron builder two package.json structure](https://www.electron.build/tutorials/two-package-structure)
Did you install 3rd party libraries used by Electron main renderer before building your app ?

```
cp app/
npm install
```

**Comment by vincios** [comment]
Hi, thanks for the quick reply.

Yes, I have followed the readme but the issue still occours.
Also, the issue occours with the "vanilla" version of the template. I haven't added any other 3rd party libraries, nor I have made any changes (except uncommenting lines 31-32 into `electron.service.ts`).

Seems like it is a folder structure issue, in fact the packaged binary looks like this

```
unpacked_exe
|---...
|---resources
     |---...
     |--- app.asar
           |---...
           |--- node_modules
                 |---@electron
                       |---remote    <-- remote is here
     |---dist
           |--- main....js <-- angular main (executed by renderer process) is here, so it cannot find remote into app.asar
           |---...
```

Uncommenting

```
this.remote = window.require('@electron/remote');
```

in `electron.service.ts`, Electron starts looking for node_modules folders from the dist folder (where main.js is located) going upward (and not downward into app.asar), so it can't reach the module.
In fact, if I manually put another node_modules folder next to the dist folder, then Electron finds the remote module and runs normally.

Maybe, manually adding the node_modules folder to the paths, like [this doc page](https://www.electron.build/tutorials/loading-app-dependencies-manually) says, could work but the warning on the top says to use this approach only in a development environment so I haven't tried it.

**Comment by maximegris** [comment]
You're right.

According to Electron builder documentation `Node modules, that must be unpacked, will be detected automatically, you don’t need to explicitly set asarUnpack`

I had to make some changes with `electron-builder`. 
Have a look at 1fb08a7 and https://github.com/maximegris/angular-electron#how-to-import-3rd-party-libraries

**Comment by vincios** [comment]
Sorry for the late reply.
I've tested on a test project right now and it works perfectly. In the next days I'll implement the fix on my main project.

For now, i think the issue can be closed.
Thanks!
