### ISSUE TITLE
How to integrate electron store into angular-elctron project ?

### ISSUE THREAD

**Issue by Karim-Oodrive** [maximegris/angular-electron#617]
**Is your feature request related to a problem? Please describe.**
I'am a confirmed Angular Developer and today, I'am working on an angular-electron project for the first time, 
So, I search for how to store user Data, and I found that  the most used package for this was electron-store:
https://www.npmjs.com/package/electron-store
I want to integrate electron-store in my application, but I didn't know from where should I start ?
When I do :
```
const Store = require('electron-store');
const store = new Store();
```
I always get many errors

**Describe the solution you'd like**
I want to have this electron store in ElectronService that you have created for us

**Additional context**
Please give me a response, that will help me a lot, I'am so pressed with this project! thanks.

**Comment by leonardodimarchi** [comment]
I've been having a similar issue when trying to use Tray or Notifications. I think we need to use the `remote` (depreceated) or the `ipcRenderer` along with `ipcMain` to communicate between your UI and the electron process. Maybe you can find this useful: https://morioh.com/p/4654ccaed433 and https://www.electronjs.org/docs/api/remote
