### ISSUE TITLE
E2E Test Not Working

### ISSUE THREAD

**Issue by traviscollins** [maximegris/angular-electron#619]
**Describe the bug**
Using an unmodified copy of the current master branch, the e2e test fails to execute with the following output

```
  1) angular-electron App
       "before each" hook for "creates initial windows":
     TypeError: Cannot read property 'client' of undefined
      at Context.<anonymous> (e2e/main.e2e.ts:13:23)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**To Reproduce**
1. Pull latest from master
2. `nvm use 16`
  - Now using node v16.4.0 (npm v7.19.0
3. `npm i`
4. `cd app`
5. `npm i`
6. `cd ..`
7. `npm run e2e`

**Expected behavior**
E2E to run and pass. 

**Additional context**
 - OS: MacOS 11.4

I tried with Node 14 and Node 16, same results. Just before the test failure, I see a flash of the electron app window appear and disappear. 

`this.app` is undefined on main.e2e.ts line 1

**Comment by traviscollins** [comment]
Full console output....

```
npm run e2e

> angular-electron@10.0.1 e2e
> npm run build:prod && cross-env TS_NODE_PROJECT='e2e/tsconfig.e2e.json' mocha --timeout 300000 --require ts-node/register e2e/**/*.e2e.ts


> angular-electron@10.0.1 build:prod
> npm run build -- -c production


> angular-electron@10.0.1 build
> npm run electron:serve-tsc && ng build --base-href ./ "-c" "production"


> angular-electron@10.0.1 electron:serve-tsc
> tsc -p tsconfig.serve.json

✔ Browser application bundle generation complete.
✔ Copying assets complete.
✔ Index html generation complete.

Initial Chunk Files               | Names         |      Size
main.e3ac8ff7631a920c0a4c.js      | main          | 271.24 kB
polyfills.94addb3a924b619bd04f.js | polyfills     |  39.64 kB
runtime.0ff2802b9cc4abc4145c.js   | runtime       |   1.02 kB
styles.f67515cbb1c850daff53.css   | styles        | 661 bytes

                                  | Initial Total | 312.55 kB

Build at: 2021-06-25T14:19:24.700Z - Hash: 9e42a9eb31e063a50aa6 - Time: 19956ms


  angular-electron App
    1) "before each" hook for "creates initial windows"


  0 passing (3s)
  1 failing

  1) angular-electron App
       "before each" hook for "creates initial windows":
     TypeError: Cannot read property 'client' of undefined
      at Context.<anonymous> (e2e/main.e2e.ts:13:23)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by maximegris** [comment]
Hi

This is now fixed on master branch. (https://github.com/maximegris/angular-electron/commit/742095f13265c69efdaee1dd50ee3812ef7dae7f)

It was due to arrow functions in `e2e` files and a wrong path used by `Spectron` after moving `NodeJS` files in `app` folder.

**Comment by traviscollins** [comment]
@maximegris Thanks! I was working towards that assumption as well. 

Should the e2e tests be executed in the GitHub Action workflows? (Just to ensure they're maintained over time)

**Comment by maximegris** [comment]
I just added both unit tests and e2e tests steps in the GitHub Actions.

**Comment by traviscollins** [comment]
Awesome. Thanks again. Looking for the tip jar.
