### ISSUE TITLE
Error trying to close/dismiss MatDialog or MatSnackBar

### ISSUE THREAD

**Issue by ArmandoPerdomo** [maximegris/angular-electron#624]
**Describe the bug**
When I invoque the snackbar, i can't close with the dismiss button or when the duration ends doesn't close
Same with the dialog, I wont able to close with "mat-dialog-close" directive in a button

**To Reproduce**
1. Install Angular Material 
2. Import MatDialogModule and MatSnackbarModule
3. Inject them in a component
4. Invoque matDialog or the matSnackbar

**Expected behavior**
Be able to close as they should

**Screenshots**

Dialog:
![dialog-not-closing](https://user-images.githubusercontent.com/34519377/125108769-7b27bd80-e0b0-11eb-8faa-0b4321c3c1c7.gif)

Snackbar
![snackbar issue](https://user-images.githubusercontent.com/34519377/125109568-8a5b3b00-e0b1-11eb-8223-e10d96e96883.gif)

**Additional context**
 - OS: Windows
 - Angular: 12.0.2
 - Angular Material: 12.0.4
 - ELectron: 13.0.1

**Comment by ArmandoPerdomo** [comment]
I tried running wrapped in ng zone but it doesn't work

`
constructor(
    private ngZone: NgZone
    private dialog: MatDialog
  ) { }


ngOnInit(){
   this.ngZone.run( () =>  this.dialog.open(MyComponent) );
}
`

**Comment by Rajdeep97** [comment]
Hi,
We use both the components and it works perfectly for us. Please debug your code and check what's the error that's not letting it close. Add 'debugger' statement to close dialog method and see.
