### ISSUE TITLE
Can't install angular material with the theme

### ISSUE THREAD

**Issue by PavelRavvich** [maximegris/angular-electron#626]
Try to do `ng add @angular/material`

But get the error with the theme:

> Your global Angular CLI version (12.1.1) is greater than your local version (12.0.5). The local Angular CLI version is used.
> 
> To disable this warning use "ng config -g cli.warnings.versionMismatch false".
> i Using package manager: npm
> √ Found compatible package version: @angular/material@12.1.2.
> √ Package information loaded.
> 
> The package @angular/material@12.1.2 will be installed and executed.
> Would you like to proceed? Yes
> √ Package successfully installed.
> ? Choose a prebuilt theme name, or "custom" for a custom theme: Pink/Blue Grey     [ Preview: https://material.angular.i
> o?theme=pink-bluegrey ]
> ? Set up global Angular Material typography styles? Yes
> ? Set up browser animations for Angular Material? Yes
> UPDATE package.json (3632 bytes)
> √ Packages installed successfully.
> Your project is not using the default builders for "build". The Angular Material schematics cannot add a theme to the workspace configuration if the builder has been changed.

How I can install angular material with a normal theme?

**Comment by PavelRavvich** [comment]
I try to add `import '@angular/material/prebuilt-themes/pink-bluegray.css'` but get an error

> ./src/styles.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
> ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
> SassError: expected selector.
>   ╷
> 1 │ import "@angular/material/prebuilt-themes/pink-bluegray.css"
>   │        ^
>   ╵
>   src\styles.scss 1:8  root stylesheet
>     at processResult (C:\Users\pavel\projects\copy-trade\client\node_modules\webpack\lib\NormalModule.js:701:19)
>     at C:\Users\pavel\projects\copy-trade\client\node_modules\webpack\lib\NormalModule.js:807:5
>     at C:\Users\pavel\projects\copy-trade\client\node_modules\loader-runner\lib\LoaderRunner.js:399:11
>     at C:\Users\pavel\projects\copy-trade\client\node_modules\loader-runner\lib\LoaderRunner.js:251:18
>     at context.callback (C:\Users\pavel\projects\copy-trade\client\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
>     at Object.callback (C:\Users\pavel\projects\copy-trade\client\node_modules\sass-loader\dist\index.js:54:7)
>     at Worker.<anonymous> (C:\Users\pavel\projects\copy-trade\client\node_modules\@angular-devkit\build-angular\src\sass\sass-service.js:134:25)
>     at Worker.emit (events.js:375:28)
>     at MessagePort.<anonymous> (internal/worker.js:216:53)
>     at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:399:24)
>     at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)
>

**Comment by PavelRavvich** [comment]
https://github.com/maximegris/angular-electron/blob/master/HOW_TO.md

**Comment by Abszissex** [comment]
For everyone who finds this. The documentation has a smaller error and will be fixed via https://github.com/maximegris/angular-electron/pull/648
