### ISSUE TITLE
Remove two package setup

### ISSUE THREAD

**Issue by kamcknig** [maximegris/angular-electron#628]
According to the Electron-builder documentation here https://electron.build/tutorials/two-package-structure.html, the two package structure is really no longer needed or necessarily recommended because electron-builder now handles dependencies properly.

**Describe the solution you'd like**
Update to only use a single package.json structure

**Comment by maximegris** [comment]
Hi

In order to build an optimized final bundle and to keep the `ng add` command working with `Angular`, we have to use the two package setup.

Otherwise we must move all web dependencies  (such Angular) in devDependencies section because they are not needed in the Electron application. Doing this breaks most of `ng add` commands.

**Comment by nikhilnxvverma1** [comment]
@maximegris 
I am migrating from an older build of your project and by now I have a huge codebase. The documentation on the 2 package.json is very poor IMO. 

First of all there is no "src/package.json". In the latest build, there is only:
/package.json
/app/package.json

Secondly, it's unclear what dependencies go where. The demarkation is vague. Previously, for better or worse, everything was housed under one single devDependency in one package.json. Now it has to be mentioned in separate places & probably duplicated around according to the documentation(if I understand correctly)

I guess, some good documentation would be nice. People like me usually come back to this starter template repo when upping their major releases. Usually there are a lot of breaking changes. Nevertheless, I am still a fan of this project.
