### ISSUE TITLE
How to get material working

### ISSUE THREAD

**Issue by KKHAN1991** [maximegris/angular-electron#63]
Hi,

i followed this guide https://alligator.io/angular/angular-material-2/.

created a new material.module.ts and imported the correct files. 

Thats all fine but when i change the styles.scss to include

```
@import '~https://fonts.googleapis.com/icon?family=Material+Icons';
@import '~@angular/material/prebuilt-themes/indigo-pink.css';
```
I get an error
```
ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./src/styles.scss
Module build failed: 
@import '~https://fonts.googleapis.com/icon?family=Material+Icons';
^
      File to import not found or unreadable: ~https://fonts.googleapis.com/icon?family=Material+Icons.
Parent style sheet: stdin
      in /home/khan/Projects/angular-electron/src/styles.scss (line 8, column 1)
 @ ./src/styles.scss 4:14-204
 @ multi ./src/styles.scss
Child html-webpack-plugin for "index.html":
     1 asset
       1 module

```

Tried also moving it to the app.component.scss but same problem.

Doesent seem like anything is working. How can i add material to this??

**Comment by syuria27** [comment]
Try import like this if using scss.
@import url('https://fonts.googleapis.com/icon?family=Material+Icons');

**Comment by maximegris** [comment]
In index.html, import Material Icons
<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> in <head></head> tag
