### ISSUE TITLE
Node modules inside app directory is not gitignored

### ISSUE THREAD

**Issue by nikhilnxvverma1** [maximegris/angular-electron#635]
I dont know if I am point out something obvious or just sounding stupid but **.gitignore** does not have an entry for `/app/node_modules`. I noticed this after merging my migrated branch with master and immediately getting 5000 new files showing up in my source control tracker of VS code

**Comment by leandrofreires** [comment]
https://github.com/maximegris/angular-electron/blob/4b44d8bd53f19c6657c96a5558d6a187432d4e54/.gitignore#L15 and run git rm --cached  app/node_modules

**Comment by nikhilnxvverma1** [comment]
> https://github.com/maximegris/angular-electron/blob/4b44d8bd53f19c6657c96a5558d6a187432d4e54/.gitignore#L15
> 
> and run git rm --cached app/node_modules

The existing line only captures node_modules in the parent directory. There is a node_module inside the app/ directory too. I am not quite sure what running `git rm --cached app/node_modules` does. Does it specifically make an entry in **.gitignore**
