### ISSUE TITLE
Angular build is not packed into the ASAR

### ISSUE THREAD

**Issue by mathudak** [maximegris/angular-electron#637]
**Describe the bug**
When enabling ASAR in the electron-builder.json, Angular application is not packed and the production build shows no UI.

**To Reproduce**
1. Go to 'electron-builder.json'
2. Chang property: "asar" from false to true => `"asar": true`
3. In the console, run `electron:build` and wait for a build to finish
4. Go to the folder containing the `release/win-unpacked/` and open angular-electron.exe
5. Electron client starts but no content is displayed

**Expected behavior**
Sample UI is displayed with working navigation between sample pages. Since the ASAR is recommended by the builder itself it would be nice if this options came right out of box.

**Additional context**
 - OS: WIN
 - when inspecting the asar using 7-zip extensions, it contains only the content of `app/` folder (the Electron package.json)

I believe there should be some quick solution to update build/pack config but so far I haven't find it.

**Comment by mathudak** [comment]
A question is, is it still a way to do it? Electron builder warns about not using ASAR and so far I wasn't able to figure out how to put contents of ``/dist`` folder to the ASAR. As if it was not supported or something

**Comment by DerAlo** [comment]
Workaround config in electron-builder.json:

`{
  "asar": true,
  "directories": {
    "output": "release/"
  },
  "files": [
    "**/*",
    "!**/*.ts",
    "!*.map",
    "!package.json",
    "!package-lock.json",
    "app"
  ],
  "extraResources": [
    {
      "from": "dist",
      "to": "../../../app",
      "filter": [
        "**/*"
      ]
    }
  ],`

**Comment by mathudak** [comment]
Unfortunately, this didn't work for me. I guess I should try multiple ``to:`` values

**Comment by labsforge** [comment]
I stumble into this too.. lost some time trying different setups, but I got it working, bottom line, if the file `package.json` and `main.js` its inside dist folder, and change the electron-builder.json to point to the dist folder, it should work ok.

**angular.json**, inside configurations:
```
"production": {
  .....
  "fileReplacements": [
    {
      "replace": "src/environments/environment.ts",
       "with": "src/environments/environment.prod.ts"
    }
  ],
  "assets": [
    {
      "glob": "package.json",
      "input": "app/",
      "output": "/"
    },
    {
      "glob": "main.js",
      "input": "app/",
      "output": "/"
    }
  ]
}
```

**electron-builder.json**
```
"asar": true,
"directories": {
  "app": "dist/",
  "buildResources": "app/build/",
  "output": "release/"
},
"files": [
  "**/*"
]
```
and remove the `extraResources`

Hope this helps.
