### ISSUE TITLE
Module not found errors

### ISSUE THREAD

**Issue by SECimon** [maximegris/angular-electron#638]
Hi,
I am a beginner with angular/electron and it seems like I am lacking basic understanding. 
Every package I try to install using npm is causing problems (I also don't understand the guide in readme, I cannot tell which is a NodeJS library and which a web library is). 

Depending on the package I try to install, I get one of the following errors: _Module not found: Error: Can't resolve 'crypto'_ (you can exchange crypto with util, fs, stream, ...)

**To Reproduce**
1. Clone repo
2. npm install --save dropbox
3. npm run ng:serve

> Error: Module not found: Error: Can't resolve 'crypto' in ...
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
> This is no longer the case. Verify if you need this module and configure a polyfill for it.
> 
> If you want to include a polyfill, you need to:
> 	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
> 	- install 'crypto-browserify'
> If you don't want to include a polyfill, you can use an empty module like this:
> 	resolve.fallback: { "crypto": false }
> 

> Error: Module not found: Error: Can't resolve 'util' in '/home/sl/Programming/Shares/angular-electron/node_modules/dropbox/dist'
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
> This is no longer the case. Verify if you need this module and configure a polyfill for it.
> 
> If you want to include a polyfill, you need to:
> 	- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
> 	- install 'util'
> If you don't want to include a polyfill, you can use an empty module like this:
> 	resolve.fallback: { "util": false }

I tried to add these lines in package.json:
```
  "browser": {
    "crypto": false
  }
```

How do I correctly install libraries?

**Comment by jmorrisIII** [comment]
@SECimon same here.

**Comment by SECimon** [comment]
@jmorrisIII I could partially solve the issue, but I am not sure whether this is the right solution as I got another error:

I added in angular.webpack.js the following lines
`
    config.resolve = {
        fallback: { 
            "path": require.resolve("path-browserify"),
            "crypto": require.resolve("crypto-browserify"),
        }
    };
`

and installed the mentioned packages (e.g. npm install crypto-browserify). 

However, now I get the following error messages:

> ./src/main.ts:3:0-45 - Error: Module not found: Error: Can't resolve './app/app.module' in '/.../angular-electron/src'
> 
> ./src/main.ts:4:0-56 - Error: Module not found: Error: Can't resolve './environments/environment' in '/.../angular-electron/src'

**Comment by wwwhack** [comment]
seems webpack removed a feature Electron relied on  ....
https://www.tallan.com/blog/2021/09/21/angular-12-and-electron-setup-with-webpack-5/?utm_source=rss&utm_medium=rss&utm_campaign=angular-12-and-electron-setup-with-webpack-5

**Comment by maximegris** [comment]
@SECimon `crypto` is a Node core module => `Dropbox` is what I call a `NodeJS library` 

As noticed @wwwhack you have to add `node-polyfill-webpack-plugin` this in your `angular.webpack.js` in order to make in work.

@SECimon @jmorrisIII  Please refer to this commit https://github.com/maximegris/angular-electron/commit/fa5b3b41d52b9bf3815e7412da2653fbd00e7058 and [README](https://github.com/maximegris/angular-electron#how-to-import-3rd-party-libraries)
