### ISSUE TITLE
Create, build and publish - app electron

### ISSUE THREAD

**Issue by nonodev96** [maximegris/angular-electron#642]
Hi, I am using this configuration to publish releases on github, with github actions, maybe it can be useful not to be uploading thousands of builds with each release.

Maybe you have to change the node version, the github secrets or some minor change.

[create-release.yaml](https://github.com/nonodev96/THUMDER/blob/dev/.github/workflows/create-release.yaml)

**Comment by maximegris** [comment]
Thanks, I will have a look at your github actions.
