### ISSUE TITLE
Works with electron@15.0.0 against @angular/*@12.2.8

### ISSUE THREAD

**Issue by sjsam** [maximegris/angular-electron#643]
Out of curiosity, I have used [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) to see if things would break when changing the major versions,

Glad to know that this recipe still works with  electron@15.0.0 against @angular/*@12.2.8  but with few workarounds:

- The `electron@remote` module had to be removed.
- The project code which relied on the same had to be removed

An update to later versions is suggested.

♥♥ Thanks a lot for this project, it is a real time saver. ♥♥

**Comment by vicpermir** [comment]
Any experience trying to move up to Angular 13 for faster compile times? I was planning to give it a try but I just don't have spare time lately.

**Comment by sjsam** [comment]
@vicpermir  Haven't tried with Angular 13.

**Comment by maximegris** [comment]
I am waiting to angular-eslint@13 before move up to Angular 13.

**Comment by vicpermir** [comment]
> 
> 
> I am waiting for angular-eslint@13 before moving up to Angular 13.

Thank you !

**Comment by maximegris** [comment]
Electron was upgrade to v15.
Waiting angular-eslint@13 before moving up to Angular 13.

I close the issue.
