### ISSUE TITLE
Angular Language Service not working properly

### ISSUE THREAD

**Issue by jmichiel** [maximegris/angular-electron#647]
**Describe the bug**
The Angular Language Service doesn't seem to find a proper config to work with

**To Reproduce**
1. Clone the repo
2. Open in VS Code
3. npm install
4. Open an Angular file (e.g. app.component.ts) and hover some code
5. Open the Output for the Angular Language Service to see

[Error - 3:15:59 PM] No config file for /home/xx/Git/angular-electron/src/app/app.module.ts

**Expected behavior**
No errors in the logs

It appears the service is only picking up the main 'tsconfig.json' file, and not the tsconfig.app.json

If you remove the
`  "include": [
    "src/**/*.d.ts"
  ],`
statement from tsconfig.json, it seems to get somewhere, but then none of the angularCompilerOptions are used.
Are they supposed to declared there then?

**Comment by Rajdeep97** [comment]
Same here.. Did anyone get any solution on this? 
@jmichiel @maximegris  any idea?

**Comment by maximegris** [comment]
Hi

* Remove `"include": [ "src/**/*.d.ts" ],`` in `tsconfig.json`
* Copy `angularCompilerOptions` section of `tsconfig.app.json` to `tsconfig.json`
* Remove `angularCompilerOptions` section in `tsconfig.app.json`

This should make Angular Language Service working in VsCode.

The above changes are applied on latest version of this project. (master branch)

**Comment by Rajdeep97** [comment]
@jmichiel check out the latest version
@maximegris This solved the issue. 👌 💯 
You rock!! ✨✨ Keep it up 😊
