### ISSUE TITLE
How can i get electron builder package work

### ISSUE THREAD

**Issue by UXDesigner2017** [maximegris/angular-electron#65]
i want to add electron builder package to this generator so i can generate AppImage for linux, windows installer for windows and else. 

https://github.com/electron-userland/electron-builder

**Comment by GBurgardt** [comment]
To create an installer for Windows I generate the program with 'npm run
electron:windows' and then create setup with Inno Setup. Maybe that will
serve you in the meantime!

**Comment by UXDesigner2017** [comment]
Thank you GBurgardt but this is the temporary solution i want to make full solution so my team can use it in the production

**Comment by maximegris** [comment]
Sorry i have no time for wiking on this project. 
If you really need electron-builder, you can add it on your project and submit a pull request. I'll try to merge it as soon as possible.
