### ISSUE TITLE
Replace Spectron with Playwright or other

### ISSUE THREAD

**Issue by FrancescoBorzi** [maximegris/angular-electron#651]
**Is your feature request related to a problem? Please describe.**

Spectron is going to be deprecated, see https://github.com/electron-userland/spectron/issues/1045 and https://github.com/electron-userland/spectron/issues/896

**Describe the solution you'd like**

We should replace it with another solution which is actively maintained

**Describe alternatives you've considered**

In the GitHub discussions above, several users suggested Playwright as an alternative and gave positive feedback about it.

https://playwright.dev/docs/api/class-electronapplication/

**Comment by maximegris** [comment]
Indeed Playwright seems to be a good fit and promising.

I will try to replace Spectron and also upgrade to Electron 15 during the weekend.

**Comment by maximegris** [comment]
Playwright is now used as end-to-end test runner. 
It is a simple integration of Playwright wich may need to be improved in future commit.
