### ISSUE TITLE
Update my angular-electron-based app to the latest version of angular-electron

### ISSUE THREAD

**Issue by FrancescoBorzi** [maximegris/angular-electron#656]
I created an app quite some time ago based on the angular-electron template:

https://github.com/azerothcore/Keira3

the template has been of great help, however with time the projects diverged and my project is no longer in sync with angular-electron.

I was wondering if there is a way I can update it because I'm no longer able to easily import features from angular-electron because the underlying configuration has too many differences now.

I'm sure I'm not the only one who is facing this issue, so it would be nice to have some standard update procedure in place.

**Comment by maximegris** [comment]
Is this because you are targeting es5 in `tsconfig.json` ?

**Comment by maximegris** [comment]
It seems we should add `"module": "commonjs",` in `tsconfig.serve.json` (used by npm script `electron:serve`) in order to make it works on recent version of NodeJS.

https://stackoverflow.com/questions/58384179/syntaxerror-cannot-use-import-statement-outside-a-module

**Comment by FrancescoBorzi** [comment]
@maximegris thanks, that helped (even though I'm still struggling with other errors..)

anyway, how can I easily keep up with the changes coming from angular-electron? is there an easy way to update my project to the latest version of angular-electron?

**Comment by FrancescoBorzi** [comment]
still a problem

**Comment by Rajdeep97** [comment]
What i do is, make a latest copy of this repo, then diff the new copy with old copy.... Then copy the changes and delete node modules and run npm install
