### ISSUE TITLE
Can't use npm packages with TS module import from Angular that uses NodeJS core module

### ISSUE THREAD

**Issue by laurentperroteau** [maximegris/angular-electron#657]
**Describe the bug**
I can't use 3rd party libraries with TS module import from Electron's Renderer process (Angular) that uses NodeJS core module.

**To Reproduce**
1. `npm install fs-extra --save`
2. `cd app && npm install fs-extra --save && cd ..`
3. Import package in app.component.ts: `import * as fsExtra from 'fs-extra';` (same problems with 3 others package that depend of 'fs')
4. Use it in app.component.ts :

```ts
fsExtra.copy('/tmp/myfile', '/tmp/mynewfile')
      .then(() => console.log('success!'))
      .catch(err => console.error(err));
```
5. `npm start`

**Errors**
```
./node_modules/graceful-fs/graceful-fs.js:1:9-22 - Error: Module not found: Error: Can't resolve 'fs' in '/home/.../angular-electron/node_modules/graceful-fs'

./node_modules/jsonfile/index.js:10:8-21 - Error: Module not found: Error: Can't resolve 'fs' in '/home/.../angular-electron/node_modules/jsonfile'
```

**Additional context**
 - OS: Linux Ubuntu 20.04. LTS

_Thanks in advance for the help, I know is not anymore the recomend way to use Node library in the rendered context but my app start with this template 5 years ago in this way_

**Comment by maximegris** [comment]
Please have a look at [README.md](https://github.com/maximegris/angular-electron#how-to-import-3rd-party-libraries)

electron.service.ts
```typescript
[...]
import * as fsExtra from 'fs-extra';

@Injectable({
  providedIn: 'root'
})
export class ElectronService {
  [...]
  fsExtra: typeof fsExtra;

  [...]

  constructor() {
    // Conditional imports
    if (this.isElectron) {
      [...]
      this.fsExtra = window.require('fs-extra');
    }
  }
}

```

app.component.ts 
```typescript
 if (electronService.isElectron) {
      electronService.fsExtra.copy('/tmp/myfile', '/tmp/mynewfile')
            .then(() => console.log('success!'))
            .catch(err => console.error(err));
}
```

This works.

**Comment by laurentperroteau** [comment]
Thanks, so if another person is in the same case: it is no longer possible (it was at least until v6.0.1) to import packages which depend on core Node like any browser package.
