### ISSUE TITLE
Configure project to not write transpiled js files to disk

### ISSUE THREAD

**Issue by hemmoleg** [maximegris/angular-electron#658]
Hi,

how can I make it so the transpiled js files are stored in memory during runtine during development? I dont mean just running ng serve. I want to run both the 'elctron backend' as well as the 'angular frontend' without having all the transpiled files written to the hard drive.

thanks in advance :)

**Comment by maximegris** [comment]
Hi

You can use `ts-node` instead of `tcs` to transpile Typescript files in memory.
There are some online tutotial => https://dev.to/michaeljota/electron-with-typescript-using-ts-node-8oi
