### ISSUE TITLE
isElectron  not work in ElectronService

### ISSUE THREAD

**Issue by Exclamation-mark** [maximegris/angular-electron#659]
**Describe the bug**

the function `isElectron`  not work in `ElectronService`.

**To Reproduce**
1. set the `contextIsolation` is true in `main\main.ts`.
2. add the flowing code in the `index.html`
```html
  if (global === undefined) {
    var global = window;
  }
```
3. execute command `npm run electron:build`
4. open the electron app,see the console:
![image](https://user-images.githubusercontent.com/18455767/143183501-9ea3a85d-72cc-440e-a343-eaa2c9b7944e.png)

**Expected behavior**
shoule be log `Run in electron` in console.

**Screenshots**
![image](https://user-images.githubusercontent.com/18455767/143183592-2070db6d-f52e-4386-9d62-5c8b1125ff90.png)

**Additional context**
 - OS: [Windows 10]

**Comment by maximegris** [comment]
This project is actually not configured with contextIsolation set to true.

Changing contextIsolation breaks how electron is injected in the renderer global variable `window`.

It is not a bug, it is how works electron.
