### ISSUE TITLE
Add Builds to github release.yml

### ISSUE THREAD

**Issue by alex-w0** [maximegris/angular-electron#662]
**Is your feature request related to a problem? Please describe.**
I think it would be a good idea to extend the Github actions to add the Windows, MacOS and Linux builds automatically to the released tags. An user is then capable to download the executable file from the released tag.

**Describe the solution you'd like**
Create a .github/release.yml that will be executed on every git tag

**Comment by b0iq** [comment]
It would be awesome feature. Unfortunately am not sure how to do it but looking forward to hear from the others about it.
