### ISSUE TITLE
powerMonitor is undefined in electron service 

### ISSUE THREAD

**Issue by pappujmdweb** [maximegris/angular-electron#666]
**Describe the bug**
I am getting the powerMonitor undefined in electron service and as well in app.component.ts

![image](https://user-images.githubusercontent.com/87754814/147473849-f0f592b8-af0f-4f17-81b8-4599d35898ae.png)

This is the result of window.require('electron')
![image](https://user-images.githubusercontent.com/87754814/147473948-104f49bc-33e1-45ae-88f4-c795dcbc62aa.png)

I would like to access the powerMonitor API here but i am not able to access it.

**Comment by maximegris** [comment]
Hi

The powerMonitor Module is part of the Main Process. To import and use this Module in the Renderer Process, you have to use [@electron/remote module](https://www.npmjs.com/package/@electron/remote).
