### ISSUE TITLE
How to turn Hot Reload off?

### ISSUE THREAD

**Issue by letsbuildawebsite** [maximegris/angular-electron#667]
Hi, 

"name": "angular-electron",
"version": "4.2.2",

I've gone through everything and can't figure out how turn off hot reloading when a file saved... I really need this. 
The solution in the following comment is no good as this line does not include 'webpack:watch' in my package.json file. 
https://github.com/maximegris/angular-electron/issues/87#issuecomment-349627424

Mine has this: 
`"start": "npm run postinstall:electron && npm-run-all -p ng:serve electron:serve",`

**Comment by maximegris** [comment]
Hot reload is a default feature of angular. [Link here](https://angular.io/cli/serve)

In order to desable it, replace line 33 in `package.json`

``` 
"ng:serve": "ng serve -c web -o",
```
by 
``` 
"ng:serve": "ng serve -c web -o --live-reload false",
```

**Comment by letsbuildawebsite** [comment]
That doesn't disable it for me :( 
also, the line beginning "ng:serve" in my file looks like this: 
` "ng:serve": "ng serve",`
I tried adding "--live-reload false" to the end to make this:
`"ng:serve": "ng serve --live-reload false",`
But nothing. 

Also, line 33 in my package.json file is "test" not "ng:serve"
