### ISSUE TITLE
input

### ISSUE THREAD

**Issue by nicola86** [maximegris/angular-electron#669]
plese try this:
without any change!!

at home.component.html

    <div class="container">
      <h1 class="title">
        {{ 'PAGES.HOME.TITLE' | translate }}
      </h1>
      <input type="file" accept="image/*" (change)="setFile($event)">
      <a routerLink="/detail">{{ 'PAGES.HOME.GO_TO_DETAIL' | translate }}</a>
    </div>

when click ''input',app will be crash

**Comment by nikhilnxvverma1** [comment]
Not much info to go with but I would assume that the TranslateModule was not imported/setup/loaded causing the `translate` processor to fail

**Comment by nicola86** [comment]
> Not much info to go with but I would assume that the TranslateModule was not imported/setup/loaded causing the `translate` processor to fail

plese try this:

home.conponent.html  
`<div class="container">
  <h1 class="title">
    {{ 'PAGES.HOME.TITLE' | translate }}
  </h1>
  <input type="file" accept="image/*" multiple (change)="fileChange($event)"
  <a routerLink="/detail">{{ 'PAGES.HOME.GO_TO_DETAIL' | translate }}</a>
</div>`

when chick ''input',app will be crash
