### ISSUE TITLE
Issue with Firebase Integration

### ISSUE THREAD

**Issue by schnouz** [maximegris/angular-electron#674]
Hi there,

Firstly thanks for this template :)  I'm trying to use this template with Firebase / Firestore but go some issues.

I've installed "@angular/fire": "7.2.0", "firebase": "9.6.4".

Everything works fine with `npm run start`

The issue is when using `npm run electron:local` or `npm run electron:build`. If I set `nodeIntegration: false` and `contextIsolation: true` it does not work And I receive a require global is not defined. The problem seems to came from firebase that is choosing the nodejs package instead of the web one. 
Everything works great if I set `nodeIntegration: true` and `contextIsolation: false` but for security reason I prefer not too. Also because i'm using contextBridge I need to set `contextIsolation: true`.

Does anyone know how I can solve that issue ? Or maybe how I can update the webpack config to exclusively select the firebase web version?

**Comment by Aravindaful** [comment]
Did you find a way to resolve this? I also having same issue

**Comment by schnouz** [comment]
Unfortunately I do not find any solution. Let me know if you sort that out

**Comment by Aravindaful** [comment]
I wasted much hours for that and after that removed angular/fire.Then installed firebase npm package. After that it worked properly in electron build project too.

**Comment by schnouz** [comment]
@Aravindaful Which version of firebase are you using ? 
Because importing `getFirestore`  from `firebase/firestore` leads to the same error.
firebase/auth and firebase/messaging works with no issues otherwise.
