### ISSUE TITLE
Building and Running contents of /dist folder locally or via S3 Bucket

### ISSUE THREAD

**Issue by Vahid1310** [maximegris/angular-electron#675]
It seems that when building via the provided build commands (npm run build etc.) and then trying to host the contents of the /dist folder locally via http-server or online via an S3 Bucket an error prevents the app from loading.

Either you get a UncaughtReference Error: global is not defined or UncaughtReference Error: require is not defined.

This was tried on my cloned repo but also on the latest version of this project without any changes applied.

Is this an error on my end or is it not intended to run the built versions of the /dist folder?

**Comment by maximegris** [comment]
Hi @Vahid1310 

This commit 58424a2daaea9c35f60a928957e088f15e07fd0d should fix your issue.

Please run  `npm run web:build` in order to build assets for S3 Bucket deploiement.
