### ISSUE TITLE
Electron window running in web mode

### ISSUE THREAD

**Issue by ekimmerst** [maximegris/angular-electron#687]
When using the ElectronService, the line ...

```
if (this.isElectron) {
```

... always returns false and hence the conditional imports are skiped and I cannot use the ipcRender etc.

I launch via `npm start` and in the Electron console I get the following output:

![screenshot](https://user-images.githubusercontent.com/49347412/163181797-24eee961-bb16-43e6-9235-e9907b6ec57b.png)

What am I doing wrong?

**Comment by ekimmerst** [comment]
Some additional comment:

When I **disable** `contextIsolation`, it works as intended. However, I thought enabling `contextIsolation` is the recommended way for security reasons ...

**Comment by maximegris** [comment]
Hi @ekimmerst 

The actual isElectron function works with `contextIsolation` set to false. It checks some properties in the global window variable.

If you set `contextIsolation` to true, you have to follow  [the official documentation](https://www.electronjs.org/fr/docs/latest/tutorial/context-isolation) and change isElectron function with your exposed variables.

Enabling `contextIsolation` is the recommended way now. 
But it adds development constraints that I didn't want to have on this project. (ex: you can't use node libraries in the renderer process  if you don't expose them with electron context bridge)
I wanted it the easiest way to start for new commers  with Electron and Angular
