### ISSUE TITLE
angular-cli file don't import css/js files

### ISSUE THREAD

**Issue by raczak** [maximegris/angular-electron#7]
Hello,

First thanks for your nice job for having embedded angular 4 into electron. I currently have a problem for adding js and css script to my project using the angular-cli file.

I think nothing is detecting in angular-cli even I remove all the content. I tried to clone again your project but nothing work.

`"styles": [
        "styles.scss",
        "./node_modules/materialize-css/bin/materialize.css"
      ],`
even this to :
`"styles": [
        "styles.scss",
        "../node_modules/materialize-css/bin/materialize.css"
      ],`

`"scripts": [
          "test.js"
      ],`

Thx by advance for you help,

**Comment by maximegris** [comment]
Hi,

You don't need to update angular-cli.
You only need to import jquery & materialize-css like this:

```bash
npm install --save jquery materialize-css
```
It works with this sample :

In index.html, import <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> in <head<</head>

styles.scss
```sass
@import "~materialize-css/dist/css/materialize.css";
```
app.component.ts
```typescript
import { Component } from '@angular/core';
import $ from 'jquery'; // You need to import jquery before materialize-css if you want to use javascript 
import * as materialize from 'materialize-css';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = `App works !`;

  constructor() {
    // Check if materialize is correctly imported
    console.log('c', materialize);

    $(document).ready(function(){
      $('.carousel').carousel();
    });
  }
```

app.component.html
```html
<nav>
  <div class="nav-wrapper">
    <div class="col s12">
      <a href="#!" class="breadcrumb">First</a>
      <a href="#!" class="breadcrumb">Second</a>
      <a href="#!" class="breadcrumb">Third</a>
    </div>
  </div>
</nav>

<div class="carousel">
  <a class="carousel-item" href="#one!"><img src="http://lorempixel.com/250/250/nature/1"></a>
  <a class="carousel-item" href="#two!"><img src="http://lorempixel.com/250/250/nature/2"></a>
  <a class="carousel-item" href="#three!"><img src="http://lorempixel.com/250/250/nature/3"></a>
  <a class="carousel-item" href="#four!"><img src="http://lorempixel.com/250/250/nature/4"></a>
  <a class="carousel-item" href="#five!"><img src="http://lorempixel.com/250/250/nature/5"></a>
</div>
```

Regards

**Comment by raczak** [comment]
Thx for your answer :)
It's better now ! I also have 2 others questions :

I have a custom js script and unfortunately I need to reuse it in a template. How can I import it without using a : `<script src="myscripts.js"></script>` in the template.

The second problem is also related to the tempale : I want to know how can I display images in my template. For example in `index.html` I want to add a svg and a png image from my assets folder. But when I put the `<img>` tag with the correct path after a `webpack --watch` the image is not found. Webpack don't add my image to the dist folder. My assets are in `src/assets`.

Thank you by advance for your answer,

**Comment by jakehockey10** [comment]
Shouldn't putting it in angular-cli.json work?  Isn't that what angular-cli.json is for?

**Comment by maximegris** [comment]
Once `eject` command is used, you're not using the CLI as a build system anymore. Whatever is in angular-cli.json is irrelevant for builds.

**Comment by jakehockey10** [comment]
thanks for the clarification.

Great work by the way!
