### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by luislobo** [maximegris/angular-electron#70]
Can this project be used as the template of a future MIT licensed project?

What needs to be included in my project to be OK with you?

Thank you

**Comment by maximegris** [comment]
If you redistribute software with any Apache licensed components, you must include a copy of the license, provide a clear Apache License attribution, and add modification notices to all the files that you modify.

**Comment by luislobo** [comment]
Thank you!

**Comment by rm-code** [comment]
@maximegris Which components are covered by the Apache license? I thought this project uses the MIT license 😕

**Comment by rm-code** [comment]
Ah looks like you changed the license recently. I opened a PR which fixes the license badge in your README.md ... that's why I was so confused.

Also would be nice if you could tell me if the above license would be ok for you.

Cheers

**Comment by luislobo** [comment]
@maximegris thank you for updating the license. I was not using it just because of the Apache license.

**Comment by maximegris** [comment]
You're welcome :)
