### ISSUE TITLE
Request to upgrade to Angular v14

### ISSUE THREAD

**Issue by Cratis1831** [maximegris/angular-electron#705]
Request to upgrade to Angular v14

**Comment by Cratis1831** [comment]
@maximegris do you have any steps/guidelines to upgrade Electron and Angular for the project so that we can do it ourselves?

**Comment by Cratis1831** [comment]
I was able to update Angular/Electron with this package on npm easily

https://www.npmjs.com/package/npm-check-updates

**Comment by maximegris** [comment]
The project is now upgrade to Angular 14 & Electron 19 :)
Regards

**Comment by Cratis1831** [comment]
thanks @maximegris !
