### ISSUE TITLE
npm run test is not working on latest release

### ISSUE THREAD

**Issue by hassang11** [maximegris/angular-electron#706]
**Describe the bug**
Errors when trying to run npm run test

**To Reproduce**
- Download the project
- npm install
- npm run test

**Expected behavior**
- Should run the tests and return success 

**Screenshots**
![image](https://user-images.githubusercontent.com/46043458/180803829-19a3c63c-8541-4b97-b08f-a43cf824e974.png)

**Additional context**
 - OS: Windows
 - node : 14.15.0

---
I also tried to use a headless chrome

Steps

- npm install karma-chrome-launcher
- Modify karma.config to the following
`// Karma configuration file, see link for more information
// https://karma-runner.github.io/0.13/config/configuration-file.html

module.exports = function (config) {
    config.set({
        basePath: '',
        frameworks: ['jasmine', '@angular-devkit/build-angular'],
        plugins: [
            require('karma-jasmine'),
            require('karma-electron'),
            require('karma-chrome-launcher'),
            require('karma-jasmine-html-reporter'),
            require('karma-coverage-istanbul-reporter'),
            require('@angular-devkit/build-angular/plugins/karma'),
        ],
        client: {
            clearContext: false, // leave Jasmine Spec Runner output visible in browser
        },
        coverageIstanbulReporter: {
            dir: require('path').join(__dirname, '../coverage'),
            reports: ['html', 'lcovonly'],
            fixWebpackSourcePaths: true,
        },
        reporters: ['progress', 'kjhtml'],
        port: 9876,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: true,
        browsers: ['Chrome'],
        singleRun: false,
        customLaunchers: {
            AngularElectron: {
                base: 'Electron',
                flags: ['--remote-debugging-port=9222'],
                browserWindowOptions: {
                    webPreferences: {
                        nodeIntegration: true,
                        nodeIntegrationInSubFrames: true,
                        allowRunningInsecureContent: true,
                        contextIsolation: false,
                    },
                },
            },
        },
    });
};
`

- edit package .json 
`       "test": "ng test --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage",
        "test:watch": "ng test",`

- run npm run test or npm run test:watch

Result : 

![image](https://user-images.githubusercontent.com/46043458/180804617-0bbd882c-8dcf-4483-afac-685351fd91dc.png)

**Comment by maximegris** [comment]
The default project npm `test` command is `ng test --watch=false`. It works on my Windows 10 / Node 14.15.1

Your screenshots show commands with another parameters : `--no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage`. Please try with the default command `"test": "ng test --watch=false"`
