### ISSUE TITLE
ipRenderer.on doesnt see component variables

### ISSUE THREAD

**Issue by aleksey-hariton** [maximegris/angular-electron#709]
Sending event from `main.js`, Angular receiving event, but can see any component variables.
Looks like `ipcRenderer.on` dont see component variables, this example giving me `undefined` in console (using latest master from GitHub).

```
  public showProgress: boolean = false

  constructor(
    private es: ElectronService,
    ) { 
    }

  ngOnInit(): void {
    this.es.ipcRenderer.on("triedLogin", function (evt, success: boolean) {
      console.log(this.showProgress)
    })
  }
```

**Comment by ac566** [comment]
I may be wrong, but doesn't "function" have it's own "this" scope? It should work if you use arrow syntax

**Comment by maximegris** [comment]
Thanks @ac566, you're right :)
I close the issue.
