### ISSUE TITLE
Usage of `child_process` in renderer does not work

### ISSUE THREAD

**Issue by driehle** [maximegris/angular-electron#710]
**Describe the bug**
Using `require('child_process')` in the renderer, i.e. the angular application, provides the following error:

```
Module not found: Error: Can't resolve 'child_process'
```

**Problem**
The issue itself is clear, Webpack processes the scripts an replaces the require statement. However, technically due to `nodeIntegration` being set to true, this code should work, shouldn't it?

How wan we prevent Webpack from processing the import statement, or - probably even better - have third party libraries use the require of the `ElectronService` provided by this boilerplate?

**Comment by maximegris** [comment]
Please have a look at ElectronService.ts. I tryed on a clean repo and this works perfectly. `child_process` is correctly imported and can be used like this :

```typescript
      this.childProcess = window.require('child_process');

      this.childProcess.exec('node -v', (error, stdout, stderr) => {
        if (error) {
          console.error(`error: ${error.message}`);
          return;
        }

        if (stderr) {
          console.error(`stderr: ${stderr}`);
          return;
        }

        console.log(`stdout:\n${stdout}`);
      });
```
