### ISSUE TITLE
Unable to build with NodeJS 16

### ISSUE THREAD

**Issue by arcovoltaico** [maximegris/angular-electron#711]
Unable to build on MacOS Monterrey,  NodeJS 16

After upgrading from NodeJs 14 to 16 when I run
`npm run build:prod && npx electron-builder build --mac`

I get 
  ```
• installing production dependencies  platform=darwin arch=x64 appDir=/Users/a77/MyRepos/U-Vox 5/player3/app
  ⨯ /usr/local/bin/node process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
Error output:
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/a77/.npm/_logs/2022-08-10T13_18_01_940Z-debug-0.log
  failedTask=build stackTrace=Error: /usr/local/bin/node process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
Error output:
npm ERR! could not determine executable to run
```
I have tried removing hooks, node modules ... 
it happens even on a fresh fork of your repo.

Thanks for your help!

**Comment by maximegris** [comment]
`npm run build:prod` and `npm run electron:build` commands works well on NodeJS 16.15.0.

What is your exact version of NodeJS ? Is it `npm run build:prod` or `npx electron-builder build --mac` that returns an error ?
