### ISSUE TITLE
Asar for using ffmpeg

### ISSUE THREAD

**Issue by arcovoltaico** [maximegris/angular-electron#712]
Hi, as your last versions do not add the app.asar directory into the compiled app anymore. My app fails while trying to locate the ffmpeg executable.  To fix it I added `"asar": false, "asarUnpack": [ "node_modules/ffmpeg-static-electron" ],`  in the beginning of  `electron-builder.json`. The resulting compiled app not only still lacks this asar folder, but is unable to render anything leaving me with a white screen and an empty console.
Any idea how to tackle it?
Cheers

**Comment by maximegris** [comment]
Hi

According electron-builder documentation, when `asar` is set to `true`, Node modules, that must be unpacked, will be detected automatically, you don’t need to explicitly set [asarUnpack]. 
If you extract files of `app.asar` from `release/win-unpacked/resources` folder with `npx asar extract app.asar destfolder` command, you must have a `node_modules` folder with your npm dependencies. Don't forget to add you dependencies also in `app/package.json` (see two package structure of electron builder)

On your exemple, you have `asar` set to `false` with `asarUnpack`. I think this is a mistake but did you try with `asar` set to `true` ?

**Comment by maximegris** [comment]
`asar` is now set by defaut to `true`
Please refer to https://github.com/maximegris/angular-electron/commit/e1da5b51669f8cba5b048e38df7283aa914f95c0
