### ISSUE TITLE
Enable asar. Electron-builder keeps warning "asar usage is disabled — this is strongly not recommended"

### ISSUE THREAD

**Issue by heiba** [maximegris/angular-electron#713]
**Is your feature request related to a problem? Please describe.**

When packaging the app using `npm run electron:build`, I get a strong stern strong warning saying the following:

```
• asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
```
This is because we have `asar: false` in electron-builder.json

**Describe the solution you'd like**

Enable asar so that we don't get this warning when building the app.

**Describe alternatives you've considered**

I tried enabling asar, but the electron app wouldn't work. It would build, and run, but I get a blank screen.

**Additional context**

**Comment by gnujeremie** [comment]
This may help you https://github.com/maximegris/angular-electron/issues/627#issuecomment-886537006

**Comment by maximegris** [comment]
When `asar` is set to `true`, your `electron-builder.json` files must be like 

```json
{
  "asar": true,
  "directories": {
    "output": "release/"
  },
  "files": [
    "**/*",
    "!**/*.ts",
    "!*.map",
    "!package.json",
    "!package-lock.json",
    {
      "from": "../dist",
      "filter": ["**/*"]
    }
  ],
  "win": {
    "icon": "dist/assets/icons",
    "target": [
      "portable"
    ]
  },
  "portable": {
    "splashImage": "dist/assets/icons/electron.bmp"
  },
  "mac": {
    "icon": "dist/assets/icons",
    "target": [
      "dmg"
    ]
  },
  "linux": {
    "icon": "dist/assets/icons",
    "target": [
      "AppImage"
    ]
  }
}
```
