### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by nikita-fuchs** [maximegris/angular-electron#719]
after cloning and installing, running `npm start` errors for me:
```
> angular-electron@11.1.0 start
> npm-run-all -p electron:serve ng:serve

sh: /angular-electron/node_modules/.bin/npm-run-all: Permission denied
```

what permissions do I have to set?

Edit: solved by giving execution permission, `chmod +x /angular-electron/node_modules/.bin/npm-run-all`
Maybe this could be set on installation? :)

**Comment by maximegris** [comment]
It is more a bad Node installation than an issue linked to this project :)

Glad that you solved this error btw !
