### ISSUE TITLE
I can't install angular material

### ISSUE THREAD

**Issue by AbdoShiabany** [maximegris/angular-electron#720]
When i try `ng add @angular/material`
I get this

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: angular-electron@11.1.0
npm ERR! Found: @angular/core@14.0.6
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"14.0.6" from the root project
npm ERR!   peer @angular/core@"^14.0.0 || ^15.0.0" from @angular/material@14.2.0
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"14.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"14.2.0" from @angular/animations@14.2.0
npm ERR! node_modules/@angular/animations
npm ERR!   peer @angular/animations@"^14.0.0 || ^15.0.0" from @angular/material@14.2.0
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"14.2.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\User\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Local\npm-cache\_logs\2022-09-06T14_48_33_051Z-debug-0.log
✖ Packages installation failed, see above.

How to solve it?!

**Comment by Solvars** [comment]
@AbdoShiabany I had the same issue yesterday. The solution i found that worked for me was to update @angular/core first:
```
ng update @angular/core
```
