### ISSUE TITLE
Create a pro executable for Linux Mac Windows

### ISSUE THREAD

**Issue by EvilSpartans** [maximegris/angular-electron#722]
Hello, thanks for this amazing project! I would like to know how to create a pro executable for mac windows or linus (like we can do with normal electronJs app) ? Thanks for your answer!

**Comment by maximegris** [comment]
Hello @EvilSpartans , 

What do you mean by a "pro executable" ?
If you mean an ".exe" for Windows & co, you just have to run `npm run electron:build`.
The project currently builds an executable based on the OS you're running the above script.

However you can specify the build type by adding `--mac /  --linux / --win` at the end of the command line.
Exemple if you want to build an AppImage for Linux : `npm run electron:build -- --linux`
