### ISSUE TITLE
Worker Threads freeze the app

### ISSUE THREAD

**Issue by sabindev** [maximegris/angular-electron#731]
**Describe the bug**
I tried opening worker threads just like i would do using the normal electron but first thread i open freezes the app for 2-3 seconds and then 2nd thread permanently freezes the app.

**To Reproduce**
Create a new file worker.ts and add it to tsconfig.serve.json
Then open it  like this:
```
  ipcMain.on('synchronous-message', (event, args) =>{
    new Worker('./app/worker.js');
  })
```

**Additional context**
App just freezes and doesnt return an error

**Comment by nunoasfranco** [comment]
This is indeed happening to me as well, my app is freezing.

**Comment by sabindev** [comment]
Closing this cuz i found a way around by sending asynchronous-messages instead of synchronous
