### ISSUE TITLE
Adding angular material with ng add fails

### ISSUE THREAD

**Issue by lkuessner** [maximegris/angular-electron#733]
I'm using the latest angular-electron version (with angular 14) and trying to ng add @angular/material to my project which fails because of dependency issues.

Output:
```[lk-basic-template +0 ~8 -6 !]> ng add @angular/material
Your global Angular CLI version (15.1.1) is greater than your local version (14.2.6). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
ℹ Using package manager: npm
✔ Found compatible package version: @angular/material@7.0.0.
✔ Package information loaded.

The package @angular/material@7.0.0 will be installed and executed.
Would you like to proceed? Yes
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: sng-configurator@0.0.0
npm ERR! Found: @angular/core@14.2.6
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"14.2.6" from the root project
npm ERR!   peer @angular/core@">=7.0.0" from @angular/material@7.0.0
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"7.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"15.1.0" from @angular/animations@15.1.0
npm ERR! node_modules/@angular/animations
npm ERR!   peer @angular/animations@">=7.0.0" from @angular/material@7.0.0
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"7.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! C:\Users\lkuessner\AppData\Local\npm-cache\_logs\2023-01-17T10_05_48_930Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lkuessner\AppData\Local\npm-cache\_logs\2023-01-17T10_05_48_930Z-debug-0.log    
✖ Packages installation failed, see above.
```

How do I solve this issue?

**Comment by lkuessner** [comment]
Thanks but this results in this error log:

```
[lk-add-angular-material +0 ~3 -0 !]> ng add @angular/material
Your global Angular CLI version (15.1.1) is greater than your local version (14.2.6). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
ℹ Using package manager: npm
✔ Found compatible package version: @angular/material@15.1.1.
✔ Package information loaded.

The package @angular/material@15.1.1 will be installed and executed.
Would you like to proceed? Yes
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @angular-builders/custom-webpack@14.0.1
npm ERR! Found: @angular/compiler-cli@15.1.1
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   dev @angular/compiler-cli@"15.1.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler-cli@"^14.0.0" from @angular-builders/custom-webpack@14.0.1
npm ERR! node_modules/@angular-builders/custom-webpack
npm ERR!   dev @angular-builders/custom-webpack@"14.0.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/compiler-cli@14.2.12
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   peer @angular/compiler-cli@"^14.0.0" from @angular-builders/custom-webpack@14.0.1
npm ERR!   node_modules/@angular-builders/custom-webpack
npm ERR!     dev @angular-builders/custom-webpack@"14.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\lkuessner\AppData\Local\npm-cache\_logs\2023-01-19T08_38_41_223Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lkuessner\AppData\Local\npm-cache\_logs\2023-01-19T08_38_41_223Z-debug-0.log
✖ Packages installation failed, see above.
```

**Comment by 6matko** [comment]
Same issue here.

**Comment by ddubrava** [comment]
I don't know what's the expected approach, but for now you can use this schematic with some hacks.

1. Install dependencies manually. `npm install --save @angular/material@14.2.6 @angular/cdk@14.2.6 @angular/animations@14.2.6`. Specify your version, if it doesn't work try to use `--force`.
2. Temporarily replace `build.builders` in angular.json with `@angular-devkit/build-angular:dev-server`.
3. Run `ng add @angular/material`.
4. Revert `build.builders` changes.

**Comment by lkuessner** [comment]
@ddubrava Thanks for your solution. This kind of works until I want to choose a preset theme.
Choosing the "Indigo/Pink" theme for example results in this error message: 
`Your project is not using the default builders for "build". The Angular Material schematics cannot add a theme to the workspace configuration if the builder has been changed.`
Also there seems to be a problem regarding the addition of the Roboto font in the index.html because the ng add @angular/material command says in the end that he couldn't find a index.html file.

Do you have any solutions for that too? Thanks in advance

**Comment by ddubrava** [comment]
Hey! You should temporarily replace build.builders in angular.json with @angular-devkit/build-angular:dev-server. Otherwise, ng add fails

**Comment by lkuessner** [comment]
I did and it worked fine until the angular material configuration script asks me if I want to either use an preset theme like "indigo/pink" or custom theme.

The important part seems to be the second sentence in the error I posted previously which states:
"The Angular Material schematics cannot add a theme to the workspace configuration if the builder has been changed."

So I follow all of your steps and angular material can be succesfully installed but without prebuild themes and with the need of some additional steps because the index.html can't be found by the cli script in order to add the font and similars.

**Comment by ddubrava** [comment]
That’s kinda interesting since I’ve installed the theme using these steps. Try to change not only the build.builders but also serve.builders. Actually all non-default builders

**Comment by thibaud57** [comment]
Solutions below not working for me either :(

**Comment by maximegris** [comment]
Hi guys,

Thanks for your research :)

I have updated the [How to file](https://github.com/maximegris/angular-electron/blob/main/HOW_TO.md) about builders. Works fine on Angular 15.
