### ISSUE TITLE
Uncaught ReferenceError: global is not defined (ng test report is not loading)

### ISSUE THREAD

**Issue by kumarandena** [maximegris/angular-electron#734]
**Branch & Packages version used:**  Angular 14 & Electron 21 : (main)

**Issue:** The test output is not displaying in the browser using [Karma Jasmine HTML Reporter](https://github.com/dfederm/karma-jasmine-html-reporter)

![image](https://user-images.githubusercontent.com/30895291/213725819-8b07c34b-f93a-4017-9cac-af1f7d88a8be.png)

-----

**Steps:**

**npm run test:watch**

angular-electron-ngtestissue> npm run test:watch

> angular-electron@11.2.0 test:watch
> ng test

✔ Browser application bundle generation complete.
20 01 2023 20:15:47.984:WARN [karma]: No captured browser, open http://localhost:9876/
20 01 2023 20:15:48.033:INFO [karma-server]: Karma v6.4.1 server started at http://localhost:9876/
20 01 2023 20:15:48.034:INFO [launcher]: Launching browsers AngularElectron with concurrency unlimited
20 01 2023 20:15:48.047:INFO [launcher]: Starting browser Electron
20 01 2023 20:15:49.050:INFO [Electron 21.1.1 (Node 16.16.0)]: Connected on socket EbN47FWlTGsXT6ybAAAB with id 6038495
LOG: 'HomeComponent INIT'
Electron 21.1.1 (Node 16.16.0): Executed 0 of 8 SUCCESS (0 secs / 0 secs)
LOG: 'HomeComponent INIT'
Electron 21.1.1 (Node 16.16.0): Executed 1 of 8 SUCCESS (0 secs / 0.073 secs)
LOG: 'PageNotFoundComponent INIT'
Electron 21.1.1 (Node 16.16.0): Executed 2 of 8 SUCCESS (0 secs / 0.087 secs)
LOG: 'APP_CONFIG', Object{production: false, environment: 'LOCAL'}
Electron 21.1.1 (Node 16.16.0): Executed 4 of 8 SUCCESS (0 secs / 0.094 secs)
LOG: Object{}
Electron 21.1.1 (Node 16.16.0): Executed 4 of 8 SUCCESS (0 secs / 0.094 secs)
LOG: 'Run in electron'
Electron 21.1.1 (Node 16.16.0): Executed 4 of 8 SUCCESS (0 secs / 0.094 secs)
LOG: 'Electron ipcRenderer', EventEmitter{_events: Object{}, _eventsCount: 0, _maxListeners: undefined, send: function(e,...t){ ... }, sendSync: function(e,...t){ ... }, sendToHost: function(e,...t){ ... }, sendTo: function(e,t,...n){ ... }, invoke: 
async function(e,...t){ ... }, postMessage: function(e,t,n){ ... }}
Electron 21.1.1 (Node 16.16.0): Executed 4 of 8 SUCCESS (0 secs / 0.094 secs)
LOG: 'Electron ipcRenderer', EventEmitter{_events: Object{}, _eventsCount: 0, _maxListeners: undefined, send: function(e,...t){ ... }, sendSync: function(e,...t){ ... }, sendToHost: function(e,...t){ ... }, sendTo: function(e,t,...n){ ... }, invoke: 
LOG: 'NodeJS childProcess', Object{_forkChild: function _forkChild(fd, serializationMode) { ... }, ChildProcess: function ChildProcess() { ... }, exec: function(){ ... }, execFile: function(...s){ ... }, execFileSync: function(...t){ ... }, execSync: function(){ ... }, fork: function fork(modulePath, args = [], options) { ... }, spawn: function spawn(file, args, options) { ... }, spawnSync: function spawnSync(file, args, options) { ... }}
Electron 21.1.1 (Node 16.16.0): Executed 4 of 8 SUCCESS (0 secs / 0.094 secs)
LOG: 'NodeJS childProcess', Object{_forkChild: function _forkChild(fd, serializationMode) { ... }, ChildProcess: function ChildProcess() { ... }, exec: function(){ ... }, execFile: function(...s){ ... }, execFileSync: function(...t){ ... }, execSync: function(){ ... }, fork: function fork(modulePath, args = [], options) { ... }, spawn: function spawn(file, args, options) {LOG: 'DetailComponent INIT'
Electron 21.1.1 (Node 16.16.0): Executed 6 of 8 SUCCESS (0 secs / 0.195 secs)
LOG: 'DetailComponent INIT'
Electron 21.1.1 (Node 16.16.0): Executed 7 of 8 SUCCESS (0 secs / 0.226 secs)
Electron 21.1.1 (Node 16.16.0): Executed 8 of 8 SUCCESS (0.2 secs / 0.246 secs)
TOTAL: 8 SUCCESS
LOG: 'stdout:
v16.10.0
'
Electron 21.1.1 (Node 16.16.0): Executed 8 of 8 SUCCESS (0.2 secs / 0.246 secs)
LOG: 'stdout:
v16.10.0
LOG: 'stdout:
v16.10.0
'
Electron 21.1.1 (Node 16.16.0): Executed 8 of 8 SUCCESS (0.2 secs / 0.246 secs)
LOG: 'stdout:
v16.10.0
'
-----

**My sample project ng version details:**
Angular CLI: 14.2.6
Node: 16.10.0
Package Manager: npm 7.24.0
OS: win32 x64

Angular: 14.2.6
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.6
@angular-devkit/build-angular   14.2.6
@angular-devkit/core            14.2.6
@angular-devkit/schematics      14.2.6
@schematics/angular             14.2.6
rxjs                            7.5.7
typescript                      4.8.4

-----

**No luck in solving issue with below,**

1.polyfills.ts / polyfills-test.ts
(window as any)['global'] = window;
or
(window as any).global = window;

2.index.html
<script>
  if (global === undefined) {
    var global = window;
  }
</script>
 or
<script>
  global = globalThis
</script>

3.angular.webpack.js
node: { global: true }

Please suggest a way forward, Thanks.

**Comment by maximegris** [comment]
Hi

I found a way to fix this issue https://github.com/maximegris/angular-electron/commit/45bdbfac260451dd0a6097e2cedab49e66af18be

It was more a Webpack issue (Thanks to https://github.com/ryanclark/karma-webpack/issues/497#issuecomment-784434254 comment)

**Comment by kumarandena** [comment]
Hi @maximegris, 
Issue fixed, verified with the commit https://github.com/maximegris/angular-electron/commit/45bdbfac260451dd0a6097e2cedab49e66af18be
I am able to see the ng test report now, Thank you so much for the help.

**Comment by maximegris** [comment]
You're welcome :)
