### ISSUE TITLE
Error when updating to Angular 15

### ISSUE THREAD

**Issue by thibaud57** [maximegris/angular-electron#735]
I'm trying to update to Angular 15.
Everything works fine but I can't use cli commands (ng generate component ...)

I've got the follwing error : 
An unhandled exception occurred: Cannot destructure property 'aliases' of 'collection.description.schematics[schematicName]' as it is undefined.

I tried to unistall cli and install globally again + remove node module & package lock ... but nothing works.

This is my package json file:
`"dependencies": {
    "@angular/common": "15.1.2",
    "@angular/compiler": "15.1.2",
    "@angular/core": "15.1.2",
    "@angular/forms": "15.1.2",
    "@angular/language-service": "15.1.2",
    "@angular/platform-browser": "15.1.2",
    "@angular/platform-browser-dynamic": "15.1.2",
    "@angular/router": "15.1.2",
    "rxjs": "7.5.7",
    "tslib": "^2.4.0",
    "zone.js": "~0.11.8"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "15.0.0",
    "@angular-devkit/build-angular": "15.1.2",
    "@angular-eslint/builder": "15.2.0",
    "@angular-eslint/eslint-plugin": "15.2.0",
    "@angular-eslint/eslint-plugin-template": "15.2.0",
    "@angular-eslint/schematics": "15.2.0",
    "@angular-eslint/template-parser": "15.2.0",
    "@angular/cli": "15.1.2",
    "@angular/compiler-cli": "15.1.2",
    "@ngx-translate/core": "14.0.0",
    "@ngx-translate/http-loader": "7.0.0",
    "@playwright/test": "1.27.1",
    "@types/jasmine": "4.3.0",
    "@types/jasminewd2": "2.0.10",
    "@types/node": "18.11.0",
    "@typescript-eslint/eslint-plugin": "^5.43.0",
    "@typescript-eslint/parser": "^5.43.0",
    "conventional-changelog-cli": "2.2.2",
    "electron": "22.0.3",
    "electron-builder": "23.6.0",
    "electron-debug": "3.2.0",
    "electron-reloader": "1.2.3",
    "eslint": "^8.28.0",
    "eslint-plugin-import": "2.26.0",
    "eslint-plugin-jsdoc": "39.3.6",
    "eslint-plugin-prefer-arrow": "1.2.3",
    "jasmine-core": "4.4.0",
    "jasmine-spec-reporter": "7.0.0",
    "karma": "6.4.1",
    "karma-coverage-istanbul-reporter": "3.0.3",
    "karma-electron": "7.3.0",
    "karma-jasmine": "5.1.0",
    "karma-jasmine-html-reporter": "2.0.0",
    "node-polyfill-webpack-plugin": "2.0.1",
    "npm-run-all": "4.1.5",
    "playwright": "1.27.1",
    "prettier": "2.8.3",
    "ts-node": "10.9.1",
    "typescript": "4.8.4",
    "wait-on": "6.0.1",
    "webdriver-manager": "12.1.8"
  },`
  
  
  Angular CLI: 15.1.2
Node: 18.12.1
Package Manager: npm 9.2.0
OS: win32 x64

  And version:
  Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.2
@angular-devkit/build-angular   15.1.2
@angular-devkit/core            15.1.2
@angular-devkit/schematics      15.1.2
@schematics/angular             15.1.2
rxjs                            7.5.7
typescript                      4.8.4

**Comment by thibaud57** [comment]
it works when i remove 
    "cli": {
        "defaultCollection": "@angular-eslint/schematics"
    },
    
    from angular.json

**Comment by maximegris** [comment]
I @thibaud57 I have just merged the angular v15 migration PR. (see https://github.com/maximegris/angular-electron/commit/a645ab4eb75d6ba988d02d1bd517e77dd1fdc59e)
It works on Windows 10 - Node: 18.12.1 - Package Manager: npm 9.2.0

Maybe you need to delete your node_modules folder.
