### ISSUE TITLE
Unable to install ng.ant.design

### ISSUE THREAD

**Issue by sabindev** [maximegris/angular-electron#748]
**Describe the bug**
Unable to resolve dependency tree error when trying to install ng.ant.design

> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: angular-electron@12.0.0
> npm ERR! Found: @angular/core@15.1.5
> npm ERR! node_modules/@angular/core
> npm ERR!   @angular/core@"15.1.5" from the root project
> npm ERR!   peer @angular/core@"^15.0.1" from ng-zorro-antd@15.0.3
> npm ERR!   node_modules/ng-zorro-antd
> npm ERR!     ng-zorro-antd@"15.0.3" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer @angular/core@"15.2.0" from @angular/animations@15.2.0
> npm ERR! node_modules/@angular/animations
> npm ERR!   peer @angular/animations@"^15.0.1" from ng-zorro-antd@15.0.3
> npm ERR!   node_modules/ng-zorro-antd
> npm ERR!     ng-zorro-antd@"15.0.3" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**To Reproduce**
ng add ng-zorro-antd

**Comment by maximegris** [comment]
`@angular/animations` is missing in your `package.json` dependencies.
Just add `"@angular/animations": "15.1.5",` in your `package.json` dependencies.
