### ISSUE TITLE
Enable TypeScript strict mode

### ISSUE THREAD

**Issue by ddubrava** [maximegris/angular-electron#753]
**Is your feature request related to a problem? Please describe.**

Hey! Could you please add TypeScript `strict` mode to a `tsconfig.json`? It's enabled by default in Angular, and since you've already enabled Angular strict options, it would be great to have TypScript strict mode as well.

**Describe the solution you'd like**

Add `strict` to a `tsconfig.json`

**Describe alternatives you've considered**

Consider enabling strict mode to avoid wasting time on refactoring :d If strict mode is turned off, you may encounter issues that could have been caught earlier with stricter type checking.

**Comment by ddubrava** [comment]
By the way, I can work on this. There are not too many errors

**Comment by maximegris** [comment]
Hi @ddubrava 
Strict mode is now active by default
Best,
