### ISSUE TITLE
Angular Material doesn't work properly

### ISSUE THREAD

**Issue by GilmardosSantos** [maximegris/angular-electron#757]
Using the Angular Material, just trying do a simple mat-card doesn't work
```
<mat-card>
    <mat-card-content>Simple card</mat-card-content>
  </mat-card>
```
Will only reproduce the Simples Card, but without all the styles from the material.

**Comment by maximegris** [comment]
Hi

Please read [this](https://github.com/maximegris/angular-electron/blob/main/HOW_TO.md) if you want to add angular material to this project.
