### ISSUE TITLE
Unable to run ngx-monaco-editor with electron

### ISSUE THREAD

**Issue by isNotOkay** [maximegris/angular-electron#758]
Hello,

I am trying to run [ngx-monaco-editor](https://github.com/miki995/ngx-monaco-editor-v2#readme) in electron but I get the following error:

```
in.ts:13 ERROR Error: Uncaught (in promise): TypeError: window.require.config is not a function
TypeError: window.require.config is not a function
    at onGotAmdLoader (ngx-monaco-editor-v2.mjs:44:36)
    at ngx-monaco-editor-v2.mjs:62:21
```
 
Did anyone manage do this?

Setting **nodeIntegration** to _true_ gets rid of the error:

```
  // Create the browser window.
  win = new BrowserWindow({
    x: 0,
    y: 0,
    width: size.width,
    height: size.height,
    webPreferences: {
      nodeIntegration: true
    },
  });

```

Unfortunately this results in _ipcRenderer_ being undefined and _electronService.isElectron_ being _false_ when opening the app in electron:
```
  constructor(
    private electronService: ElectronService
  ) {
    electronService.isElectron // false
    electronService.ipcRenderer // undefined
}
```

**Update:**

I fixed this issue by adding a _preload.js_ script:

```
window.isElectron = true;
window.ipcRenderer = require('electron').ipcRenderer;
window.webFrame = require('electron').webFrame;
```

The _electron.service.ts_ has to be adjusted like this:

```
constructor() {
    // Conditional imports
    if (this.isElectron) {
      // @ts-ignore
      this.ipcRenderer = window.ipcRenderer;
      // @ts-ignore
      this.webFrame = window.webFrame;
    }
  }

  get isElectron(): boolean {
    // @ts-ignore
    return window.isElectron;
  }
```

Make sure to load the preload script in *app\main.ts* and that _contextIsolation_ is set to _false_, otherwise the values of the preload script are not accessible on the window object:

```
  // Create the browser window.
  win = new BrowserWindow({
    x: 0,
    y: 0,
    width: size.width,
    height: size.height,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: false,
    },
  });
```

**Comment by maximegris** [comment]
Hi
I close the issue because the BrowserWindow default configuration of this project already have noteIntegration setted to `true`. 
```typescript
new BrowserWindow({
    x: 0,
    y: 0,
    width: size.width,
    height: size.height,
    webPreferences: {
      nodeIntegration: true,
      allowRunningInsecureContent: (serve),
      contextIsolation: false,
    },
  });
```

So if you had to set nodEIntegration to `true` by yourself, that means you made changes on your project that may cause the encounter issue.
Please read https://github.com/maximegris/angular-electron/issues/752#issuecomment-1544591009 if you want to add preload script with `nodeIntegration: false`
