### ISSUE TITLE
 Error: Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by Sarthhak03** [maximegris/angular-electron#759]
**Describe the bug**
Can not access 'fs' filesystem

**To Reproduce**
1. in a service file , writing a logic to read files , for that did-
2. import * as fs from 'fs';
3. fs.readFileSync()
4. getting error - ./node_modules/electron/index.js:1:11-24 - Error: Module not found: Error: Can't resolve 'fs'

**Expected behavior**

**Screenshots**

**Additional context**
 - angular 15
 - electron v-24
 - node 16.20.0

**Comment by maximegris** [comment]
Hi
Please check providers/electron.service.ts to watch how conditional import of libraries has to be done when using NodeJS / 3rd party libraries in renderer context (i.e. Angular).

**Comment by secoldPrivate** [comment]
@maximegris 

./node_modules/electron/index.js:1:11-24 - Error: Module not found: Error: Can't resolve 'fs' i

Why is the error appearing inside of index.js?
