### ISSUE TITLE
Cannot install angular material

### ISSUE THREAD

**Issue by td-michal-kepka** [maximegris/angular-electron#763]
**Describe the bug**
After executing `ng add @angular/material`
![image](https://github.com/maximegris/angular-electron/assets/135213602/d07679ca-979a-4259-b41c-30abc6b6938b)

**To Reproduce**
1. Clone latest repo and follow installation instructions in readme
2. Replace temporarily custom builders by default ones in angular.json as specified in HOW TO file
@angular-builders/custom-webpack:browser => @angular-devkit/build-angular:browser
@angular-builders/custom-webpack:dev-server => @angular-devkit/build-angular:dev-server
3. Execute ng add @angular/material

**Expected behavior**
Angular-material installs without errors

**Additional context**
 - Apple M2 - Ventura 13.2.1

**Comment by ptatoChi** [comment]
install @angular/animations@16.1.3

**Comment by nikhilnxvverma1** [comment]
I have had the same problem with angular animation several times. I usually just ```--force``` it as it suggests. If you want you can try migrating your entire [angular stack to the next version if available](https://update.angular.io/)
