### ISSUE TITLE
New window

### ISSUE THREAD

**Issue by pragasam1016** [maximegris/angular-electron#767]
I have to open new popup window to get some user input. 

  openPopup(){
    window.open(`${window.location.href}/popup/`)
  }

This is available in the angular app. **popup** is the new component in the angular

It is working good in the local environment. The electron is creating new window and it is loading the html controllers in the new popup.
It is taking a path of **http://localhost:4200/popup** 

when we take a build and install it OR if we stop localhost in the local environment it is not working. It looks for the file system path like **file://C:/..**  that which is not fine 

Expectation :

I am looking for a solution where i can open popup angular component as a popup window in electron js.

**Comment by maximegris** [comment]
I would suggest you to read this official article about opening windows from the renderer 

https://www.electronjs.org/docs/latest/api/window-open

By the way I would suggest you to use directly dialog/pop-in with Angular (for a better UX)
