### ISSUE TITLE
Karma is now deprecated, what's next?

### ISSUE THREAD

**Issue by FrancescoBorzi** [maximegris/angular-electron#768]
With Karma being now deprecated and Angular moving to Jest / Web Test Runner, I think we should also consider moving forward angular-electron.

References:

https://github.com/karma-runner/karma#karma-is-deprecated-and-is-not-accepting-new-features-or-general-bug-fixes

https://blog.angular.io/moving-angular-cli-to-jest-and-web-test-runner-ef85ef69ceca

https://modern-web.dev/docs/test-runner/writing-tests/mocking/

**Comment by maximegris** [comment]
I think we could start using Jest instead of Karma.

I make a quick test by adding @angular-builders/jest library after removing all reference to karma & jasmine.
It works well on my default unit tests but these are not exhaustive...

**Comment by maximegris** [comment]
I took the opportunity to merge the MR #771 relative to JEST migration after merging Angular 17 MR. 

Thanks again.
