### ISSUE TITLE
Kinectron

### ISSUE THREAD

**Issue by forvy** [maximegris/angular-electron#779]
Hi, thank you for developing this cool project. 

I'm new to Electron. Just want to make sure how should I integrate the https://github.com/kinectron/kinectron kinectron file into the electron folder? What I want to achieve is to use the Azure Kinect SDK function inside the Angular app. Any suggestion would be appreciated. Thank you

**Comment by HCenggel** [comment]
I think you should describe the specific needs

**Comment by maximegris** [comment]
Sorry I cannot help you here, I do not provide 3rd party lib integration support.
