### ISSUE TITLE
How can I change the splash screen image?

### ISSUE THREAD

**Issue by Haytam95** [maximegris/angular-electron#788]
Hi ! First of all, thanks for this great boilerplate.

I have a quick question, how can I change the `splashScreen` when the application is starting?

By default it has in the file `electron-builder.json` and `builder-effective-config.yaml`

```
"portable": {
    "splashImage": "dist/assets/icons/electron.bmp"
  },
```

I tried changing that to another image (electron.jpg for example), but the new splash never displays. Is there any requirement for the image or somewhere else to change?

**Comment by erwinvanlun** [comment]
change src/assets/background.jpg?

**Comment by Haytam95** [comment]
I tried changing that image (it's a bmp) and nothing is shown during the startup

**Comment by maximegris** [comment]
The documentation is not clear about that but first be sure your new image is [a bitmap with 24bit and nonzero resolution](https://github.com/electron-userland/electron-builder/issues/5390#issuecomment-1312902198.  Check this thread, it give you tools to convert your .bmp image to 24bit file. I tried with Paint it worked.

Then you can find `electron.bmp` file in `assets/icons` folder.

Two way to replace the splash image :
* Replace the current file by yours while keeping the same name.
* Add your .bmp image in this folder, then replace `electron.bmp` in both files you mentionned.

**Comment by Haytam95** [comment]
Thanks!
