### ISSUE TITLE
Replace electron packager with electron-builder

### ISSUE THREAD

**Issue by P1-Ro** [maximegris/angular-electron#81]
Is there any chance that Electron Packager will be replaced by [electron-builder](https://github.com/electron-userland/electron-builder)? 

Because electron-builder builds actual installation file and provides easy way for automatic updates.

**Comment by seopei** [comment]
#86

**Comment by P1-Ro** [comment]
@seopei thanks :+1:

**Comment by maximegris** [comment]
Merged! Thanks 👍

**Comment by chrisfoster78** [comment]
@seopei I have been trying to use electron-updater and have hit a number of version issues with core/js and electron-builder that I have been unable to resolve.  I don't suppose you have managed to get auto updates to work?

**Comment by seopei** [comment]
@chrisfoster78 I have no troubles with auto updates. Please give me more information about your issues.
