### ISSUE TITLE
running the karma test does not work with external node modules

### ISSUE THREAD

**Issue by elovin** [maximegris/angular-electron#83]
As long as I do not use external node modules karma runs fine,
but as soon as I import an external module like this `import * as Bleno from 'bleno`,
karma cant find the module bleno, electron however can.

I tried adding the following to the karma.conf.js which lets karma start but ofcourse it cant find the require statements as soon as i click debug:

`    webpack: {
      externals: {
        child_process: 'require("child_process")',
        noble: 'require("noble")',
        bleno: 'require("bleno")'
      }
    },`

So I need webpack as a preprocessor  for the require statements.
When I add karma-webpack to the plugins and use webpack as a preprocessor I have problems with the test.ts file, this should work without karma-webpack correct ? (I used [this](https://stackoverflow.com/questions/38573690/uncaught-referenceerror-require-is-not-defined-on-karma-start-karma-conf-js) as an example to use webpack with karma)

adding node_modules/bleno/index.js to the files: [] does not work either.

So how can I add external modules to karma ?

UPDATE:

Okay as I understand it, karma is only for client side tests and mocha for server side tests so I should test my code with the 3th party modules with mocha =?!

**Comment by elovin** [comment]
I use mocha + chai now for any backend tests and karma + mocha + chai for frontend instead of jasmine.

**Comment by arcovoltaico** [comment]
Could you add a test.js and specs example using karma + mocha + chai ? Also a config guide would be extra awesome ;-)
