### ISSUE TITLE
Is it possible to configure hot reload?

### ISSUE THREAD

**Issue by EdoardoSchnell** [maximegris/angular-electron#87]
Hi,

First, let me say it, great repository 👍 

My app writes json files and every time it does the hot reload kicks in, throwing the user back at the home page. Is there any way to configure/disable it? I've looked into `webpack.config.js` and both `main.ts` with no luck...

**Comment by speccaN** [comment]
I got the same issue

**Comment by mo2menelzeiny** [comment]
@EdoardoSchnell @speccaN, the hot-reload is basically done in this project using Webpack's watch feature, it's implemented here in the NPM scripts that starts your application. https://github.com/maximegris/angular-electron/blob/32b56c4080f1832e144f060af5e819de72dc3a1d/package.json#L22
I guess to disable it you gotta remove the `webpack:watch` part of the start script.

**Comment by speccaN** [comment]
@mo2menelzeiny  Alright, I'll give that a try! Thanks for the help!

**Comment by mo2menelzeiny** [comment]
@speccaN you're most welcome
