### ISSUE TITLE
NPM packages installation error

### ISSUE THREAD

**Issue by jamzi** [maximegris/angular-electron#9]
Hey. When I run npm install after cloning the repo, I get next error: 
![image](https://cloud.githubusercontent.com/assets/2678290/25562864/b1c9167c-2d90-11e7-8b4f-d3963098ab90.png)
The Angular part (the CLI process) works, when I run npm start, but the Electron part doesn't.

**Comment by jamzi** [comment]
Update. It seems to be an issue with **extract-zip** package. The workaround for now is to especially set the version of this package in package.json. It should look like this:

    "electron": "~1.6.5",
    "extract-zip": "=1.6.0",
    "electron-packager": "~8.6.0",

**Comment by maximegris** [comment]
Hi,

Indeed `npm install` is broken...
I added the workaround in `package.json`.  Tested with npm v3+ and it works :)
Thanks!
