### ISSUE TITLE
Possibility of moving from Webpack to Angular CLI

### ISSUE THREAD

**Issue by mo2menelzeiny** [maximegris/angular-electron#93]
I understand that the main limitation is the inclusion of external npm modules, however the benefits of Angular CLI are very tempting to research into t his.

I've also came across some repositories that implement the link between Electron and Angular by using Gulp in addition to sustaining the hot reload feature.

Example repositories:
- https://github.com/sean-perkins/angular-electron-seed
- https://github.com/Teradata/covalent-electron

So the question is, is it possible to migrate and what are the pros and cons?

**Comment by maximegris** [comment]
Both solutions are acceptable.
When I started this project, I decide not to include another task runner like Gulp. On the contrary I wanted to control Webpack settings to work this node modules & web dependencies.

By the way you can still submit a pull request with Gulp and the same level of functionnality/integration. :)
