### ISSUE TITLE
Npm start dont show anything

### ISSUE THREAD

**Issue by GBurgardt** [maximegris/angular-electron#96]
Hi! I am trying to make npm start in an old project (it was not touched 4 months ago) and it does not start. I make npm start and it does not start the app. I think it may be something simple, but I can not think what it is.

**Comment by mo2menelzeiny** [comment]
@GBurgardt There aren't any logs showing or errors?

**Comment by DrMabuse23** [comment]
well same here my porblem is electron start before webpack is done i get ...."index.html" not found but only first time! after reload everything works fine

**Comment by GBurgardt** [comment]
@mo2menelzeiny The log does not throw any errors, the last lines show this.

` [437] ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./src/styles.scss 2.19 kB {2} [built]
 [439] ./src/assets/fonts/YulindaScriptDemo.otf 88 bytes {2} [built]
    + 427 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 1.36 kB {0} [built]
`
And then nothing happens, the app does not open as it should.

**Comment by mo2menelzeiny** [comment]
@GBurgardt can you include your package.json file as well
