### ISSUE TITLE
get win Object

### ISSUE THREAD

**Issue by az114q** [maximegris/angular-electron#97]
how can I get win:BrowserWindow in component？ I try to write own close window function,but I can get this win.

**Comment by xama5** [comment]
Hi, I think I figured it out with the help of StackOverflow.
[Link to answer](https://stackoverflow.com/a/31174463/7561667)

Basically what you need to do is to extend /src/app/providers/electron.service.ts to look like this:

```
import { Injectable } from '@angular/core';
import { ipcRenderer  } from 'electron';
import * as childProcess from 'child_process';

// add this
import BrowserWindow = Electron.BrowserWindow;

@Injectable()
export class ElectronService {

  ipcRenderer: typeof ipcRenderer;
  childProcess: typeof childProcess;
  // and this
  window: BrowserWindow;

  constructor() {
    if (this.isElectron()) {
      this.ipcRenderer = window.require('electron').ipcRenderer;
      this.childProcess = window.require('child_process');
      // and this too
      this.window = window.require('electron').remote.getCurrentWindow();
    }
  }

  isElectron = () => {
    return window && window.process && window.process.type;
  }
}
```
Now you can access the window like this:

```
import {Component, OnInit} from '@angular/core';
import { ElectronService } from './providers/electron.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  constructor(public electronService: ElectronService) {}

  ngOnInit() {
    // immediately close window after component initalization
    this.electronService.window.close();
  }
}
```

**Comment by az114q** [comment]
ok,I will have a try. thank you

**Comment by rm-code** [comment]
I tried the same for "App", but couldn't get it to work.

```
import App = Electron.App;

...

this.app = window.require( 'electron' ) ...?
```

Or is it different for the App module?

**Comment by xama5** [comment]
@rm-code What are you actually trying to do with the Electron.App object?
Also, for me, your question seems unrelated to this issue. I'd suggest opening a new issue.

**Comment by rm-code** [comment]
> @rm-code What are you actually trying to do with the Electron.App object?
I wanted to use it to be able to handle "quitting" and going "fullscreen" correctly and I thought that's done via the App.

> Also, for me, your question seems unrelated to this issue. I'd suggest opening a new issue.
Yeah you are right. I just thought it might be the same process to get the App.

**Comment by xama5** [comment]
@rm-code Ah, in this case, you want to use my approach to get the window object. You can go fullscreen with the `setFullscreen`-method and quitting the app is done with `close()`

**Comment by rm-code** [comment]
Perfect! Thanks a lot :+1:
