### ISSUE TITLE
Not allowed to load local resource:

### ISSUE THREAD

**Issue by mmick66** [maximegris/angular-electron#98]
I follow the steps but when I run `npm start` I get an error in the browser's window console:
```
Not allowed to load local resource: file:///Users/[my-home-directory]/angular-electron/dist/index.html
```

**Comment by StevePorter92** [comment]
@mmick66 I did the solution in https://github.com/StevePorter92/angular-electron/commit/136344b1cb96ea9947a080394c2280721ff45667 and it seemed to do the trick for me. Can you see if you have any luck?

**Comment by jakehockey10** [comment]
@StevePorter92 , I'm still having this issue and I'm using the latest from angular-electron.  Any other ideas about what's going on?

**Comment by StevePorter92** [comment]
Hey @jakehockey10, I'll take another look this evening. I was dubious as to why the fix suddenly meant it started working for me.

**Comment by jakehockey10** [comment]
@StevePorter92 did you end up having another look at this?
