### ISSUE TITLE
Move dependencies to devDependencies, to reduce final application size

### ISSUE THREAD

**Issue by eugenious** [maximegris/angular-electron#99]
When building the final application artifact (dmg, exe, etc), I found that during the build, electron-builder is smart enough to include /dist/node_modules in the final output, and EXCLUDE devDependencies automatically. (https://www.electron.build/configuration/contents)

But in this starter project there are several dependencies (such as @angular/*), so this means that they are being included in the generated .asar.

Is it necessary to include these node_modules in the final application, since they are being included as part of the webpack generated bundles already? I believe those files are unnecessary and just take up space.

So, I would suggest moving all dependencies into devDependencies instead.

As a data point, I have done this in my own project and it seems to have no ill-effects. The final application size went from 39MB to 34MB (windows exe), and from 62MB to 48MB (mac dmg).

**Comment by maximegris** [comment]
Thanks for the advice. (Done)

**Comment by icharge** [comment]
I have a question. If I have to install another module then I have to use `npm i xx --save-dev` ??

**Comment by cjackson234** [comment]
Is it an app or dev dependency?

**Comment by icharge** [comment]
App dep

**Comment by leonardochaia** [comment]
It may be useful to add this to the readme.
I'm new to Electron and was wondering why all dependencies where in devDependencies.
Thanks.
